private-attribution/ipa

pre-commit

This does all of the checking that might a typical rust project needs.
Skip these checks with `git commit -n` if you know your code is busted.
Otherwise, this will prevent bad stuff from hitting the tree.

Add pre-commit hook

---

.gitignore
src/helpers/event.rs

A quick and simple commit and pull request test, adding a couple of lines in .gitignore.
Also testing `fallback_matchkey()` during `generate_event_report()` if a match key has not been generated for the user for a particular provider.

Test fallback_matchkey

---

src/error.rs
src/lib.rs
src/net/mod.rs
src/net/server.rs
src/net/thread.rs

A simple thread module with mspc channel for sending jobs / terminating the thread. A thread will wait indefinitely for incoming messages from the caller (`Receiver`'s `recv()` is blocking). Message will either contain a function to be executed by the thread, or a message to let the thread to terminate itself gracefully.
I'll use this thread mod to create a server module in the next diff.
```
❯ cargo test --lib net -- --nocapture
Compiling raw-ipa v0.1.0 (/Users/taiki/src/raw-ipa)
Finished test [unoptimized + debuginfo] target(s) in 0.43s
Running unittests (target/debug/deps/raw_ipa-6735d863a171d867)
running 1 test
Worker 0 received a job; executing.
Terminating thread 0
Worker 0 is shutting down.
test net::server::tests::test_no_panic ... ok
test result: ok. 1 passed; 0 failed; 0 …
```

Thread module to be used for server connection handler

---

src/net/mod.rs
src/net/server.rs
src/net/thread.rs

This is a stacked branch of my previous PR: [Thread module to be used for server connection handler #18](https://github.com/martinthomson/raw-ipa/pull/18)
New commits for this pull request begin at [886ac46](https://github.com/martinthomson/raw-ipa/commit/886ac46cd482407befd3e7e78a7e5162997b6cf6)
This diff implements `Pool` which consists of a vector of `Thread`s. Now, a single thread object is a size(1) `Pool`.

[Stacked Diff] Thread pool object for concurrent connections handling

---

src/net/handler.rs
src/net/mod.rs
src/net/server.rs
src/net/thread.rs

This is a stacked branch of my previous PR: [[Stacked Diff] Thread pool object for concurrent connections handling #19
](https://github.com/martinthomson/raw-ipa/pull/19)
New commits for this pull request begin at [dfad8b8](https://github.com/martinthomson/raw-ipa/commit/dfad8b8218909876c440f9b6515aecbab163f56d)
This commit adds a connection handler and basic networking IO.
1. `Server` spawns a new thread (`ConnectionHandler`) to create a `TcpListener` and a pool thread
2. For each accepted connection, `ConnectionHandler` will send the stream to any available thread
3. Each thread will handle the actual IO operation. Once the operation is completed, the thread returns to idle state
For testing purpose, I created `Echo` server command, which just returns whatever the server received.

[Stacked Diff] Implement basic networking for stream IO over TCP

---

src/net/client.rs
src/net/data.rs
src/net/handler.rs
src/net/mod.rs
src/net/server.rs
src/net/thread.rs

This is a stacked branch of my previous PR [[Stacked Diff] Implement basic networking for stream IO over TCP #20
](https://github.com/martinthomson/raw-ipa/pull/20)
New commits for this branch begin at [ee4190b](https://github.com/martinthomson/raw-ipa/commit/ee4190b9d4142632b8f0dd18ecc9b7b6d4660763)
This commit adds a simple TCPStream client which enables sending a `Command` to a specified server and receiving the result from it. Client is pretty much the same as what I have in server.rs unit tests, but refactored into its own file.

[Stacked Diff] Implement a client module to send commands to a network server

---

Cargo.toml
src/helpers/mod.rs
src/helpers/models.rs

Quick implementation of source/trigger events and IPA query data models. Actual parameter types require further reviews but submitting the first try for PoC.

Events and query structure definitions

---

Cargo.toml
src/error.rs

instead of implementing a custom macro to handle error enum, use [`thiserror` crate](https://docs.rs/thiserror/1.0.31/thiserror/) to simplify errors definition.
Not only will this remove a macro, it will make it easier to expand errors and error handling moving forward.
Particularly, we should consider sub-typing errors, either on a per-topic (ie, "parsing errors" vs "io errors"), or a per-module (ie, "the http module" vs "the pipeline module") basis.
What this could mean in practice is that the `main()` function will have a top-level `Error`, which breaks down into more specific errors.
If we delineate per-topic, we will use the `Error` type throughout the code base, and have heterogeneous error types that compose. this requires some extra work to allow for, say, a subtype of a subtype …

simplify error definitions and discuss more robust error handling

---

src/lib.rs

It is disabled by default.
https://rust-lang.github.io/rust-clippy/master/#clone_on_ref_ptr
Motivated by https://github.com/rust-lang/rfcs/issues/2588

Enable clippy rule clone_on_ref_ptr

---

Cargo.toml
src/bin/helper.rs
src/bin/ua.rs
src/cli/verbosity.rs
src/net/server/mod.rs
src/net/thread.rs
src/user.rs

Tracing crate has all features we're using currently (print to stderr, verbosity, format) and is required to instrument MPC helpers with telemetry required to understand the performance of it and different protocols we'll be experimenting with.
This change also adds some pretty basic tracing of HTTP requests by using `tower-http` crate.
`stderrlog` crate is removed as we no longer need to use it. Besides that, it has a security advisory against it
```
Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── chrono 0.4.19
└── stderrlog 0.5.3
└── raw-ipa 0.1.0
error: 1 vulnerability found!
``` …

Migrate to `tracing` crate

---

Cargo.toml
src/field.rs
src/lib.rs
src/shamir.rs

This change adds Shamir secret sharing implementation over a finite field (implementation of FF is provided by [`ff`](https://docs.rs/ff/latest/ff/) crate. This implementation supports share addition if field that is used for coefficients and secrets is a finite prime field. 
The goal is to be able to execute secure addition (and later secure multiplication) protocol over the wire by running helper instances that perform MPC and client that submits the job. 
There are plenty of [SSS implementations](https://crates.io/keywords/shamir) written in Rust, however most of them use binary fields GF(2^n) which makes it impossible to implement share addition in O(1). See [this](https://en.wikipedia.org/wiki/Finite_field_arithmetic#Addition_and_subtraction) for more information.

Implement Shamir secret sharing over a finite field

---

Cargo.toml
src/prss.rs

* x25519-dalek: upgrade to v2 as it uses rand 0.6 and we don't need rng adapter anymore
* bump up rust compiler version to 1.62
* sort dependencies

Cargo.toml housekeeping

---

src/prss.rs

The output here is too low entropy to avoid collisions, so run it a few
times.

Update a flaky test

---

src/bin/ipa_bench/gen_events.rs
src/bin/ipa_bench/sample.rs
src/helpers/models.rs

This diff changes source and trigger event structures in the following way:
1. Change "breakdown_key" and "zkp" fields' type from string to u32.
2. Duplicate fields that exist in trigger event to source event and vice versa. This ensures that two aribtrary data chunks are indistinguishable so that an observer cannot learn whether one is a source or trigger event.
3. Add a flag (boolean) to indicate whether the event type is source (false/0) or trigger(true/1).

Modify event structures

---

scripts/start-helpers.py

This python script launches multiple [helper] CLI (MPC server) instances bound on given ports. This is to be used together with a client CLI to test out IPA protocols (#36).
* Launch 3 helper instances on ports from 9876 to 9878 (and Ctrl-C to terminate all instances)
```
❯ python3 ./scripts/start-helpers.py -e ./target/debug/helper -p 9876 -n 3
INFO raw_ipa::cli::verbosity: Logging setup at level debug
INFO raw_ipa::cli::verbosity: Logging setup at level debug
INFO raw_ipa::cli::verbosity: Logging setup at level debug
INFO helper: listening to http://127.0.0.1:9878
INFO helper: listening to http://127.0.0.1:9877
INFO helper: listening to http://127.0.0.1:9876
^C
Traceback (most recent call last):
File "/Users/taiki/src/raw-ipa/./scripts/start-helpers.py", line 55, in <module> …
```

Python script to start helper servers

---

src/prss.rs

Some clown forgot to feed a fresh index into the second call to
random(), so we were getting a collision with 1/31 probability.
Fix that.

Fix the three_party_random test properly

---

src/field.rs
src/securemul.rs

It is convenient to have a common implementation without requiring all field implementations to define their own. Unfortunately I couldn't use (or I don't know how) `From<Field> for u128` because `Field` is a trait so I ended up defining a method on the trait itself.

Field: add as_u128 method

---

research-prototype/README.md

to call `replicated-ring-party.x` we don't need that many indirections, it was a copy-paste bug introduced by me.

Update commands in README.md

---

src/field.rs
src/securemul.rs

As we discussed in #55 it is a waste of space to use `u128` to send copies of `Fp31` between helpers. This change makes it a requirement for all fields to implement serialization. It also provides an out-of-the-box implementation for `Fp31` which is efficient enough (1 byte per instance) to be used in our test implementation.
Given that now `Field` elements may be sent across `await` points, there is a need for `Field` to be `Send + 'static`. 
Note that there are some issues with this implementation that need to be addressed
- The level of granularity for serializers (as well as buf writers) is byte (`u8`). Serde provides `serialize_u8` method and similar crates (`bytes`, "std::io::Cursor", etc) also work with bytes. That means if `Field` implementation needs 42 bits of information, we'll …

Make Field serializable

---

src/prss.rs
src/securemul.rs

The comments I had on #66 might be easier to resolve with this change in place.  There are a few things that need to be merged (ProtocolId from #66 and SpaceIndex from this one) to make this all come together, but I wanted to get the pieces in place first.

Split the PRSS code into multiple spaces

---

src/helpers/ring.rs
src/replicated_secret_sharing.rs

Rust 1.63 brought some new clippy lints, fixing them to make main compile

Fix new clippy warnings

---

src/prss.rs

I'm not entirely clear on the relative benefits of using this over the
fixed-key model of AES - particularly as we are reducing the `u128`
modulo $p << 2^{128}$ - but this seems like a relatively cheap way to
build the function.  This function provides correlation robustness,
whereas the fixed-key mode used previously does not.
Paper: https://eprint.iacr.org/2019/074
Function: $\mathsf{MMO}^{\pi}$

Use the MMO^pi function for PRSS

---

src/helpers/mod.rs
src/helpers/ring.rs

There seem to be more and more protocols we need to implement that require helpers to know their exact position inside the MPC ring. For instance, modulus conversion needs to construct binary secret shares differently depending on which helper performs this operation (#63).
Secure sort (#66) seem to need that as well as it requires helpers to agree on constructing a secret share of `1`.
This change adds necessary plumbing to make helper identity available for protocol writers - `ctx.helper_ring.identity()` should return the exact helper location

Add Helper Identity enum

---

Cargo.toml
src/chunkscan.rs
src/helpers/mock.rs

Previously `receive` was running a tight loop where on each iteration it checked whether the message is available or not. This change makes all the hard work happening inside one task that holds onto a local buffer of messages, so we don't need any synchronization there. The communication between the event loop and `receive` function is done via oneshot channels. 
We discussed this optimization [here](https://github.com/akoshelev/raw-ipa/commit/5f50e270eeb20e86db0687b1de61fb13b89c0815#r82460624) and this change should fix #62

Remove spin and wait from receive

---

Cargo.toml
src/bin/helper.rs
src/bin/ipa_bench/cmd.rs
src/bin/ipa_bench/gen_events.rs
src/bin/ipa_bench/ipa_bench.rs
src/bin/test_mpc.rs
src/cli/metric_collector.rs
src/cli/mod.rs
src/cli/stats.rs
src/cli/verbosity.rs
src/lib.rs
src/net/server/mod.rs
src/telemetry/mod.rs

There are currently two metrics implementations that most of the crates use:
* [OpenTelemetry](https://docs.rs/opentelemetry/latest/opentelemetry/#metrics)
* [Metrics](https://docs.rs/metrics/0.19.0/metrics/)
Both provide similar API that allows creating counters, gauges and histograms.
However, there seem to be a warning that OpenTelemetry implementation is not stable.
Also, OpenTelemetry crate is more than just metrics, it also provides tracing API,
which may shadow `tracing` if pulled in scope.
Because of these reasons, this change suggests to use `Metrics` crate. However, it is
likely that we would need to start using OpenTelemetry at some point because it
provides integration with many open-source and third-party metric/trace collectors
and visualization tools. I don't believe we …

Introduce metrics to the system

---

src/secret_sharing/replicated.rs

as it implements `Add`, it should also implement `AddAssign` to make `+=` work

Implement AddAssign for `Replicated<F>`

---

Cargo.toml
src/bin/helper.rs
src/helpers/mock.rs
src/protocol/mod.rs
src/protocol/securemul.rs
src/test_fixture/logging.rs
src/test_fixture/mod.rs
src/test_fixture/world.rs

Add traces to various code blocks inside this module to improve traceability.
Implement logging setup for tests and use it inside securemul.rs. Trace level can be controlled by setting `RUST_LOG` variable
```bash
RUST_LOG=trace && cargo test
```
```
2022-09-20T01:27:34.860994Z TRACE send{target=H2 record_id=RecordId(1) msg=DValue { d: 2_mod31 }}:get_connection{peer=H2 step=TestStep/Mul1[1]}: raw_ipa::helpers::mock: Requesting connection
2022-09-20T01:27:34.862044Z TRACE send{target=H3 record_id=RecordId(1) msg=DValue { d: 11_mod31 }}:get_connection{peer=H3 step=TestStep/Mul1[1]}: raw_ipa::helpers::mock: Requesting connection
2022-09-20T01:27:34.862148Z TRACE send{target=H1 record_id=RecordId(1) msg=DValue { d: 22_mod31 }}:get_connection{peer=H1 step=TestStep/Mul1[1]}: …
```

Instrument mock module

---

Cargo.toml
src/bin/helper.rs
src/helpers/mesh.rs
src/helpers/mock.rs
src/lib.rs
src/protocol/context.rs
src/protocol/mod.rs
src/protocol/securemul.rs
src/protocol/sort/bit_permutations.rs
src/protocol/sort/mod.rs
src/test_fixture/logging.rs
src/test_fixture/mod.rs
src/test_fixture/world.rs

[Semi honest sort] Computing bit permutations
Executes sorting of a bit column on mpc helpers. Each helper receives their input shares and do following steps
1. local computation by `prepare_mult_inputs` which outputs 2 vectors [x,y]
2. multiply each row of previous output individually (i.e. x*y) across mpc helpers.
3. add ith column by i+len to obtain helper's share of sorted location, where len is same as input shares length
PS: Have stacked this over the "refactor" branch changes so you would see more changes than needed for this commit

[Semi honest sort] Computing bit permutations

---

Cargo.toml
benches/oneshot/arithmetic_circuit.rs
src/bin/helper.rs
src/bin/ipa_bench/cmd.rs
src/bin/ipa_bench/gen_events.rs
src/bin/ipa_bench/ipa_bench.rs
src/bin/ipa_bench/sample.rs
src/bin/test_mpc.rs
src/cli/stats.rs
src/cli/verbosity.rs
src/protocol/securemul.rs
src/protocol/sort/apply.rs
src/secret_sharing/shamir.rs
src/test_fixture/sharing.rs

* Upgrade to clap v4 from structopt. Structopt is in maintenance mode and has been ported to clap_derive. 
* Bump the deps
* Bump Rust compiler to 1.64
* Remove unused dependencies

Cargo.toml: remove unused deps, bump versions, etc

---

src/helpers/prss.rs

This version probably doesn't address @richajaindce's issues because it requires that a mutable reference to the RNG be obtained.  I'll follow up with a less efficient version that might be easier to use.

Turn PrssSpace into an Rng

---

src/protocol/sort/reshare.rs
src/test_fixture/world.rs

1. Fixing reshare test to avoid flaky behavior
2. Adding a test to validate a new space is generated for each step
3. Added assert in shuffle to ensure steps do not share prss.

Fixing test and adding asserts

---

src/protocol/context.rs
src/protocol/mod.rs
src/protocol/modulus_conversion/gen_random.rs
src/protocol/modulus_conversion/mod.rs
src/protocol/securemul.rs
src/test_fixture/mod.rs

To convert from XOR secret shares of match keys, the lists of replicated secret sharings of each bit in Z_p, we will need to generate pairs of secret sharings of "r", a random number not known to any of the helpers.
This diff introduces code that given a binary replicated secret sharing of "r" (which can be locally generated using PRSS), converts that into a replicated secret sharing of the same value in Z_p. This is the main work involved in the modulus conversion.
There are additional optimisations to add later.

Mod conversion [Part 1]

---

src/helpers/messaging.rs
src/protocol/reveal.rs
src/protocol/securemul.rs
src/protocol/sort/reshare.rs

There is currently no need to take an exclusive reference to self. Given that `Mesh` is no longer a trait, this change is fairly easy to make.
Taking a shared reference instead of `&mut self` enables protocols to run multiple concurrent multiplications at the same time.
The use case for it is presented in #128

`Mesh` methods take shared reference

---

src/protocol/context.rs
src/protocol/mod.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/mod.rs
src/protocol/reveal_additive_binary.rs
src/secret_sharing/replicated.rs

Assume that the browser will secret share a match key into XOR secret shares, with each share encrypted towards a different helper.
Upon decryption, each helper will possess just one share (i.e. not a replicated sharing).
Assume we interpret this as a bit-packed array of secret sharings in Z_2. Basically, for each of the bits of the match key, there are three shares, each one boolean, and each helper possesses just one of them.
This ConvertShares protocol takes in a u64 (which is interpreted as a bit-packing of up to 64 of these Z_2 secret sharings) and converts this to a vector of secret-sharings in a larger field, where each element of the vector is a sharing of either zero or one.
Example:
`0b11001`
```
vec![ 
Replicated<F>, // a random sharing of `1` 
Replicated<F>, // a random …
```

Implemented modulus conversion

---

src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/double_random.rs
src/protocol/modulus_conversion/mod.rs
src/protocol/modulus_conversion/specialized_mul.rs

We can use a specialized multiplication protocol to save half the communication bandwidth, because we know that a large number of shares are zero.

Optimizing the multiplication protocol used in share conversion

---

src/protocol/dot_product.rs
src/protocol/mod.rs

If you have two vectors of secret shared numbers, and you'd like to compute the dot-product of these two vectors (that is, the sum of the pairwise products), this can be accomplished with a communication cost that is equivalent to just one multiplication. That's right, it's irrelevant how long the vectors are. Pretty cool huh?

Adding a new dot-product protocol

---

src/cli/net/server/mod.rs
src/telemetry/mod.rs

This change makes IPA web server to emit a metric that shows which HTTP protocol was used for every request made to the helper. The goal is to be aware if helpers start using HTTP 1.1. Restricting server code to accept HTTP 2.0 only is not great because HTTP 1.1 is way easier to debug and therefore valuable to support.
Alternatively we could just use a config that instructs the server which protocol it should exclusively support. Right now it feels that having this visibility is enough, but we may reconsider this in the future.
Note that it may be a bit misleading if connection starts as HTTP/1.1 and then gets upgraded to HTTP/2.0 but in our setting helper clients should probably initiate HTTP/2 from the beginning.

HTTP2/HTTP 1.1 metrics for IPA server

---

src/protocol/context.rs
src/protocol/securemul.rs

This one protocol looked different from all the others. That seems weird. Let's make them more similar.

Making SecureMul just take a context

---

src/secret_sharing/malicious_replicated.rs
src/secret_sharing/mod.rs
src/secret_sharing/replicated.rs

To upgrade to malicious security, we need to run every arithmetic circuit twice; one with the original numbers, and once with those numbers times a random, secret-shared value `r`. All of the local operations (like addition, subtraction, negation, and multiplication with a constant) can be done without communication between the helpers. We just need to do them both locally. This struct should help with that. It overrides the basic math operators to ensure all of the accounting is done twice.

Adding a new struct to help with upgrading to malicious security

---

.github/workflows/check.yml

The actions-rs/cargo action isn't needed and the toolchain install is a little out of date now.
I've switched to one that seems better, but now I can't change organization settings to remove the others and enable these, so I guess it will have to wait.

Update the CI checks

---

src/protocol/prss.rs

Since yesterday, clippy seems unhappy with two `prss` tests with no obvious reason why.
```
error: non-binding `let` on a type that implements `Drop`
--> src/protocol/prss.rs:571:9
|
571 |         let _ = p1.sequential(&step);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D clippy::let-underscore-drop` implied by `-D clippy::pedantic`
= help: consider using an underscore-prefixed named binding or dropping explicitly with `std::mem::drop`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_drop
```
It either sees what I don't see, but I wasn't able to find `Drop` implementation for that type. I also wasn't able to reproduce it locally neither on MacOS nor Linux, despite the fact that I am using the same cargo version as our …

Make GH clippy happy again

---

src/helpers/buffers/mod.rs
src/helpers/buffers/receive.rs
src/helpers/buffers/send.rs

`SendBuffer` is about to receive a major overhaul, so it requires its own space. It is better to make this change in advance so subsequent reviews are easier to follow.
There are no functional changes in this PR, only refactoring

Create a folder for buffers module

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/context.rs
src/protocol/securemul.rs
src/protocol/sort/bit_permutations.rs
src/test_fixture/circuit.rs

This was @martinthomson's recommendation. I think it helps us utilize the "step" stuff better.

Make context.multiply() consume the context

---

src/ff/field.rs
src/ff/mod.rs
src/ff/prime_field.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/double_random.rs
src/protocol/reveal_additive_binary.rs
src/secret_sharing/replicated.rs

This is a stack diff on top of #157. 7f42b8a is the new diff introduced by this PR.
This diff adds the new struct `Fp2` which represents a binary field $Z_2$. `Fp2` is compatible with the existing field `Fp31` as it implements `Field`, and it automatically works with `Replicated`. `Fp2` also implements the new trait `BinaryField`, which is derived from `Field` and defines bit operations `&`, `|`, `^` and `!`. Protocols that input/output bits can either specify a generic type (i.e. `Replicated<B: BinaryField>`) or the concrete implementation (i.e. `execute(input: Fp2)`).
Implementations of the field arithmetic operations (e.g. `Add`, `Mul`, etc.) are exactly the same for `Fp2` and `Fp31`, hence I created a macro that generates `Field` implementations. One thing that has changed from the …

Fp2 field for boolean circuits

---

src/helpers/messaging.rs
src/protocol/attribution/accumulate_credit.rs
src/protocol/check_zero.rs
src/protocol/context.rs
src/protocol/malicious.rs
src/protocol/mod.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/double_random.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/reveal.rs
src/protocol/reveal_additive_binary.rs
src/protocol/securemul.rs
src/protocol/sort/bit_permutations.rs
src/protocol/sort/reshare.rs
src/protocol/sort/shuffle.rs
src/test_fixture/mod.rs
src/test_fixture/world.rs

1. remove network from gateway, which reduces the complexity of the context declaration
2. add RecordId::from(usize), which complicates usage in some places, but simplifies others
3. fix the bit permutation code
I'll split this up later if necessary, but I need to attend to other things for now.

Three changes

---

.github/workflows/check.yml

Reverts private-attribution/ipa#161 (which in turn reverted this as an original change).
This simplifies the dependencies we have on actions for rust.  Now that I've worked out how to enable the action, we can see how this works.

Update CI checks

---

src/protocol/context.rs
src/protocol/malicious.rs
src/protocol/maliciously_secure_mul.rs
src/protocol/mod.rs

The 3rd step in a stack of 3 diffs to upgrade our arithmetic circuits to malicious security.
This introduces a new "Maliciously Secure Multiplication" protocol, which performs a multiplication twice, once to compute `a * b`, and once to produce `r * a * b`. This protocol automatically updates the information theoretic MACs that will eventually be checked at the conclusion of the protocol.

Adding a Maliciously Secure multiplication protocol

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/check_zero.rs
src/protocol/malicious.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/double_random.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/reveal.rs
src/protocol/reveal_additive_binary.rs
src/protocol/securemul.rs
src/protocol/sort/bit_permutations.rs
src/protocol/sort/reshare.rs
src/protocol/sort/shuffle.rs
src/test_fixture/circuit.rs
src/test_fixture/mod.rs

Per discussion in #180, `ProtocolContext` is generic over an `F`. To support protocols that take `BinaryField` (i.e. `Fp2`) as inputs, change `make_contexts` to also become generic over `F` instead of returning a concrete implementation.

`make_contexts` returns a `ProtocolContext<'_, F>`

---

.github/workflows/check.yml
benches/ct/arithmetic_circuit.rs
benches/iai/arithmetic_circuit.rs
benches/oneshot/arithmetic_circuit.rs
pre-commit

I've also added compile benchmark target to stop the bleeding. Unfortunately that will take the PR approval run longer, open to alternatives here.

Fix compilation errors for benchmarks

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/check_zero.rs
src/protocol/context.rs
src/protocol/malicious.rs
src/protocol/securemul.rs
src/protocol/sort/bit_permutations.rs
src/test_fixture/circuit.rs

The original idea of using `async` was to provide backpressure to slow down protocols that are moving too fast. However, after doing some benchmarking, creating the multiplication struct is almost zero cost and protocol will be blocked after computing `right_d` anyway.
There is no reason to provide backpressure at the creation time - it carries no benefit compared to providing backpressure on `execute` call.

Make multiply and malicious_multiply non-async functions on `ProtocolContext`

---

src/protocol/modulus_conversion/convert_shares.rs

Looks like the way things panned out, we actually only want to get one bit at a time for sorting purposes. As such, this other API was unused and is dead code. Let's remove it for now. If we ever decide we need it later, we can retrieve it from version control.

remove dead code

---

src/ff/field.rs
src/ff/prime_field.rs

In #186, @richajaindce wants to write a test for sorting N rows of data. Sadly, she cannot test sorting more than 30 rows of data, because 30 is the maximum value we can represent with our silly test field Fp31! 
So I created a much bigger field, using the prime number `2^32 - 5`, which is the largest prime number less than 2^32.

Creating a prime field with the largest 32-bit integer

---

src/protocol/reveal.rs
src/protocol/sort/compose.rs
src/protocol/sort/secureapplyinv.rs

Stumbled across this code while looking for patterns how to use `narrow`, decided to send a quick fix
* we don't need to allocate a vector to hold the results of reveal. `try_join_all` returns a `Vec` so we can re-use it if it stores `usize` elements
* no need to take an exclusive reference to permutation for reveal operation
* naming suggestion

Small optimizations for reveal_permutation fn

---

src/error.rs
src/helpers/mod.rs
src/test_fixture/fabric.rs

I noticed that we use boxed errors inside protocols in cases where we don't have to because infrastructure errors cannot be converted to `Error` object and therefore `?` operator cannot be used.
This change was inspired by #199 where reveal protocol could've just returned `Result<(), Error>` and test for correct error type inside unit tests.

Add `InfraError` member to error type.

---

.github/workflows/audit-check.yml
.github/workflows/audit-daily.yml

Two new actions have been added. One runs the security audit (cargo-audit) if any of the cargo config files has changed. Another one runs periodically and scans Cargo.lock against advisory db. If a new CVE is posted there, new issue will be created in IPA repo (at least I hope it will, I haven't tested that part)
Tested it locally to confirm that action runs if `Cargo.*` files changed: https://github.com/akoshelev/raw-ipa/actions/runs/3375031039

Add new action to check deps against advisory DB

---

src/error.rs
src/ff/field.rs
src/lib.rs
src/net/server/mod.rs
src/protocol/attribution/mod.rs
src/protocol/context.rs
src/protocol/malicious.rs
src/protocol/mul/malicious.rs
src/protocol/mul/mod.rs
src/protocol/prss.rs
src/protocol/reveal.rs
src/protocol/sort/apply.rs
src/protocol/sort/mod.rs
src/secret_sharing/malicious_replicated.rs
src/test_fixture/world.rs

Discussed this on Wire. We mostly ignore them anyway

Suppress similar_names and module_name_repetitions lints

---

src/net/server/mod.rs
src/protocol/sort/apply.rs
src/protocol/sort/compose.rs
src/protocol/sort/secureapplyinv.rs
src/protocol/sort/shuffle.rs

Restructuring code in shuffle/applyinv/compose to consume data which is input to them and return the transformed output rather than doing an in-place change. This will help in better code readability.
It is a part of comment on #186 : https://github.com/private-attribution/ipa/pull/186#discussion_r1016252919 "What I really don't like about these 23 lines of code, is that it's not obvious which arguments are updated / modified by these Protocols. "

Restructuring code in shuffle/applyinv/compose to consume inputs

---

src/protocol/boolean/mod.rs
src/protocol/boolean/prefix_or.rs

Remove string instantiation from `BitOpStep`. Instead, use a const &str table to look up unique step strings. We assume that the bit representation of secret shared values are always less than 64.

Replace BitOpStep to use the const &str table

---

src/protocol/modulus_conversion/double_random.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/reveal.rs

Some related protocols have changed their error type as well. It is possible because of #202. Using `Error` is more ergonomic when actual error type need to be tested (in unit tests)

Move from `BoxError` to `Error` in reveal

---

src/protocol/mod.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/prss.rs

Similarly to validating steps while narrowing contexts, this change makes PRSS validate the indices passed on to it when generating randomness.
It should be a mistake to use the same index twice within the same PRSS instance. This change enables PRSS to panic and abort in such cases.
Interestingly it already helped to catch one bug inside the malicious implementation.
This should help with some issues presented in #135 as well. The cost we pay is another HashSet in memory. It can grow up to $O(N)$ where $N$ is the  size of the input. It may be acceptable for debug builds. There is also an optimization we could use to reduce the footprint https://docs.rs/tinyset/latest/tinyset/setu64/struct.SetU64.html

Validate indices used in PRSS

---

Cargo.toml
pre-commit
src/protocol/reveal.rs
src/protocol/sort/apply.rs
src/protocol/sort/compose.rs
src/protocol/sort/generate_sort_permutation.rs
src/protocol/sort/secureapplyinv.rs
src/protocol/sort/shuffle.rs
src/test_fixture/mod.rs
src/test_fixture/sharing.rs

The permutations crate has a few issues:
1.) Naming convention is reverse of the paper
2.) It *mutates* the permutation being applied, which means we have to clone permutations pretty often (wasteful)
3.) Strange Permutation.online() stuff all over the place.

Replacing permutations crate with home-rolled code

---

src/protocol/boolean/prefix_or.rs

Damgård's [paper](https://iacr.org/archive/tcc2006/38760286/38760286.pdf) describes the protocol in F_p, but my initial implementation used `BinaryField` to simplify boolean arithmetics. This, however, becomes a problem when we migrate to malicious because the chance of MACs not matching in Fp2 is 50%. This diff updates `PrefixOr` protocol to be generic over `F: Field`; a larger field than `BinaryField`.
This change affects one arithmetic logic where we calculate OR of two bits. (lines 49-55)
$OR([a], [b]) = ! ( ![a] * ![b] )$

Fix PrefixOr to work with F_p

---

src/ff/prime_field.rs
src/protocol/malicious.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/mul/semi_honest.rs
src/protocol/reveal.rs
src/secret_sharing/malicious_replicated.rs
src/test_fixture/mod.rs
src/test_fixture/sharing.rs

I tried to implement for any field, but I couldn't convince the compiler to let me do that.
This should make the testing pieces more ergonomic and maybe also some of the mainline code.

Implement Distribution<F> for Standard on prime fields

---

src/protocol/boolean/bitwise_lt.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/prefix_or.rs
src/protocol/boolean/xor.rs

This diff implements `BitwiseLessThan` protocol. It takes two bitwise-shared inputs in $\mathbb{Z}_p$ and returns 1 if and only if the first parameter is less than the second parameter. This is an implementation of "5.3 Bitwise Less-Than" described in this [paper](https://iacr.org/archive/tcc2006/38760286/38760286.pdf), [13].
`BitwiseLessThan` takes inputs $[a]\_B = ([a\_1]\_p,...,[a\_l]\_p)$ where $a\_1,...,a\_l ∈ {0,1} ⊆ F\_p$ and $[b]\_B = ([b\_1]\_p,...,[b\_l]\_p)$ where $b\_1,...,b\_l ∈ {0,1} ⊆ F\_p$, then computes $h ∈ {0, 1} := a <\{?} b$ where $h = 1$ iff $a$ is less than $b$.
`BitwiseLessThan` invokes one sub-protocol, `PrefixOr`, and `2l` mult's (`l` = bit length, `l` xor's + `l` mult's).

Bitwise Less-Than Protocol

---

Cargo.toml
benches/oneshot/sort.rs
src/helpers/messaging.rs
src/protocol/sort/generate_sort_permutation.rs
src/protocol/sort/mod.rs

Very rudimentary, just to reproduce #237
the way you would run it (if you want traces):
```rust
RUST_LOG=trace cargo bench --bench oneshot_sort --profile dev --features test-fixture
```

Add sort bench

---

src/protocol/boolean/bitwise_lt.rs
src/protocol/boolean/prefix_or.rs
src/protocol/boolean/xor.rs
src/protocol/malicious.rs
src/protocol/mod.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/mul/semi_honest.rs
src/protocol/sort/reshare.rs

I can't type `RecordId::from(0_u32)` anymore, sorry

Add From<i32> implementation for RecordId (tests only)

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/boolean/bitwise_lt.rs
src/protocol/boolean/prefix_or.rs
src/protocol/boolean/xor.rs
src/protocol/check_zero.rs
src/protocol/malicious.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/mul/malicious.rs
src/protocol/mul/mod.rs
src/protocol/mul/semi_honest.rs

Now that SecureMul doesn't throw BoxErrors, all the protocols that call it can just use normal errors. This should make it easier to match on them and stuff.

bye bye BoxError

---

src/protocol/modulus_conversion/specialized_mul.rs

We used to have to hack around. Now we can use `bind()`

Minor change to the tests

---

src/ff/field.rs
src/protocol/boolean/carries.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/or.rs
src/protocol/boolean/prefix_or.rs
src/secret_sharing/replicated.rs

This diff implements `Carries` protocol. "6.3 Computing the carry bits" from the [paper](https://iacr.org/archive/tcc2006/38760286/38760286.pdf), "Unconditionally Secure Constant-Rounds Multi-party Computation for Equality, Comparison, Bits, and Exponentiation".
`Carries` computes... well, the carries. It takes two bitwise shared secrets, and outputs a bitwise share indicating the indice where bit-carries occur.
This by itself is not useful, but this is a part of the bitwise sum protocol, which I will send out the PR next.

Bitwise Carries protocol

---

src/protocol/boolean/bitwise_sum.rs
src/protocol/boolean/mod.rs

This is a stacked diff. The commit needs to be reviewed is eb2777f4e8f236548643897d059403bd6963496b.
This diff implements `BitwiseSum`, which takes two bitwise shared inputs in $\mathbb{Z}\_p$ and outputs a bitwise shared number of the sum. This is an implementation of "6.2 Bitwise Sum" described in this [paper](https://iacr.org/archive/tcc2006/38760286/38760286.pdf).
This protocol is useful for adding bitwise shared numbers, but is also a part of the bit-decomposition protocol.
PRE∨ (PrefixOr) #195 
BIT-LT (BitwiseLessThan) #206 
SOLVED-BITS (random bit-shares) #209 
CARRIES (Carries) #219 
BIT-ADD (BitwiseSum) **this PR**

Bitwise Sum protocol

---

.github/workflows/check.yml
pre-commit
src/lib.rs

This setting prevents compiler from building the code with warnings. I think it is useful to be able to do that because often I prototype an implementation and want to see whether it compiles and it is ok if there are unadressed warnings such asunused imports. Also I want to be able to run tests and get feedback from them without addressing all the warnings.
I think we have good protection at PR level as GH action would prevent pushing code that violates this no warnings rule.
I also enabled validation for `cargo doc` if we ever need to use it  based on conversations in https://github.com/rust-lang/cargo/issues/8424
Verified it is working and failing build: https://github.com/akoshelev/raw-ipa/actions/runs/3486104797

Remove deny(warnings)

---

src/protocol/reveal/mod.rs
src/protocol/sort/bit_permutation.rs
src/test_fixture/sharing.rs

This was definitely wrong. Our tests of malicious contexts aren't yet calling validate - so this issue wasn't detected yet. But in reality, a MaliciousReplicated sharing should be a sharing of (x, r*x) and the *same* value of `r` needs be be used for the entire protocol, until it is revealed at the time `validate()` is called.

Make share_malicious accept r

---

.github/workflows/check.yml

Most of the time, PR is broken because of formatting and/or Clippy issues. Therefore, it is desirable to run these checks first and get the feedback earlier before running builds and tests. My observation (likely biased towards my own behavior) is that we rarely submit code that does not compile or tests that are broken.

Run lint/Clippy first before build in GH actions

---

benches/oneshot/sort.rs
src/protocol/malicious.rs
src/test_fixture/mod.rs

The futures crate has one of these, but it returns a tuple.  That is more flexible than this, which isn't strictly what we need.
(Not sure if we need this with other active changes inbound, but I wrote it and am putting it up anyway.)

Wrapper for joining 3 things

---

Cargo.toml
src/protocol/sort/compose.rs
src/protocol/sort/generate_sort_permutation.rs
src/protocol/sort/mod.rs
src/protocol/sort/secureapplyinv.rs
src/protocol/sort/shuffle.rs

I am on a crusade to eliminate different sources of randomness in IPA to keep PRSS and thread_rng() only. Having those prevents concurrency tests to provide "replay" functionality.
I believe we shouldn't be using any PRNG as our PRSS implementation already provides random generator that is suitable to shuffle vectors.
This change replaces ChaCha RNG with PRSS seq RNG

Use PRSS sequential randomness to generate permutation instead of ChaCha

---

src/protocol/boolean/bitwise_lt.rs
src/protocol/boolean/dumb_bitwise_lt.rs
src/protocol/boolean/mod.rs

Upon reviewing the BitwiseLessThan protocol (#206), I was struck by how incredibly complex the logic was. I found it very difficult to understand what the paper was saying, and why things needed to be that complicated.
So I thought I would implement a really dumb, straightforward way of doing things and compare performance.
- Old: 44 multiplications
- New: 28 multiplications
36% reduction
- Old: 176 multiplications
- New: 124 multiplications
30% reduction
In general, this "dumb" approach requires 4*(L - 1) multiplications.
In a debug build, when I just run `cargo test` this makes the "manual only" tests run much faster:
- Old: 28.65 seconds
- New: 18.64 seconds
35% reduction
- Old: 116.54 seconds
- New: 70.74 seconds
39% reduction

Implemeting a simple, straightforward bitwise les than protocol

---

src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/bitwise_sum.rs
src/protocol/boolean/dumb_bitwise_sum.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/or.rs

Our current BitwiseAdd protocol is VERY SLOW. I didn't understand why the current protocol was so complicated so I created a much simpler one and benchmarked it:
- Old: 35 multiplications
- New: 13 multiplications
63% reduction
- Old: 1520 multiplications
- New: 94 multiplications
94% reduction (!!!)
This makes the tests run a LOT faster.
- Old: 23.47 seconds
- New: 10.66 seconds
63% reduction
- Old: 82.82 seconds
- New: 5 seconds 
94% reduction (!!!)

Dumb bitwise add

---

src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/bitwise_less_than_prime.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/solved_bits.rs
src/test_fixture/mod.rs
src/test_fixture/sharing.rs

When comparing two unknown numbers, we need to use the BitwiseLessThan protocol. It considers many possibilities. When comparing to a specific number we don't need to check as many things. The primes we use are even more specialized, they are almost entire ones. e.g. 31 = 0b11111, and our 32 bit prime is 0b11111111111111111111111111111011. Comparing to see if a number is *less than* these values is very easy, we can just check if the number is greater-than-or-equal-to the prime and negate the result. There are very few numbers that meet this condition. Basically, nearly all the bits need to be one. That's easy to check, just multiply all the bits that are supposed to be ones.

Implementing an optimized comparison with the prime

---

src/protocol/mul/malicious.rs
src/protocol/mul/mod.rs
src/protocol/mul/semi_honest.rs

These structs aren't doing anything for us. Let's just use functions.

Kill SecureMult structs

---

src/protocol/sort/compose.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/secureapplyinv.rs

We always return the revealed permutation and also a tuple of random permutations which will be used for shuffle. Extracting it out in a struct for better code readability

[Minor] Struct RevealedAndRandomPermutations

---

benches/oneshot/sort.rs
src/helpers/messaging.rs
src/protocol/attribution/accumulate_credit.rs
src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/random_bits_generator.rs
src/protocol/boolean/solved_bits.rs
src/protocol/boolean/xor.rs
src/protocol/check_zero.rs
src/protocol/context/malicious.rs
src/protocol/context/mod.rs
src/protocol/context/semi_honest.rs
src/protocol/malicious.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/mul/semi_honest.rs
src/protocol/reveal/mod.rs
src/protocol/sort/generate_permutation.rs
src/test_fixture/circuit.rs
src/test_fixture/world.rs

This was awfully messy being in context. Given that we currently only expect the user contribution capping step to use this, let's just have that protocol generate this object and pass it in.

Move RandomBitsGenerator out of context

---

src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/generate_random_bits/malicious.rs
src/protocol/boolean/generate_random_bits/mod.rs
src/protocol/boolean/generate_random_bits/semi_honest.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/random_bits_generator.rs
src/protocol/boolean/solved_bits.rs
src/protocol/context/malicious.rs
src/protocol/context/mod.rs
src/protocol/modulus_conversion/convert_shares.rs
src/test_fixture/sharing.rs

As it's implemented now, `generate_random_bits()` calls `convert_bit_local()` which creates `Replicated<F>` instances. I'm moving `generate_random_bits()` as a trait and implement it for SemiHonestContext and MaliciousContext, so that protocols calling this method can be upgraded to malicious as well.
* Created `RandomBits` trait which has only one method 
* Malicious version of `generate_random_bits()` calls `upgrade_bit_triple()`
* Removed SolvedBits struct to align with other protocols. Now the protocol is just `solved_bits()` method
* Other mechanical changes for generics <F, S, C>

Malicious SolvedBits

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/mod.rs
src/protocol/sort/apply_sort/mod.rs
src/protocol/sort/apply_sort/shuffle.rs

`AggregateCredit` protocol takes the result from `CreditCapping` protocol, does some pre-processing (coming in the next diff), and makes two sort calls to perform the aggregation. This diff adds the sorting part of the AggregateCredit protocol.
Two sorts called during the aggregation step are:
1. Sort by aggregation_bit and then breakdown_key
2. Sort by aggregation_bit (2nd time)
`aggregation_bit` is a bit sharing of 0 or 1, and used to determine which row needs to be aggregated. This bit will be added at the beginning of the AggregateCredit protocol.

AggregateCredit Protocol #1 - Sort by aggregation_bit, breakdown_key

---

src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs

This diff adds the prefix-sum computation of the credit values per breakdown key. The computation uses the same binary-tree prefix sum approach as other attribution protocols do.

Aggregation Protocol [part 2 / 2] - Add the prefix sum aggregation

---

src/helpers/buffers/fsv.rs
src/helpers/buffers/mod.rs
src/helpers/buffers/receive.rs
src/helpers/buffers/send.rs
src/helpers/messaging.rs
src/helpers/network.rs

It is an easy mistake to make to start counting records from 1 or miss sending a record. Infrastructure stays silent and does not output anything for it. This change sets up a timer for gateway loop that prints the state of helper (if there is something pending) every 10 seconds. The output looks like this
```bash
2022-12-05T05:48:59.379513Z ERROR raw_ipa::helpers::messaging: Nothing has happened on H1 in the last 10s. Here is the list of tasks pending completion:
waiting to send: [
channel[peer=H2,step=step=protocol/run-0]: [0]
],
waiting to receive: [
channel[peer=H2,step=step=protocol/run-0]: [1, 2, 3, 4, 5, 6, 7, 8, 9]
]
```

Print helper state if nothing is going on

---

src/helpers/buffers/send.rs

It causes noise when we have long running tests. The proper solution would be to implement channel closure https://github.com/private-attribution/ipa/issues/168 as it can be seen how much memory we're wasting by not doing it.
Skipping empty buffers is correct because there is no error on the protocol side

Gateway: do not report buffers that are 100% empty

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/mod.rs
src/protocol/basics/check_zero.rs
src/protocol/basics/mul/sparse.rs
src/protocol/basics/reveal.rs
src/protocol/ipa/mod.rs
src/protocol/malicious.rs
src/secret_sharing/into_shares.rs
src/secret_sharing/malicious_replicated.rs
src/secret_sharing/mod.rs
src/test_fixture/circuit.rs
src/test_fixture/mod.rs
src/test_fixture/sharing.rs
src/test_fixture/world.rs

Test client I am making to benchmark and execute different scenarios needs to be able to secret share user input before sending it to different helpers.
Helper server implementation does not need that, so trait is hidden behind a feature flag
@martinthomson we discussed this and my initial approach was to implement a similar trait for CLI use, but it turned out to be exactly the same as `IntoShares`  and its implementations. Hope that exposing it to `cli` and `test_fixture` is good enough to prevent it from leaking to prod code

Move IntoShares trait and friends to secret_sharing mod

---

Cargo.toml
src/ff/prime_field.rs

Some time ago, field serde tests were removed, I think that was a mistake and this change brings them back.
It is a good time to move some of the tests inside the macro that generates the field implementation to ensure we run them for all field types.

Bring back field tests accidentally removed

---

src/protocol/ipa/mod.rs

I don't have enough patience to wait for 50 seconds. We should move it to end-to-end test folder if it is going to take that long

Ignore end-to-end IPA test

---

src/bin/helper.rs
src/helpers/http/mod.rs
src/helpers/http/network.rs
src/net/discovery/conf.rs
src/net/discovery/mod.rs
src/test_fixture/mod.rs
src/test_fixture/net.rs

As we discussed, each helper will be assigned a role when query processing starts. That means helpers may have different roles in different queries it participates in. Helper configuration therefore must be configured around its endpoint that stays the same regardless of number of queries it processes.
This change also removes interim structs that mirrored the end config struct, but used raw types (str, [u8]). With custom deserialize implementation it is easy to support only one hierarchy of configs

Remove roles from helper config

---

src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/random_bits_generator.rs

This changes random bits generator to accept a context once when the context is created, rather than each time randomness is requested. Because bits are generated in batches, this seems more appropriate -- the context that was supplied to the individual `get()` call where a batch happened to be generated may or may not have anything to do with the context where the bits are ultimately used.
There is still a problem for closing the communication channels associated with random bits generation since the total record count is less well defined than in some other cases. But isolating the context for random bits in this way I think offers more flexibility to solve that.
And there are still problems related to sampling the random bits in a deterministic order on each helper, that we discussed …

pass context once to RandomBitsGenerator::new

---

src/bin/helper.rs
src/helpers/http/mod.rs
src/helpers/messaging.rs
src/test_fixture/world.rs

This turns out to have a measurable effect on test running time, at least on my machine.  It's worth about a second overall.
I considered tuning this with more runs, but we've got enough churn ahead of us that I am going to suggest we hold off.

Buffer the send/recv channels

---

src/bits/bit_array.rs
src/bits/mod.rs
src/ff/field.rs
src/ff/mod.rs
src/ff/prime_field.rs
src/protocol/basics/mul/mod.rs
src/protocol/basics/reshare.rs
src/protocol/basics/reveal.rs
src/protocol/boolean/generate_random_bits/mod.rs
src/protocol/context/mod.rs
src/protocol/sort/apply_sort/shuffle.rs
src/secret_sharing/mod.rs

Another refactoring towards supporting XOR replicated shares (see the diagram below for the overall design). This diff adds a new intermediate trait for secret shared values i.e., fields, bit arrays, that helps abstract away the implementations of the secrets from contexts and context dependent protocols such as `SecureMul` (red box in the diagram).
For now, I bounded the context to `Context<V: SharedValue + ArithmeticOps>`, basically equivalent to `F: Field` leaving the current behavior intact.

`SharedValue` trait for secret shared value types

---

.github/workflows/check.yml
pre-commit
src/cli/playbook/input.rs
src/helpers/http/mod.rs
src/helpers/http/network.rs
src/helpers/http/prss_exchange_protocol.rs
src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/basics/mul/sparse.rs
src/protocol/boolean/bitwise_equal.rs
src/protocol/boolean/bitwise_less_than_prime.rs
src/protocol/context/mod.rs
src/protocol/sort/apply_sort/mod.rs
src/protocol/sort/apply_sort/shuffle.rs
src/tests/infra.rs
src/tests/mod.rs
src/tests/protocol.rs

I finally found the bug that was blocking shuttle tests. The issue outlined in #256 was fixed in
#363 but there was another bug inside the concurrency test itself. This change fixes it and enables concurrency testing as part of PR workflow approval.
It also adds a test for semi-honest IPA but given that it is incredibly slow, it only runs it for 2 iterations. Once we improve the IPA latency, number of iterations can be increased.

Enable concurrency testing

---

src/helpers/buffers/fsv.rs
src/helpers/buffers/mod.rs
src/helpers/buffers/send.rs
src/helpers/messaging.rs

This makes the send buffer take an absolute index, so that it can be the place we track that value.
I was going to take a look at the backpressure thing we talked about earlier, but I realized that it will need some more significant restructuring of the gateway code.  This was the groundwork I was laying, with a goal of making the `end` field on the FSV into an `AtomicUsize` that could be shared with other threads.
I did manage to get a test failure out of this where we overran the buffer, so this general line of investigation is definitely needed.
I'll follow up with a write-up on a channel-per-step design, then call it a day.

Start with some refactoring

---

src/protocol/attribution/credit_capping.rs

I am trying to eliminate the use of Tokio API in places we can use something else - tokio is a problem for CF workers environment

Minor: replace tokio::try_join with futures_util::try_join3

---

src/helpers/http/mod.rs
src/protocol/attribution/credit_capping.rs
src/protocol/basics/check_zero.rs

Apologies, missed more calls to `tokio::try_join!` :(
Verified that after this change there are no more calls to it
```bash
grep -r "tokio::try_join" . --include \*.rs | wc -l
0
```

Eliminate more calls to tokio::try_join!

---

src/bits/bit_array.rs
src/bits/mod.rs

Similar to `Field`, create a macro to generate BitArray structs with a specified bit length. Added `BitArray40` for the match key.
`BitArray64` is intact which we could use for other report fields i.e. breakdown key, but I suppose we'll use a lot shorter bit-length struct for that.

Create a macro to generate BitArray variations

---

src/protocol/sort/multi_bit_permutation.rs

tl;dr
Sorting 1000 rows:
= Old version =
(3-bit multi-sort) Total records sent: 1,950,000
(4-bit multi-sort) Total records sent: 3,129,000
= New version =
(3-bit multi-sort) Total records sent: 1,194,000
(4-bit multi-sort) Total records sent: 1,353,000
= Summary =
(3-bit multi-sort) 
- 756,000 fewer records sent
- 38.8% reduction
(4-bit multi-sort)
- 1,776,000 fewer records sent
- 56.7% reduction
For a 3-bit multi-bit-sort, here is what you do for each row:
- check if it's a bitwise representation of zero
- check if it's a bitwise representation of one
- check if it's a bitwise representation of two
- check if it's a bitwise representation of three
- check if it's a bitwise representation of four
- check if it's a bitwise representation of five
- check if it's a bitwise representation of …

More efficient multi-bit permutation generation

---

src/ff/field.rs
src/ff/prime_field.rs
src/helpers/buffers/fsv.rs
src/helpers/buffers/mod.rs
src/helpers/buffers/ordering_mpsc.rs
src/helpers/error.rs
src/helpers/http/prss_exchange_protocol.rs
src/helpers/messaging.rs

This creates a channel that accepts inputs in any order, then reorders them, using a buffer.  It only accepts each item once (panicking if a duplicate is sent) and it will block (asynchronously) if the value doesn't currently fit in the buffer.
Hopefully, this will be useful for our sending side.  We'll need a store of these and a way to hook them up to the connection.

Ordering MPSC

---

src/protocol/basics/mul/sparse.rs
src/protocol/basics/reshare.rs
src/protocol/basics/reveal.rs
src/protocol/boolean/generate_random_bits/malicious.rs
src/protocol/context/malicious.rs
src/protocol/context/mod.rs
src/protocol/malicious.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/mod.rs
src/test_fixture/sharing.rs
src/test_fixture/world.rs

Split this off from #360.
The purpose of these changes is to allow managing total_records on the upgrade_ctx without exposing a
set_total_upgrades function on MaliciousContext.
This ended up being a bit more involved than I thought it would be originally. I could pretty easily change this to get rid of set_total_upgrades without the UpgradeContext stuff, by adding an upgrade_vector function on ContextInner and narrowing the IntoMalicious impl for IntoIter to be specific to vectors.
I do think it's possible we'll want UpgradeContext as an entity, either as part of the changes to have contexts own open channels, or as part of the changes to make context cloning more efficient (#380).

rework upgrades for malicious protocol

---

Cargo.toml

We're not quite ready to eliminate them, there are some missing features (channel backpressure) that we need to implement before we can ignore them in release builds.
In the meantime, it is better to give some clues why benchmark is stalled/failed even at the cost of adding more branches

Enable debug assertions for benchmarks

---

src/protocol/basics/sum_of_product/malicious.rs
src/protocol/basics/sum_of_product/mod.rs
src/protocol/basics/sum_of_product/semi_honest.rs
src/protocol/sort/multi_bit_permutation.rs

As it turns out, the only time we ever compute the dot-product of two vectors, we independently have them in memory as two vectors. So it's better to just use them as-is, rather than creating a new vector of pairs of them.

Reverting #379

---

src/bits/bit_array.rs
src/bits/mod.rs

The original implementation of `Ord` for `bitvec::BitArray` compares two arrays from LSB, and at the first index where the arrays differ, the array with the high bit is greater.
For our use case, however, we want to compare two arrays by their integer values represented by the bits. In other words, if `a < b` is true, then `BitArrayN::try_from(a).unwrap() < BitArrayN::try_from(b).unwrap()` must also be true.

Implement `Ord` for BitArray types

---

Cargo.toml
src/bits/bit_array.rs
src/bits/mod.rs
src/ff/field.rs
src/ff/prime_field.rs
src/helpers/buffers/ordering_mpsc.rs
src/helpers/http/prss_exchange_protocol.rs
src/helpers/messaging.rs
src/helpers/mod.rs
src/secret_sharing/replicated/semi_honest/xor_share.rs

`serialize`/`deserialize` now work with fixed-size arrays. Unfortunately it does not eliminate all the runtime checks because in some places I had to use `GenericArray::from_slice`.
The benefit of this approach is that `Serialize` implementors do not need to check the size of the buffer, it is guaranteed to be set correctly.
this is still rough (I want to fix import and add some doc tests) but should demonstrate the idea.

Experimental `Serialize` trait backed by GenericArray

---

benches/oneshot/sort.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/ipa/mod.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/mod.rs
src/protocol/sort/apply_sort/mod.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/generate_permutation_opt.rs
src/protocol/sort/multi_bit_permutation.rs

Now, convert_all_bits returns vector of 2D vectors where each 2D vector is of size [ record_count ; num_multi_bits].
This helps in code clarity and is also required for malicious sort to do upgrade

Refactor of sort to take multi bits per record

---

.github/workflows/extra.yml

An additional workflow can run in parallel.  This increases overall work, but it might allow us to reduce the overall time to getting a positive answer.

Split out some of the longer-running tasks

---

.github/workflows/audit-check.yml
.github/workflows/audit-daily.yml
.github/workflows/audit.yml

It does not seem to work. I agree that we need to get rid of `actions-rs` but for now want to unblock main
https://github.com/akoshelev/raw-ipa/actions/runs/4067659251/jobs/7005327980
```bash
Run rustup toolchain install stable --component cargo-audit --profile minimal --no-self-update
rustup toolchain install stable --component cargo-audit --profile minimal --no-self-update
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
CARGO_TERM_COLOR: always
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
warning: Signature verification failed for 'https://static.rust-lang.org/dist/channel-rust-stable.toml'
info: latest update on 2023-01-26, rust version 1.67.0 (fc594f156 2023-01-24)
error: component 'cargo-audit' for target 'x86_64-unknown-linux-gnu' is …
```

Revert cargo audit change

---

src/protocol/boolean/bitwise_equal.rs

Similar to other bitwise protocols, this is a specialized protocol to check an equality of a bitwise share with a constant value. 
I plan to use this in a modified aggregation protocol where we compare breakdown keys rather than sorting by breakdown keys to sum up credits.

Bitwise equal constant

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs

It bothered me that we were initializing a Vec with length num_records with all clones of ONE. Then we never even used them... just overwrote them.
It also bothered me that the functions to calculate "b" and "stop_bit" made it harder to see what was going on. Just inlining the first iteration allowed me to simplify the loop and make everything simpler.

Simplify logic in aggregation

---

src/protocol/sort/compose.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/generate_permutation_opt.rs
src/protocol/sort/secureapplyinv.rs

Our code asserts that input_len == input_permutation.len() in apply/applyinv so there is no reason to have this argument as it is implied to be equal to input_permutation.len()

Remove input_len argument from shuffle_and_reveal_permutation

---

.github/workflows/check.yml
Cargo.toml
pre-commit
src/cli/mod.rs
src/cli/playbook/ipa.rs
src/cli/playbook/multiply.rs
src/helpers/mod.rs
src/helpers/transport/bytearrstream/aligned.rs
src/helpers/transport/bytearrstream/mod.rs
src/test_fixture/net.rs

After merging https://github.com/private-attribution/ipa/pull/464, oneshot IPA benchmark stopped compiling w/o
default features enabled. This commit fixes it by gating web-app
features behind `web-app` feature flag.
One place where it was particularly problematic was `ByteArrStream`
with a strong dependency on Hyper. I had to replace it with `Bytes`.

Make oneshot IPA compile again

---

pre-commit

When `git commit` is executed to finalize a merge process, MERGE_* files in .git/ are silently removed by `git stash push` in `pre-commit` script. This results in merge's `git commit` to fail, and one needs to restart the merging process from the beginning.

Save MERGE_* in pre-commit execution

---

src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/input.rs
src/protocol/context/malicious.rs

to avoid exposing `PhantomData` marker

Add constructor to CappedCreditsWIthAggregationBit struct

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/or.rs
src/protocol/ipa/mod.rs

One common ads use-case is to just *count* conversions. In this case, the "trigger value" is irrelevant. Every conversion counts the same, just one.
Furthermore, a common use-case is to *count distinct* users. Another way of saying this, is that each user can at most contribute a value of *one* to the output. 
In this special case, we can completely avoid bit-decomposition, and indeed we can avoid large chunks of the IPA protocol entirely. As this is not a rare use-case, it seems worthwhile to specialise this, so that we can run a much faster, more communication efficient algorithm.
Testing out on 1000 rows, "Records Sent" drops from 2,286,120 to 1,652,889 - a 27.7% drop in total communication.
Looking at the breakdown by stage:
- Accumulate drops from 77,796 to 2,997 (now it's just ONE …

Adding specialized functionality for when the per-user cap is one

---

src/protocol/attribution/credit_capping.rs
src/protocol/ipa/mod.rs

Extremely minor performance improvement.
In the PER_USER_CAP = 1 variant of the code:
...we checking if we need to filter out a given row.
...we do that by checking if the _following_ rows contain at least one contribution from the same user.
So that means nobody was ever reading the very *first* row.
This PR just avoids computing this value which was never read.

Minor optimization. Skip one row.

---

src/protocol/ipa/mod.rs

The "random" IPA test did not actually validate that the output was correct.
This PR creates a single "random" IPA test, which uses a seeded random number generator and logs the seed. That way, if it ever fails, we can re-test the seed that led to the failure.
Since the logic differs (significantly) if the PER_USER_CAP is 1 or another number, the same input is tested twice, first with a PER_USER_CAP of 1, then with a PER_USER_CAP of 3.
The expected output is computed in a straightforward way that's easy to verify is correct.

Making the random data test actually check outputs

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/ipa/mod.rs

The aggregation protocols accumulate values using a binary-tree style prefix-sum. The current code computes an intermediate `b` bit and multiply it by `credit` to determine whether a value should be accumulated in each iteration.
How we currently compute the `b` bit is by `sibling_helper_bit * current_stop_bit`. Since the initial `stop_bit` is computed by `sibling_helper_bit * sibling_is_trigger_bit`, we can eliminate `b` and just compute `current_stop_bit * sibling_value`.
Since call sites do not need helper_bits after calling `do_the_binary_tree_thing()`, I changed helper_bits to move. We also don't need to handle a special case for depth 0 and not need to create new vectors for credits, I changed credits to mutable borrow.
This change reduces 1 mult from per depth * N rows * 3 …

Remove the intermediate `b` bit

---

src/protocol/attribution/mod.rs
src/protocol/ipa/mod.rs

On the last iteration, there is no need to update the "stop bits" because they won't be read in the last iteration. We can skip this and save on communication bandwidth!

Skipping the computation of 'stop bits' on the last iteration

---

src/protocol/attribution/mod.rs

Same as #487 + #490. The baseline result doesn't change because it only has 5 events, but the improvement is still 1 less mult from O(N log N) logic.

Remove `b` bit from `prefix_or_binary_tree_style`

---

src/protocol/ipa/mod.rs

Credit capping executes the prefix-or function on each row log N times. I was working on an optimization to:
* Reduce 1 mult per iteration from N log N loop
* Add N mults per function call
The baseline test's result was an increase in the communication because the loop executed only once. As the `N` increases, however, the performance gain is obvious.
This PR adds 4 more rows, just enough to execute the said loop few more times, to be able to see the optimization results better. As the test is executed in parallel, it doesn't change the overall test execution time.

Add more events to the baseline test

---

src/protocol/attribution/mod.rs
src/protocol/ipa/mod.rs

I found another small optimization!
The very first iteration of PREFIX-OR, we basically update the "credit" for each line to reflect: "Is either _this_ row a 1, or is the _following_ row a 1 (from the same match key)".
Thinking about this a bit, I realized it is *impossible* (in the first iteration) to both have `uncapped_credits[i] ==1` AND `uncapped_credits[i+1] == 1`. 
The reason this is impossible is because of how basic attribution is in the "cap = 1" case. 
The only way to have `uncapped_credits[i] == 1` is to have a source event, followed by a trigger event from the same person. If you had two adjacent rows that both met this condition, that would imply that is_trigger_event[i+1] is simultaneously both a source and trigger event.
Put another way, two consecutive source-events …

Optimization: add to compute OR

---

Cargo.toml
src/helpers/mod.rs
src/helpers/transport/channelled_transport.rs
src/helpers/transport/mod.rs
src/helpers/transport/query.rs
src/lib.rs
src/protocol/mod.rs
src/test_fixture/transport/channeled_transport.rs
src/test_fixture/transport/mod.rs

Some things are still looking clunky, but I am not sure if there is a better way to deal with it. 
I tested major use cases (send/receive and receive query). As we discussed with @martinthomson the first iteration would be to agree on the transport API and build new infra in parallel with the existing one

In memory transport with channels

---

src/protocol/attribution/mod.rs
src/protocol/ipa/mod.rs

In #487, I changed how we compute the prefix-sum. Determining whether we should accumulate the `sibling_value` only depends on the `current_stop_bit`. That means we skip the bottom stop bits at `stop_bits[(num_rows - step_size + 1)..]`, which allows us to reduce 1 mult from each depth = log N mult reduction.

Remove the last stop_bit computation from each binary-tree depth

---

src/protocol/attribution/mod.rs

Missed to fix `set_total_records` in #495.

Correct record count for one less stop_bit mult

---

.github/workflows/check.yml
Cargo.toml

It is [disabled](https://doc.rust-lang.org/cargo/reference/profiles.html#incremental) by default and it should help shortening the iteration cycle on benchmarks

Enable incremental compilation for release builds

---

src/helpers/buffers/ordering_mpsc.rs

deriving clone for structs with internal Arc still does not work properly :(

Proper Clone for OrderingMpscSender

---

src/protocol/attribution/aggregate_credit.rs
src/protocol/ipa/mod.rs
src/protocol/sort/mod.rs
src/protocol/sort/multi_bit_permutation.rs

When there are very few breakdown keys (i.e. less than 32) it's less communication to just check each breakdown key for equality for every possible breakdown key. Sorting is better when there are a large number of breakdowns.
I did an analysis, plotting the total communication for both approaches. Results: https://docs.google.com/spreadsheets/d/1Nix-mr6VBpGFOnKIwIvniAV3KO5vhk3ydSwxcfh2-OM/edit?usp=sharing

Optimizing aggregation for small breakdown key counts

---

src/protocol/boolean/add_constant.rs
src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/mod.rs
src/protocol/ipa/mod.rs

We just throw these out, so remove 'em.  The function now operates modulo 2^l, which is all we use.  We can't do the same for the earlier addition as we need to know about the overflow.
Savings are modest.  So 3 multiplications per event. 27 records in semi-honest; 54 in malicious for our 9 event test.
I also renamed both functions.  The old names annoyed me, because context provided a lot of information that was again repeated in the name.  The new names are shorter.  We should remove "bitwise" from other "boolean" functions, because bitwise is implied in most cases.

Remove trailing bits from the bit decomposition protocol

---

src/helpers/buffers/mod.rs
src/helpers/buffers/ordering_mpsc.rs
src/helpers/mod.rs
src/helpers/transport/channelled_transport.rs
src/test_fixture/transport/channeled_transport.rs

see commit messages. Basically this PR does two things
* Make `OrderingMpscReceiver` implement a stream
* Get rid of one associated type on transport and make `send` method to take any stream provided by the caller.

Build integration between new transport and OrderingMpsc 

---

Cargo.toml

This will make the running of IPA quite a bit faster, but the compiling quite a bit slower.  I've opted for "thin", which isn't the full LTO, but it should still help a fair bit with performance.
Run time is hard to measure (on my machine, it varies a LOT), but the slowest LTO run is faster than the fastest non-LTO.
Closes #510.

Enable LTO on release builds

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/apply_attribution_window.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/basics/check_zero.rs
src/protocol/basics/mul/malicious.rs
src/protocol/basics/mul/mod.rs
src/protocol/basics/mul/semi_honest.rs
src/protocol/basics/mul/sparse.rs
src/protocol/boolean/add_constant.rs
src/protocol/boolean/bitwise_less_than_prime.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/or.rs
src/protocol/boolean/xor.rs
src/protocol/context/malicious.rs
src/protocol/malicious.rs
src/protocol/sort/bit_permutation.rs
src/protocol/sort/mod.rs
src/query/executor.rs
src/test_fixture/circuit.rs

I think this is the last cleanup from https://github.com/private-attribution/ipa/pull/488#discussion_r1115059175. Reshare and reveal were done previously. This PR does multiply. The remaining things in `protocol::basics` are:
* `sum_of_products` is still an associated function, but it's less clear the right way to make that a method. If it's implemented as a method on slices, then various things that currently require `S: BasicProtocols` instead need to require `[S]: SumOfProducts`, which somewhat offsets any ergonomic benefit of being able to call as a method rather than an associated function. Sum-of-products is only used a couple places anyways.
* `share_known_value` is an associated function, but that makes sense because it's a constructor of sorts, not an operation on a value.
* …

make `multiply` a method

---

scripts/test-coverage.sh

This is a little bit of an indulgence for me, but I find that generating coverage reports was a little bit tedious to setup.  This script can be pointed at a file to generate a coverage report.  It's a little elaborate, but it automates the process completely, so it might be useful.
I haven't enabled cargo options (like `-F`) but those can be added.

A test coverage script

---

benches/oneshot/ipa.rs
src/helpers/transport/query.rs
src/net/http_serde.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/malicious.rs
src/protocol/attribution/mod.rs
src/protocol/attribution/semi_honest.rs
src/protocol/ipa/mod.rs
src/tests/protocol.rs

Wraps the three attribution sub-protocols (accumulate, cap, aggregate) into one protocol, making it more friendly for callers that they do not need to know the details and the order of the sub-protocols.
It also lays the foundation of calling `apply_attribution_window` protocol. This wrapper protocol can determine whether to apply the attribution window logic depending on a parameter, and sub-protocols' behaviors will change accordingly. All these details will be contained in this super protocol.

Attribution wrapper protocol

---

src/protocol/basics/reshare.rs
src/protocol/basics/reveal.rs
src/protocol/context/malicious.rs
src/protocol/context/mod.rs
src/protocol/mod.rs
src/protocol/sort/apply_sort/shuffle.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/shuffle.rs
src/secret_sharing/replicated/malicious/additive_share.rs

When I originally added this it was only used for malicious upgrades, but that has changed, so this PR moves it out of the malicious context module and into `protocol` (which is also where `RecordId` lives).

move `RecordBinding` to a more appropriate home

---

src/helpers/messaging.rs
src/hpke/mod.rs
src/net/server/handlers/query/results.rs
src/protocol/basics/mul/semi_honest.rs
src/protocol/basics/mul/sparse.rs
src/protocol/basics/reshare.rs
src/protocol/basics/share_known_value.rs
src/protocol/basics/sum_of_product/malicious.rs
src/protocol/basics/sum_of_product/semi_honest.rs
src/protocol/boolean/generate_random_bits/mod.rs
src/protocol/context/mod.rs
src/protocol/malicious.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/prss/crypto.rs
src/protocol/sort/apply_sort/shuffle.rs
src/secret_sharing/into_shares.rs
src/secret_sharing/replicated/malicious/additive_share.rs
src/secret_sharing/replicated/mod.rs
src/secret_sharing/replicated/semi_honest/additive_share.rs
src/secret_sharing/replicated/semi_honest/xor_share.rs
src/secret_sharing/scheme.rs
src/test_fixture/sharing.rs
src/tests/infra.rs

Implement `Reshare` trait for semi-honest and malicious `XorShare`. For now, the malicious XOR reshare implementation is the same as semi-honest.

Impl Reshare for XorShare

---

src/ff/field.rs
src/ff/galois_field.rs
src/ff/mod.rs
src/secret_sharing/into_shares.rs
src/secret_sharing/replicated/semi_honest/xor_share.rs
src/test_fixture/sharing.rs

This leaves GF with just arithmetic operations which will let us treat GF exactly the same as prime fields.
Next up is removing bitwise operations from `XorShare`, and merge `AdditiveShare` and `XorShare`.

Remove bitwise ops from Galois Field

---

.github/workflows/check.yml
pre-commit

It leads to quite significant improvement in runtime. In debug mode it currently takes ~40 seconds on my machine to run them all. In release mode, it only takes 3 seconds
before
```bash
test result: ok. 24 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 41.59s
```
after
```bash
test result: ok. 24 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.49s
```

Run concurrency tests in release mode

---

src/helpers/buffers/fsv.rs

This struct will be deprecated soon anyway

Suppress clippy unused warning on FSV

---

src/ff/mod.rs
src/secret_sharing/replicated/semi_honest/xor_share.rs
src/secret_sharing/scheme.rs

We'll need to merge the two to remove dup code, but implementing `Reshare` for `AdditiveShare<SharedValue>` and `AdditiveShare<GaloisField>` will require further refactoring (impl signature will be the same and will conflict). Since we don't know what `Reshare` might look like for Galois Field shares, I'm differing the merge to after the `Reshare` implementation.

XorShare as linear secret sharing

---

src/ff/field.rs
src/ff/mod.rs
src/ff/prime_field.rs
src/protocol/attribution/apply_attribution_window.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/malicious.rs
src/protocol/attribution/semi_honest.rs
src/protocol/basics/check_zero.rs
src/protocol/boolean/add_constant.rs
src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/bitwise_less_than_prime.rs
src/protocol/boolean/comparison.rs
src/protocol/boolean/generate_random_bits/malicious.rs
src/protocol/boolean/generate_random_bits/mod.rs
src/protocol/boolean/generate_random_bits/semi_honest.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/random_bits_generator.rs
src/protocol/boolean/solved_bits.rs
src/protocol/ipa/mod.rs
src/query/executor.rs
src/test_fixture/sharing.rs

This extracts `PrimeField` piece from @andyleiserson's PR https://github.com/private-attribution/ipa/pull/545.
Current hierarchy of secret shared value types are:
```SharedValue -> Field```
where `Field` was really prime fields defined in prime_field.rs. Now that we have Galois Fields, this diff creates a new trait `PrimeField` that all current prime fields (i.e., Fp32BitPrime) implement. This allows us to Galois Field to be the sub-type of `Field`.
```
SharedValue -> Field -> PrimeField
\-> GaloisField
```

PrimeField trait

---

src/ff/field.rs
src/ff/galois_field.rs
src/ff/prime_field.rs
src/secret_sharing/mod.rs

We want to create a new type `Gf2` as in #552, which is basically a field of 2 elements {0, 1}. We use the `BitArr!` to define an internal struct to store the bits for `GaloisFields` like this:
`type U8_1 = BitArr!(for 8, in u8, Lsb0);`
For Gf2, it's tempting to do something like `type U8_0 = BitArr!(for 1, in u8, Lsb0);`, but this macro just generates an array long enough to fit the number of bits (`for 1`) in the underlying primitive type (`in u8`), so both `U8_1` and `U8_0` here are `[u8; 1]`.
This is a problem because we want to implement `Block` for these storage types, but type aliases are just short names for the given type; not new types.
Specifying a trait for type aliases is in [nightly build](https://rust-lang.github.io/impl-trait-initiative/explainer/tait.html), but until that …

Remove VALID_BIT_LENGTH from Block trait

---

src/helpers/mod.rs
src/protocol/attribution/apply_attribution_window.rs
src/protocol/attribution/credit_capping.rs
src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/comparison.rs
src/protocol/boolean/random_bits_generator.rs

This is just a prelude to a larger refactoring after which `RandomBitsGenerator` will be able to efficiently use the infrastructure buffering capabilities.
Currently, it does not change anything for the callers, but the idea is that `fallback_generator` will opt out from using buffering and will be continuously sending data as it goes in. With the right field size, the probability of `RandomBitsGenerator` calling it more than once is negligible, calling it once for `Fp32BitPrime` is $10^-9$

Use two channels inside random bits generator 

---

src/protocol/attribution/malicious.rs
src/protocol/attribution/mod.rs
src/protocol/attribution/semi_honest.rs
src/protocol/boolean/bitwise_equal.rs
src/protocol/boolean/mod.rs
src/protocol/context/malicious.rs
src/protocol/ipa/mod.rs

This PR is stacked on top of #552 - and makes use of that new functionality to save communication overhead in IPA.
This uses a *binary field* for the bits of the match key, and while in malicious mode, the `rx` component is still a 4-byte value, the `x` part is just a single bit. For the moment, this results in 1-byte of communication - but we can address that later.

WIP: using field extension to drop IPA communications

---

benches/oneshot/ipa.rs
benches/oneshot/sort.rs
src/helpers/gateway/mod.rs
src/protocol/ipa/mod.rs
src/test_fixture/ipa.rs
src/test_fixture/world.rs
src/tests/infra.rs

As Martin predicted, send capacity was destined to be broken because of the bad config name. So we ended up with send buffer capacity that is 4 times smaller than we wanted.
I thought it might be a good idea to align buffer capacity with the field size as it should work for the majority of the channels. That required making sure IPA uses the same field, so I had to plug in a generic argument to it

Fix send gateway buffer capacity

---

src/helpers/gateway/send.rs
src/protocol/context/mod.rs
src/protocol/ipa/mod.rs
src/telemetry/mod.rs
src/telemetry/step_stats.rs

A companion to `records.sent` that measures the total communication in bytes between helpers. With recent developments in IPA, the total number of records may stay the same, but size of messages sent is reduced. `records.sent` does not capture it, so we would rely on `bytes.sent` to check those improvements.

Add bytes.sent metric to count bytes sent between helpers

---

benches/oneshot/ipa.rs
benches/oneshot/sort.rs
src/helpers/gateway/mod.rs
src/helpers/gateway/send.rs
src/protocol/ipa/mod.rs
src/test_fixture/world.rs
src/tests/infra.rs

Recent [change](https://github.com/private-attribution/ipa/pull/566) made it possible for IPA to send different field values, so send buffer capacity must be adjusted to that. Setting up raw bytes capacity no longer works and here is why:
assume we set send buffer capacity to 1024 bytes. That would mean that it could keep up to 256 `Fp32BitPrime` values or 1024 `Gf2` values. Given that we are moving towards defining a sliding window of records we process in parallel (see @martinthomson's efforts to implement [`seq_try_join_all`](https://github.com/private-attribution/ipa/commit/bfc7a09b46bfb4f3de18693882192424d83addff)) we no longer can rely on universal send buffer capacity.
The proposed fix includes defining send buffer capacity in terms of items to process and adjusting byte capacity …

Revert gateway send buffer capacity back from bytes to units

---

src/protocol/context/malicious.rs
src/protocol/ipa/mod.rs
src/query/executor.rs
src/test_fixture/input/mod.rs
src/test_fixture/input/sharing.rs
src/test_fixture/ipa.rs
src/tests/protocol.rs

Add a new `AdditiveShare<F>` field for timestamps to IPA e2e protocol input.
semi-honest cap3: 15453 -> 15507
malicious cap3: 38400 -> 38535
semi-honest cap1: 11784 -> 11838
malicious cap1: 29046 -> 29181
We can save the cost by not applying permutation if the attribution window parameter passed to IPA is 0 (disable attribution window). But that requires different input structures and many if-else in several code paths. If we expect reasonable amount of queries to disable applying attribution window, then we should consider doing so. However, my guess is that almost all queries would require attribution window computations.

Pass timestamps to IPA

---

.clippy.toml
src/helpers/buffers/ordering_mpsc.rs
src/helpers/buffers/ordering_sender.rs
src/helpers/buffers/unordered_receiver.rs
src/lib.rs
src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/apply_attribution_window.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/basics/mul/semi_honest.rs
src/protocol/basics/reshare.rs
src/protocol/basics/reveal.rs
src/protocol/boolean/random_bits_generator.rs
src/protocol/boolean/solved_bits.rs
src/protocol/context/malicious.rs
src/protocol/context/mod.rs
src/protocol/malicious.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/sort/bit_permutation.rs
src/protocol/sort/multi_bit_permutation.rs
src/seq_join.rs
src/tests/infra.rs

Allow array joins in tests
Follow up on #585 - relax this requirement to avoid array joins in prod code only
Also this change proposes to rename `join` to `try_join` - see commit message for details why.
* removed lint suppression in prod code and verified that clippy is angry about it
```bash
cargo clippy
Checking num-traits v0.2.15
Checking byteorder v1.4.3
Checking curve25519-dalek v3.2.0
Checking ordered-float v2.10.0
Checking x25519-dalek v2.0.0-pre.1
Checking metrics-util v0.14.0
Checking hpke v0.10.0
Checking metrics-tracing-context v0.12.0
Checking ipa v0.1.0 (/Users/koshelev/workspace/raw-ipa)
warning: use of a disallowed method `futures::future::join_all`
--> src/secret_sharing/replicated/malicious/additive_share.rs:294:22
|
294 |           let result = join_all(
| …
```

Allow disallowed methods in tests

---

Cargo.toml
benches/oneshot/ipa.rs
src/bin/helper.rs

This cut about 25% off the running time of a test, but it only works reliably on x86_64.

Switch to jemalloc allocator

---

src/protocol/attribution/credit_capping.rs

We're still far too exposed to memory allocations, but this should fix the spike we're seeing about 2/3 - 3/4 through a run.
This is safe because the comparison ends with sequential operations, even if earlier operations (RBG) are not.
IPA for 50000 records took 568.861833105s compared to 843.574458344s without this change (same baseline; not rebased).

Fix the memory spike

---

src/hpke/info.rs
src/hpke/mod.rs

Implementing https://github.com/private-attribution/ipa/issues/593  to add an event type (is_trigger) to the associated data/Info.  Right now have it with `pub type`  and not an `enum`

add event type (is_trigger bit) to Info

---

scripts/benchmark_ipa.sh

===============================
Command to run
===============================
scripts/benchmark_ipa.sh QUERY_SIZE
This would run oneshot_ipa with QUERY_SIZE and output the benchmark results
===============================
Sample output (on the terminal)
===============================
Step,Bytes sent,Records Sent
Verify,153600,38400
Sort,716040,197010
Attribution,85419,30042
Capping,436256,109064
Aggregation,64800,16200
Others,148956,37239
Total,1605071,427955

Script to generate a report with benchmarking results

---

src/helpers/gateway/mod.rs
src/helpers/gateway/receive.rs
src/hpke/mod.rs
src/protocol/basics/sum_of_product/semi_honest.rs
src/protocol/boolean/add_constant.rs
src/protocol/ipa/mod.rs
src/protocol/mod.rs
src/protocol/prss/mod.rs
src/protocol/sort/apply_sort/shuffle.rs

Fix new clippy warnings - it is pretty cool that clippy can now detect unused type parameter and constants

Upgrade to Rust 1.69

---

Cargo.toml
src/bin/test_mpc.rs
src/cli/playbook/input.rs
src/cli/playbook/ipa.rs
src/cli/playbook/mod.rs
src/cli/playbook/multiply.rs

It compiles and runs, but obviously needs HTTP servers to stand
```bash
cargo run --bin test_mpc --features=cli --features=web-app -- --input-type fp31 multiply
Finished dev [unoptimized + debuginfo] target(s) in 0.55s
Running `target/debug/test_mpc --input-type fp31 multiply`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HyperPassthrough(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', src/bin/test_mpc.rs:100:76
```

Bring back test_mpc CLI

---

src/protocol/context/mod.rs
src/protocol/context/prss.rs
src/protocol/ipa/mod.rs
src/protocol/prss/mod.rs
src/protocol/sort/shuffle.rs
src/test_fixture/mod.rs
src/test_fixture/world.rs

I realized that we no longer print/emit sequential randomness metrics
```bash
RUST_LOG=ipa=DEBUG cargo bench --bench oneshot_ipa --no-default-features --features="enable-benches debug-trace" -- -n 10 | cut -d',' -f5 | sort -nr | head -n10
Sequential PRSS
0
0
0
0
0
0
0
0
0
```
after some debugging, it seems that shuffle now calls `next_u32` method instead of `next_u64`. I think it happened because we switched from `usize` to `u32` in `get_two_of_three_random_permutations`. Static dispatch does not call instrumented `next_u64` and here we are.
Unit tests did not catch that because they use a different protocol that never hit that path. Now it is changed to generate `u32` values too.
It also feels bad that we don't test PRSS metrics for IPA, so I changed the `communication_baseline` test. …

Fix sequential prss metrics in IPA

---

Cargo.toml
benches/README.md
benches/oneshot/ipa.rs
src/protocol/context/prss.rs
src/telemetry/mod.rs
src/test_fixture/metrics.rs

[DHAT](https://docs.rs/dhat/latest/dhat/)
This PR enables DHAT for memory profiling. Only `oneshot/ipa` is supported for now. To run the profiling, execute the following command.
```
cargo bench --bench oneshot_ipa --profile=bench-dhat --features="dhat-heap enable-benches" --no-default-features -- -n 100
```
For more detail, refer to README.md included in this PR.

DHAT for memory profiling

---

src/helpers/transport/bytearrstream/aligned.rs

They are not supposed to be executed under Shuttle's scheduler.

Exclude bytearrstream tests from Shuttle

---

.github/workflows/check.yml
.gitignore
Cargo.toml
pre-commit
src/bin/helper.rs
src/bin/test_mpc.rs
src/cli/keygen.rs
src/cli/mod.rs
src/cli/playbook/mod.rs
src/cli/test_setup.rs
src/cli/verbosity.rs
src/config.rs
src/net/client/mod.rs
src/net/mod.rs
src/net/server/mod.rs
src/net/test.rs
src/net/transport.rs
src/query/processor.rs
src/test_fixture/config.rs
tests/helper_networks.rs

Some possible points for discussion:
* This changes the default log level to info (#608).
* I have added `keygen` and `test-setup` commands as alternate functions of the `helper` binary. I like having utility commands embedded in the server binary since it means you always have the utilities anywhere you have the server. However, this does have the consequence that the utility-only dependencies `rcgen` and `time` become dependencies of `web-app`. If there is a preference to make each of the CLI functions a standalone binary (or to put the CLI utilities together in a `helper-tool` binary), I can do that.
* I add `cli` and `test-fixture` to the feature set for web tests because the new end-to-end test invokes `test_mpc`. I started to do the work to have test_mpc optionally print the results …

TLS server certificate configuration

---

benches/oneshot/ipa.rs
src/bin/test_mpc.rs
src/helpers/transport/query.rs
src/net/http_serde.rs
src/net/server/handlers/query/create.rs
src/net/server/mod.rs
src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/apply_attribution_window.rs
src/protocol/ipa/mod.rs
src/query/processor.rs
src/query/runner/ipa.rs
src/test_fixture/ipa.rs
src/tests/protocol.rs

Found this issue while working on some CLI tooling. Currently MPC just skips the attribution window logic if the window is set to be 0. IPA in the clear did not do it and I was observing different results running them one after another. 
It does seem better to use the type system to make this behavior more clear. As 0 truly does not make much sense as window value, `Option<NonZeroU32>>` is used instead.

Match the behavior of IPA in the clear and MPC IPA

---

src/telemetry/stats.rs

CLI tools (helper + test_mpc) print metrics collected during the run. However, for `test_mpc` it is often true that there are no metrics emited. This leads to empty table printed to the output.
```bash
+--------+-------------+-------+------------+
| metric | description | value | dimensions |
+===========================================+
+--------+-------------+-------+------------+
```
This commit changes that, making it conditional on number of records in that table.

Print metrics only if there are any

---

src/bin/helper.rs
src/bin/test_mpc.rs
src/cli/test_setup.rs
src/config.rs
src/net/client/mod.rs
src/net/server/mod.rs
src/net/test.rs
src/net/transport.rs
src/test_fixture/config.rs
tests/helper_networks.rs

Branch includes #637.
@akoshelev observed that `https` URLs in `network.toml` were honored even when running in HTTP mode. With this change, the URL scheme in the configuration is overridden with whatever is selected on the command line. To reduce confusion, I also changed `test-setup` to write URLs in the config with host and port only.
I also made HTTPS the default when running a helper (option is now `--disable-https` instead of `--https`), and in the default configuration for real-infra unit tests.

make https the default, but enable running in http mode with the https config

---

src/protocol/attribution/credit_capping.rs
src/seq_join.rs

I've started to look for places to apply this, and there are fewer than I'd have liked.  But this change was easy enough to execute.
Next step is to start changing the gap between protocol steps so that one produces a stream and the other consumes it.  Not as many options on that front as I had hoped, based on my first look, but we'll see.

Streaming: Make seq_join take a stream

---

.github/workflows/check.yml

We build the benchmarks twice for this job, but we don't have to.

Avoid a second build for benchmarks

---

src/exact.rs
src/lib.rs
src/seq_join.rs

If we're going to use streams, there will come a time where we need to be somewhat more definite about the length of the stream.  Our contexts need to know how many records are processed for a given step, so being able to interrogate a stream to determine its length will help a fair bit.
This change defines a new trait, modeled from `ExactSizeIterator` for streams and a stream wrapper that provides an implementation of that trait.  The idea is that when we get a stream from the network, we'll be able to explicitly mark the size of that stream so that protocol step implementations can just know how many records are being processed.

Add an exact-sized stream trait

---

Cargo.toml
src/protocol/step.rs

Let say we have this:
#[Step]
pub enum Step {
ModulusConversionForMatchKeys,
}
The proc macro expansion function called at the compile time will receive the `Step` token but it doesn't have attributes like its full module path. I believe that path resolution is done at build time and there's no way to interpret that in proc macro.
This change adds a feature that, when enabled, narrowed steps will be prefixed with their full module paths. This information is used in the proc macro to generate StepNarrow implementations for IPA steps.

Print the step's full path

---

src/hpke/info.rs
src/hpke/mod.rs

Based on https://github.com/patcg-individual-drafts/ipa/issues/57, there is an attack that a malicious Match Key Provider (MKP) can carry out by creating fake sites and using those sites' privacy budgets to measure events that happened on its own source or trigger site. Until we are able to find a good mitigation to this attack, we have decided to move forward with no match key provider in the IPA design. 
This PR removes mkp from being added to associated data in hpke.

Removing match key provider from HPKE for now

---

scripts/collect_steps.py

A python script to run `oneshot_ipa` benchmark for all combinations of IPA options to generate all the possible steps, sort them and print them out. The output will be used to codegen the optimized `Steps` implementation.
This script basically executes the following command:
`RUST_LOG=ipa=DEBUG cargo bench --bench oneshot_ipa --no-default-features --features="enable-benches debug-trace step-trace" -- --num-multi-bits 1 -n 10 -c $1 -w $2 -b $3 -m $4`
where options that affect IPA protocol paths are:
* `-c` PER_USER_CAP = [1, 3]
* `-w` ATTRIBUTION_WINDOW = [0, 86400]
* `-b` BREAKDOWN_KEYS = [1, 33]
* `-m` SECURITY_MODEL = ["malicious", "semi-honest"]
The output is not 100% complete because there are protocols that change the number of narrows based on the number of bits or rows that are …

Python script to generate (mostly) complete IPA steps

---

src/test_fixture/event_gen.rs

1. On main, run:
`cargo bench --bench oneshot_ipa --no-default-features --features="enable-benches" -- -b 1`
`thread 'tokio-runtime-worker' panicked at 'cannot sample empty range', /Users/taiki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rand-0.8.5/src/rng.rs:134:9`
bug from this [line](https://github.com/private-attribution/ipa/pull/647/files#diff-a2e596e6cd259bc063f0615516e2e11a06a41eacfbe1dcedf880d73b2a6cd21aR152).

Breakdown key index is 0-based

---

docker/.dockerignore
docker/helper.Dockerfile
scripts/helper-image.sh

It is not very capable right now, want to collect some early feedback. It does set up an image with helper binary and TLS config.
Addresses #644 
```bash
$ scripts/helper-image.sh --identity 1 --hostname localhost
1
[+] Building 181.3s (17/17) FINISHED
=> [internal] load build definition from helper.Dockerfile                                                                                                                                                              0.0s
=> => transferring dockerfile: 798B                                                                                                                                                                                     0.0s
=> [internal] load .dockerignore …
```

Add Dockerfile to create IPA helper image

---

docker/helper.Dockerfile

We need them to bootstrap helper service and decrypt match key shares.

Docker: generate HPKE keys along with TLS

---

docker/.dockerignore
scripts/helper-image.sh

Before this change, we had Docker transferring gigabytes (if both release and debug builds exist) of data inside the image and make no use of it. It was happening because docker [expects](https://docs.docker.com/engine/reference/builder/#dockerignore-file) `.dockerignore` file to be inside the root folder of the context.
In IPA folder structure, `.dockerignore` was put right next to the `.Dockerfile` so it wasn't picked up when building the image.
There does not seem to be an option to provide path to `.dockerignore` to Docker CLI, so I build the context manually

Reduce the size of Docker build context

---

in-market-test/helper-nodes/setup_instructions.md

Updating the instructions to add commands for copying the public keys to/from a docker image.

Helper setup instructions

---

.github/workflows/check.yml

If a PR includes only integration test changes, it does not trigger the workflow, see https://github.com/private-attribution/ipa/pull/666

Trigger CI actions on integration tests changes

---

Cargo.toml
src/error.rs
src/helpers/transport/in_memory/mod.rs
src/helpers/transport/in_memory/transport.rs
src/helpers/transport/stream.rs
src/lib.rs
src/net/transport.rs
src/query/completion.rs
src/query/executor.rs
src/query/mod.rs
src/query/processor.rs
src/query/runner/ipa.rs
src/query/runner/mod.rs
src/query/runner/test_multiply.rs
src/query/state.rs
src/test_fixture/app.rs

Make helpers capable of running more than one query
This change allows both in memory and HTTP implementations to run more than one query in sequence.
There were two things preventing it: `QueryProcessor` not properly cleaning up its state and transports keeping the stream
collections after query completion. The former was easy to fix, but I am not super happy with the fix for the latter.
There were a couple of options how to fix the transports:
* Generate a unique query id for each run (#615). We need this anyway, so this could be an incomplete fix.
Incomplete because one may consider keeping streams for completed query around forever as memleak.
* Teach `Transport` trait to be aware of query completion. That looked as too big of a fix and a violation of the design we have right now
* …

Make helpers capable of running more than one query

---

docker/helper.Dockerfile
in-market-test/helper-nodes/setup_instructions.md
src/bin/helper.rs
src/cli/clientconf.rs
src/cli/mod.rs
src/cli/paths.rs
src/cli/test_setup.rs
src/config.rs
src/helpers/mod.rs
tests/helper_networks.rs

In order to streamline our helper image bootstrap, we need a command to generate a valid `network.toml` from a set of public keys and public uris. The flow would be as follows:
* script generates 3 docker images, each with its own configuration (DNS name)
* script copies public configuration from each helper to each other helper
* script runs `docker run` to execute this command to generate `network.toml` on each image
after this, images will be fully ready to be copied to the nodes that will run helpers
```bash
cargo run --bin helper --no-default-features --features="cli web-app real-world-infra" -- confgen --keys-dir test_data --output-dir /tmp/ipaconfgen
```

Command to generate `network.toml`

---

scripts/ec2-instance-config.yaml

```bash
yum info docker
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Installed Packages
Name        : docker
Arch        : x86_64
Version     : 20.10.23
Release     : 1.amzn2.0.1
Size        : 163 M
Repo        : installed
From repo   : amzn2extra-docker
Summary     : Automates deployment of containerized applications
URL         : http://www.docker.com
License     : ASL 2.0 and MIT and BSD and MPLv2.0 and WTFPL
Description : Docker is an open-source engine that automates the deployment of any
: application as a lightweight, portable, self-sufficient container that will
: run virtually anywhere.
:
: Docker containers can encapsulate any payload, and will run consistently on
: and between virtually any server. The same container that a developer builds
: and tests …
```

Install docker on EC2 instances

---

src/query/executor.rs
src/query/processor.rs
src/query/runner/ipa.rs
src/query/runner/mod.rs
src/query/runner/test_multiply.rs

In particular, this makes there be only one copy of the code that processes the input reports for an IPA query.

Reduce duplicated code involved in running a query

---

src/net/server/mod.rs

See #685 for details. We certainly need more than 256 streams. Having an upper limit close to that number leaves us vulnerable to having this issue again in the future.
So I'd rather not limit it and rely on performance metrics if we start seeing impact of too many streams open.
I also don't see an easy way to test this, so tests are not included :(

Remove the limit on number of concurrent streams

---

Cargo.toml
src/net/server/mod.rs

It's been long since the last update and we need to pick up some bug fixes (particularly in Hyper)
Upgrading Axum is more involved, so it is not included

Upgrade dependencies

---

src/cli/verbosity.rs
src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/apply_attribution_window.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/context/validator.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/sort/apply_sort/mod.rs
src/protocol/sort/generate_permutation.rs
src/query/executor.rs
src/query/runner/ipa.rs

Using [`span_events`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.Layer.html#method.with_span_events) to log the durations
This is how malicious IPA run looks like 
```bash
2023-06-07T22:17:12.017603Z  INFO ipa::cli::verbosity: Logging setup at level info
2023-06-07T22:17:12.022709Z  INFO ipa::net::server: server listening on http://0.0.0.0:3000
2023-06-07T22:17:53.390055Z  INFO ipa_query: ipa::query::runner::ipa: new
2023-06-07T22:17:54.384306Z  INFO ipa_query:modulus_conversion{bits=40 parallel=3 step=protocol/malicious_protocol/mod_conv_match_key}: ipa::protocol::modulus_conversion::convert_shares: new
2023-06-07T22:17:56.001739Z  INFO ipa_query:modulus_conversion{bits=40 parallel=3 step=protocol/malicious_protocol/mod_conv_match_key}: …
```

Log duration of major IPA steps

---

src/test_fixture/event_gen.rs

Instead of generating events incrementally each second, this would now generate events at a gap of upto 60 secs.
This would ensure that we can test attribution window logic.
We can easily generate events in > 7day attribution window with 100k query size with this.

generate events to support attribution window

---

src/net/client/mod.rs

Tested it in the worst setup possible (US->AU->US helper configuration) on 5k input
Before this change
```
2023-06-09T23:10:06.630888Z  INFO ipa_query: ipa::query::runner::ipa: new
...
2023-06-09T23:13:54.409354Z  INFO ipa_query: ipa::query::runner::ipa: close time.busy=10.3s time.idle=217s
```
After this change
```
2023-06-10T00:00:20.559948Z  INFO ipa_query: ipa::query::runner::ipa: new
...
2023-06-10T00:02:20.118076Z  INFO ipa_query: ipa::query::runner::ipa: close time.busy=10.2s time.idle=109s
```

set TCP_NODELAY for helper-to-helper connection

---

src/protocol/prss/mod.rs

This diff updates `UsedSet`, a hash map that keeps track of used prss indexes, to use `Gate` as its keys. Previously, it used `String` which is a clone of static strings that are returned by `Step::as_ref()`. This causes a huge memory allocation even for the `Compact` gate where we could just use `u16` step IDs as keys.
Below is the DHAT memory profile showing the total memory consumption when we use `String` as the key. *20%* of the entire memory allocation (3.3GB for 1000 rows) comes from the hash map.
```
▼ PP 1/1 (16 children) {
Total:     17,768,783,497 bytes (100%, 12,380,886.86/s) in 146,289,044 blocks (100%, 101,930.9/s), avg size 121.46 bytes, avg lifetime 3,994,725.36 µs (0.28% of program duration)
At t-gmax: 330,879,053 bytes (100%) in 982,552 blocks (100%), avg size 336.75 …
```

Use Gate as used prss HashMap keys

---

benches/oneshot/ipa.rs
scripts/collect_steps.py
src/telemetry/stats.rs
src/telemetry/step_stats.rs

There are dynamic steps that are generated based on the number of input rows to IPA.
Since we are only executing IPA with 10 input rows, it only generates log2(10) (maybe a few more/less because of the optimizations) dynamic steps. We want to generate all possible steps for code generation without actually executing IPA with 1B rows.
This change also suppresses header lines not needed for step colleciton.

Generate dynamic steps

---

scripts/ec2-provision.sh

By default EC2 provisions ~9Gb partitions which is not enough for Rust toolchain and IPA deps. I was manually resizing it, but now that we need to provision more and more instances, it is better to set up volume size at the start.
Note that NVME-backed instances use the same convention name for root partition, but they are shown as `/dev/nvme0n1p1` in `df`
Here is how it looks now:
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         31G     0   31G   0% /dev
tmpfs            31G     0   31G   0% /dev/shm
tmpfs            31G  532K   31G   1% /run
tmpfs            31G     0   31G   0% /sys/fs/cgroup
/dev/nvme0n1p1  200G  6.5G  194G   4% /
tmpfs           6.2G     0  6.2G   0% /run/user/1000
```
before this change
```
df -h
Filesystem      Size  Used Avail Use% …
```

EC2: increase the size of root partition to 200Gb

---

src/net/client/mod.rs

Fix Rustdoc for `ClientIdentity::from_pks8`

---

src/query/processor.rs
src/query/state.rs

Currently if H1 failed to communicate with H2 or H3, it remembers the query forever. This change makes it forget about the query it failed to prepare. Addresses #701

Make new_query recover from communication errors

---

src/bin/ipa_bench/cmd.rs
src/bin/ipa_bench/gen_events.rs
src/bin/ipa_bench/sample.rs
src/error.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/input.rs
src/protocol/attribution/mod.rs
src/protocol/boolean/bitwise_less_than_prime.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/solved_bits.rs
src/protocol/context/mod.rs
src/protocol/context/upgrade.rs
src/protocol/ipa/mod.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/sort/compose.rs
src/protocol/sort/secureapplyinv.rs
src/test_fixture/input/sharing.rs
src/test_fixture/world.rs

@benjaminsavage, this might help.  I've added a couple of tweaks (see #724) above yours as well, because I'll be needing those.

Breakdown key simplification cleanups

---

docker/ci/helper.Dockerfile

This fixes #734.
We need to specify either `descriptive-gate` or `compact-gate` if `--no-default-features` is on. For CI, we want to use the compact gate.

Build docker CI image with compact-gate feature

---

Cargo.toml
src/bin/report_collector.rs
src/test_fixture/event_gen.rs
tests/helper_networks.rs

For synthetic test we need to be able to generate uncoordinated impressions and conversions on different machines. That requires sharing a seed for random generator, new argument that tells `EventGenerator` to skip source or trigger events and conversion probability. 
I tested it using the following script
```bash
cargo run --release --bin report_collector --features="clap cli test-fixture" -- gen-ipa-inputs -n 1000 --output-file /tmp/ipa-conversions.txt --max-breakdown-key 20 --report-filter trigger-only --seed 123
cargo run --release --bin report_collector --features="clap cli test-fixture" -- gen-ipa-inputs -n 1000 --output-file /tmp/ipa-impressions.txt --max-breakdown-key 20 --report-filter source-only --seed 123
cat /tmp/ipa-impressions.txt /tmp/ipa-conversions.txt | sort -t ',' -k1 …
```

Add seed, report-filter and conversion probability arguments to event generator

---

src/protocol/step/mod.rs

Any code change causes rust-analyzer and intellij-rust to recompile macros which takes seconds.
thanks @martinthomson for this suggestion, I can finally code again

Hide compact gate module behind a feature flag

---

src/net/client/mod.rs

Upgrading rustls from 0.21 to 0.25 brought deprecated method usage warning

Fix deprecated method warning in HTTP client code

---

src/helpers/error.rs
src/helpers/gateway/mod.rs
src/helpers/gateway/receive.rs

While dealing with #728 I noticed that end of stream error does not carry the information about the origin and step.

Add step/role to receive error

---

src/protocol/dp/insecure.rs

giving some more room on the difference between variance of rounded and continuous gaussians.  We don't have a theoretical bound to use here right now, so is a simple test but for small epsilon where these can diverge it was failing often.  Ideally, we get a better bound in the future, but the actual plan is to switch to generating a discrete gaussian (or laplace) and stop using the rounded gaussian.

fix flaky dp test

---

docker/helper.Dockerfile

w/o certs installed, it panics with "no ca certificates" error

Make docker image capable of running HTTP IPA

---

src/protocol/basics/reshare.rs
src/protocol/context/validator.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/sort/apply_sort/mod.rs
src/protocol/sort/apply_sort/shuffle.rs
src/query/runner/ipa.rs

* Use gate.as_ref() to print step names, rather than gate id
* Log reshare(vec) and shuffle steps
* Do not print IPA query config for every log line
```
ipa_query{query_config=IpaQueryConfig { per_user_credit_cap: 5, max_breakdown_key: 20, attribution_window_seconds: None, num_multi_bits: 3, plaintext_match_keys: false } query_size=500000}:sort_permutation:validate{gate=6939}: ipa::protocol::context::validator: new
```
is hard to read

Improve logging in IPA

---

src/protocol/dp/insecure.rs

https://github.com/private-attribution/ipa/actions/runs/5694472598

Relax normal distribution bounds for DP test even more

---

src/protocol/step/descriptive.rs
src/telemetry/mod.rs
src/telemetry/step_stats.rs

Current compact gate has an issue (#706) that not all narrowed steps are not executed. This diff adds one metric to our tracing. Each time we narrow a step, we log it and generate metrics output when debug tracing is on. Since `steps.txt` (file we use to generate compact gate) will contain all narrowed steps rather than executed steps, we don't need special handlings for such steps anymore.
This resolves the issue #706, but it also comes with a side effect. The compact gate would now contain state transitions that don't actually trigger communications. I can't think of that being a problem in production, but it is a bit of a concern that we cannot distinguish between comms/no-comms state transitions.
That said, the benefit of being able to get rid of that "magic" in compact.rs surpasses …

collect step tracing each time a step is narrowed

---

src/protocol/step/compact.rs

and Debug impl
These are mostly used to print errors, so allocations don't happen often
Otherwise, errors look like this
```
InfraError(ReceiveError { source: H1, step: "12287", inner: EndOfStream { record_id: RecordId(999424) } })
```

Use strings in Compact gate Display

---

src/hpke/mod.rs
src/report.rs

As we are preparing to create a separate aggregation circuit, we need better names for HPKE primitives used in IPA. We no longer encrypt shares of match keys only, for aggregation we want to encrypt boolean shares of various sizes. We will start with 1 byte shares
This change just moves things around and does a bunch of renames. No functional changes

Generalized hpke

---

src/ff/galois_field.rs
src/ff/mod.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/saturating_sum.rs
src/protocol/mod.rs
src/protocol/prf_sharding/mod.rs
src/secret_sharing/replicated/mod.rs

This PR correctly implements the new OPRF approach to attribution and per-user contribution capping.
Aggregation is left for another day.
This uses a bitwise saturating sum approach to perform the contribution capping, where the caller specifies how many bits to use.
All the logic is reflected in this Google sheet which implements the same oblivious algorithm: https://docs.google.com/spreadsheets/d/1-6cvFe7GbhdzuiaTuiZ9ojq36rA4AVMjBvTqvvpJaHw/edit?usp=sharing
While multiple users can be run in parallel (using a try_join_all for now), each user's circuit is rather deep, with each row of data depending on the preceding row. This can lead to very deep circuits for users with many rows of data.

Attribution and Capping for OPRF approach

---

src/ff/mod.rs
src/protocol/aggregation/mod.rs
src/protocol/attribution/apply_attribution_window.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/basics/if_else.rs
src/protocol/basics/reveal.rs
src/protocol/boolean/add_constant.rs
src/protocol/boolean/bitwise_equal.rs
src/protocol/boolean/comparison.rs
src/protocol/boolean/random_bits_generator.rs
src/protocol/boolean/saturating_sum.rs
src/protocol/boolean/solved_bits.rs
src/protocol/context/malicious.rs
src/protocol/ipa/mod.rs
src/protocol/sort/bit_permutation.rs
src/query/runner/aggregate.rs
src/query/runner/ipa.rs
src/secret_sharing/decomposed.rs
src/secret_sharing/mod.rs
src/secret_sharing/replicated/malicious/additive_share.rs
src/secret_sharing/replicated/semi_honest/additive_share.rs
src/secret_sharing/scheme.rs

This change brings an extra trait bound for linear secret sharing trait, to allow addition and multiplication on references, rather than owned types. Currently it is only possible to do `a + b` or `a + &b`, but not `&a + b` or `&a + &b`. This change makes it possible.
As usual, it is not all rosy here, because of the compiler issue: https://github.com/rust-lang/rust/issues/20671. There is a need currently to specify the additional trait bound on every function, but I think it is worth it because not every `.clone()` call can be eliminated by the compiler, as it can be seen [here](https://rust.godbolt.org/z/MsoTnaeoc). We're better off helping optimizer here. So it cost us additional trait bound, but gives a much nicer addition/multiplication w/o extra clones and makes us not worry about …

Allow addition and multiplication for references to secret shared values

---

src/protocol/basics/reveal.rs

It shouldn't require fields, semi-honest reveal works with shared values just fine.
noticed in #795

Relax semi-honest reveal bounds

---

src/helpers/buffers/ordering_sender.rs
src/helpers/gateway/mod.rs
src/helpers/gateway/receive.rs
src/helpers/gateway/send.rs

So far I've discovered three:
1) Contention when creating a sender
2) Contention when creating a receiver
Those were easy to fix, just use the entry API that provides atomic `check-and-insert`. It costs us a clone but correctness is more important.
3) Race inside `OrderingSender`
This was not that easy to find and fix. Essentially what was happening is two threads (write to `i` and write to `i+1`) both read the same value from `next` atomic ( = `i`). Then, thread `i` won the race and blocked `waiting` shard trying to wake the waker for `i+1`. Obviously there was no waker yet, so it released the lock to let `i+1` thread put its waker there. After that, there was no action that could lead to calling that waker and the whole program stalled. 
I considered a brute force fix (to extend the …

Fix some (all?) concurrency issues inside infrastructure

---

src/helpers/transport/query.rs
src/net/http_serde.rs

It seems that the code introduces a few unnecessary local structs to parse http query parameters into. But these structs are the same as the final QueryType-nested structs.
So, we can parse the params into those structs directly and make the code simpler.

Simplify FromRequest::from_request for QueryConfigParams

---

.github/workflows/check.yml
tests/common/mod.rs
tests/common/tempdir.rs
tests/helper_networks.rs

* Adding ASAN led to a leak discovery, fixed it inside integration tests
* Tried hard to onboard MSAN and TSAN, both don't really work. Opened an issue for MSAN: #800
* "Additional tests" section in our CI grew big and now failing with "no space left on device error". Did not have enough time to investigate, just decided to split it into release and debug builds
Motivation for adding sanitizers: we are preparing for adding unsafe parallelism to simulate structured concurrency and it is crucial to have some guardrails around that mechanism

Add asan and leak sanitizers and tidy up GH

---

ipa-macros/src/derive_step/mod.rs
src/protocol/attribution/mod.rs
src/protocol/context/upgrade.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/prf_sharding/feature_label_dot_product.rs
src/protocol/prf_sharding/mod.rs
src/protocol/sort/apply_sort/shuffle.rs
src/protocol/sort/mod.rs
src/protocol/step/mod.rs

Unblocking @richajaindce for her sparse attribution-aggregation code testing. Dynamic steps can be extended beyond 64. I set the upper limit to 1024 to prevent the IDE from freezing by accidentally writing a huge number and the macro generating gigantic code.

#[dynamic] attribute takes an integer literal to specify the max number of steps

---

Cargo.toml
src/ff/prime_field.rs
src/protocol/prf_sharding/bucket.rs
src/protocol/prf_sharding/feature_label_dot_product.rs
src/protocol/prf_sharding/mod.rs

Move the function to a file on its own.
Skip iterations when the number of buckets is less than half the number of bits and `robust` is false.
Refactor tests.
Add an overflow test and guard against having more than 128 buckets (which we can't support).
Fix gen_range() invocations.
Closes #803.

Restructure the bucketing code

---

.cargo/config.toml
Cargo.toml

This used to require the nightly compiler, but as of https://github.com/RustCrypto/block-ciphers/pull/365 no longer does.
Before:
sort benchmark BATCHSIZE 100 NUM_MULTI_BITS 3 complete after 0.15205078s
After:
sort benchmark BATCHSIZE 100 NUM_MULTI_BITS 3 complete after 0.07513808s

Update aes crate and enable intrinsics on aarch64

---

src/ff/galois_field.rs
src/ff/mod.rs
src/protocol/prf_sharding/bucket.rs
src/protocol/prf_sharding/mod.rs

1. Increasing max number of breakdowns we can support with OPRF to 512
2. In case no conversion is attributed to any bucket, do_aggregation would return vector with zeroes

Minor changes/fixes in OPRF

---

src/protocol/prf_sharding/mod.rs

It was using sequential join that limits number of futures driven concurrently to completion. This circuit requires all user-level circuits to be polled, so `parallel_join` is more appropriate
There may be other places where parallel join must be used, I did not check those, this got me to 10k rows.
```
Running `target/debug/report_collector --network test_data/network.toml --input-file /tmp/events-10000.txt --output-file output.txt --disable-https oprf-ipa --max-breakdown-key 256 --per-user-credit-cap 16 --plaintext-match-keys`
2023-10-31T21:04:37.643906Z  INFO ipa::cli::verbosity: Logging setup at level info
2023-10-31T21:04:38.406898Z  INFO ipa::cli::playbook::ipa: Starting query for OPRF
2023-10-31T21:07:11.873166Z  INFO ipa::cli::playbook::ipa: Running IPA for 10000 records took …
```

Fix OPRF attribution and capping circuit

---

src/ff/galois_field.rs
src/protocol/boolean/generate_random_bits.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/mod.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/generate_permutation_opt.rs

If you only want to convert some fields of a struct, this would allow you to do that.  This is incomplete in the sense that it produces tuples.  You might want to have a type that can be reconstructed from the converted and retained fields.  Maybe that could be part of this functionality also, but I'm leaving that for a future refactoring.

modulus conversion with retention

---

src/cli/verbosity.rs
src/helpers/gateway/receive.rs
src/helpers/gateway/send.rs
src/helpers/mod.rs
src/protocol/mod.rs

See individual commits for details

Logging improvements

---

src/protocol/mod.rs
src/protocol/prf_sharding/mod.rs

There is an issue where sequential join limits the number of Futures that are spawned...
...this interacts poorly with our infra which is waiting for a sufficiently large batch to perform any communication...
...which leads to this deadlock where you're just stuck, and no progress is made...
This is a hack which allows the code to actually run for input sizes > 1000. I do not like this code, but I'll put it up here just to stimulate a conversation about how to move forward. I think I'd prefer a different solution, where we increase the number of futures that can spawn to more than the minimum batch size, so that progress can be made. 
- Running IPA for 10000 records took 27.914203637s
- Running IPA for 100000 records took 308.087942399s
- Running IPA for 1000000 records took …

Hack to avoid stall

---

src/protocol/step/compact.rs

was getting an error running OPRF IPA with compact steps enabled
```
cannot narrow from the invalid step oprf_ipa
stack trace:
```
there is still another issue that I don't know how to fix yet
```
thread 'tokio-runtime-worker' panicked at src/protocol/prf_sharding/mod.rs:219:10:
Invalid state transition: 8815 -> row3
```

Add OPRF root step to compact

---

.github/workflows/check.yml

Its great that we run them twice, but it is probably [too much](https://github.com/private-attribution/ipa/actions/runs/6789188348/job/18458850996). Run them once as part of additional checks step
[Here is the step where we run it](https://github.com/private-attribution/ipa/blob/main/.github/workflows/check.yml#L140)

Remove compact gate tests from basic checks

---

src/protocol/ipa_prf/prf_sharding/mod.rs

I updated the code to filter out all the users with just a single row of data, and never even emit them to the outbound stream, in an effort to reduce the number of futures being created. 
I also moved the "collect" to after the users are "chunked" by OPRF, to just sort them by number of rows descending.
This is a hacky workaround that prevents the infra stall that's caused when a batch of 1024 rows fails to generate 1024 multiplications at depth + 1.
```
Running IPA for 100000 records took 238.103110663s
```

Moving collect to a better place in OPRF IPA

---

benches/oneshot/ipa.rs
src/protocol/ipa/mod.rs
src/protocol/step/compact.rs
src/test_fixture/event_gen.rs

OPRF steps depend on the maximum number of rows of all given users. In order to generate steps for the `Compact` gate, we need to be able to specify exactly how many **user(s)** and **events** we want to generate from the `EventGenerator`.
The current `EventGenerator` randomly generates events between `[1..=max_events_per_user]` per user, for up to `max_user_id` users (the name is confusing. I renamed it to `user_count`). It allows us to control the total number of events to generate, but not the number of events per user.
This is a quick change to fixate the number of events users can produce. We lose the randomness, but for the testing purpose I don't think that is a big deal as the randomness doesn't follow a real-world distribution anyway. Ideally, callers of the generator should be …

make random event generator generate "min_events_per_user..=max_events_per_user" number of events

---

.github/actions/rm/action.yml
.github/workflows/check.yml

14Gb default space is probably not enough for us [anymore](https://github.com/private-attribution/ipa/actions/runs/6797444345/job/18479569860?pr=840)
```
[ec2-user@ip-172-31-49-57 ipa]$ du -sh target/
36G     target/
```
see the discussion here
https://github.com/actions/runner-images/issues/2875
A successful run: https://github.com/akoshelev/raw-ipa/actions/runs/6802955694

Clean up runner space before running actions

---

benches/oneshot/ipa.rs
src/bin/report_collector.rs
src/protocol/ipa/mod.rs
src/test_fixture/event_gen.rs

Our protocols expect timestamps to be within a fixed bit length (i.e., Gf20Bit), but the event generator may generate events that are outside this bound. This change adds a new config parameter to bind the timestamps to be within a given value.

Set timestamp upper limit in EventGenerator's config

---

benches/oneshot/ipa.rs
src/protocol/ipa_prf/prf_sharding/mod.rs
src/test_fixture/ipa.rs

It was a stupid mistake of mine. I initialized the very first row with a share of zero, so we always subtracted zero from the trigger event timestamp, causing the event to get ignored. The bug happens if the first row for a user is a source event and the succeeding trigger event's timestamp is > `ATTRIBUTION_WINDOW_SECONDS`.

OPRF IPA attribution window bug fix

---

.github/workflows/check.yml

Fixes https://github.com/private-attribution/ipa/issues/837 because the underlying issue https://github.com/rust-lang/rust/pull/117542 is fixed
Sanitizers are green again: https://github.com/akoshelev/raw-ipa/actions/runs/6828379933/job/18572392843

Enable sanitizers again

---

ipa-core/src/ff/boolean_array.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs

quick fix for overflow issue when using BA256 with new truncate function. 2 tests failed (doesn't seem related to PR): 
test protocol::ipa_prf::prf_sharding::tests::capping_bugfix ... FAILED
test protocol::ipa_prf::prf_sharding::tests::semi_honest_aggregation_capping_attribution_with_attribution_window ... FAILED
new truncate leads to insecure PRSS for BA256, will get fixed when issue https://github.com/private-attribution/ipa/issues/812 is addressed

quick fix for overflow

---

ipa-core/benches/oneshot/ipa.rs
ipa-core/src/ff/boolean_array.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/query/runner/oprf_ipa.rs
ipa-core/src/test_fixture/ipa.rs
scripts/collect_steps.py

I created another regression in landing #853. 
When running the collect steps script, the outputs do not match the expected values due to differences in how per-user capping is applied.
Unfortunately, now that the per-user cap is a compile-time constant, it's harder to deal with this. I'm not sure how to dynamically select a `type` based on the value of a u32. I'm hopeful that someone can suggest a much better way to do this.
This issue is bigger than just the per-user cap. The number of breakdown keys, the maximum size of a trigger value, everything is a compile time constant now, and we potentially want to choose these things dynamically based on the values provided at runtime.

Fixing error when running collect steps

---

ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/report.rs

Running it with tracing enabled to debug #867 made it quite obvious that we attempt to send 1M records without having a chance to succeed.
I also included some minor fixes to improve diagnostics for event type deserialization

Use sequential join to compute PRF

---

ipa-core/src/ff/curve_points.rs
ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/ff/prime_field.rs
ipa-core/src/secret_sharing/mod.rs

The compiler is smart enough to conditionally derive `Eq` on `AdditiveShare<V: SharedValue>` depending on whether `V: Eq`. However, when the picture gets more complicated for vectorization, there are cases where the compiler can't figure out the Eq / non-Eq variants. Requiring that `SharedValue`s are always `Eq` will simplify things.
(I don't really think there's anywhere that the Eq vs. PartialEq distinction for these types really matters, so we could probably address this by removing any use of `Eq` `AdditiveShare`s, but my impression is that would be a bigger change.)
The only case where I can see this being potentially controversial is `RP25519(CompressedRistretto)`. However, since `CompressedRistretto` (which comes from the curve25519_dalek crate) is `Eq`, it seems safe to make our …

Require that `SharedValue: Eq`

---

ipa-core/src/protocol/ipa_prf/quicksort.rs

Quicksort no longer accepts empty ranges. so if you want to sort an "empty list", you'd need to provide a range like 0..1

fix quicksort test

---

ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
pre-commit

While #900 unblocked the build, it did so in a way that broke the way the "histogram" was computed. This reverts those changes, while continuing to ensure that it doesn't generate any invalid ranges like 0..0 - so now the tests pass.

fixing busted stuff

---

ipa-core/src/ff/boolean_array.rs

Addresses #911 by returning a `NonZeroPadding` error for bit arrays that don't have infallible conversions. 
I had to change the awesome Martin's macro in order to be able to generate a bit array with all ones. Unfortunately, for bit arrays that are not multiples of 8, `bitarr!` macro generate a byte array with all `1`s. So for 20 bit wide array, `bitarr[1; 20]` generates a [u8::MAX; 3], instead of `100000h`. 
Unfortunately, macros can't do math, so we need to specify explicitly whether deserializing a  BAXX is fallible or no. Infallible deserialization has a compile-time check for multiples of 8, so we don't accidentally set it for wrong boolean arrays

Reject paddings != 0 for boolean arrays

---

.github/codecov.yml
.github/workflows/check.yml
scripts/coverage-ci

tested on my repo: https://app.codecov.io/github/akoshelev/raw-ipa/commit/1a593623b8bd0c8f205c17ebbcb46e2ce267f4c4/tree

Add code coverage to the CI

---

ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/galois_field.rs

Make Galois field follow Boolean arrays deserialization strategy (added in #912): for lengths that are not multiple of 8, reject inputs with non-zero padding.

Fallible deserialization for Galois fields

---

ipa-core/src/ff/galois_field.rs

...sort of.  I haven't tried very hard to confound the optimization
routines in the compiler.
This could slow things down, but I believe that it is essential as a
baseline to ensure that we don't leak.
This adds a new test, because I discovered that our Gf20 polynomial was
incorrectly transcribed.

Make Galois multiplication constant time 

---

.github/codecov.yml

Given that there are plenty of false positives (#920, #919), it does not make sense to keep the target coverage that high.

Relax CodeCov targets

---

ipa-core/src/ff/boolean.rs
ipa-core/src/ff/galois_field.rs
ipa-core/src/protocol/basics/share_known_value.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs

Making the members of `AdditiveShare` private reduces the number of things that will need to be updated for vectorization.
In cases where there is both horizontal and vertical vectorization, my plan is that the vertical (across records) is the inner vectorization, and the horizontal (vector-type values within one record) is the outer. My plan is that values of this sort will be stored in `BitDecomposed<AdditiveShare<BitVec>>`. (The most likely candidate for `BitVec` is a Boolean array, although for vertical vectorization, it should rarely be necessary to access individual elements of the vector, and disallowing such access except through special pack/unpack primitives may catch some bugs.)

Remove public access to `AdditiveShare` members

---

ipa-core/Cargo.toml

We use it in one place where we read the encryption keys for match keys.
The reason why it was working before: `axum-server` [brought](https://github.com/programatik29/axum-server/blob/9d5adb28bfa483bda401714ad43f5f5c8d12cb61/Cargo.toml#L16) it.

Include tokio fs feature

---

ipa-core/src/protocol/attribution/aggregate_credit.rs
ipa-core/src/protocol/ipa/mod.rs
ipa-core/tests/common/mod.rs
scripts/collect_steps.py

The new approach to aggregation (binary tree, moving value obliviously) is just more efficient than our old code. No reason not to use this improved algorithm in old IPA as well.

Backport of improved aggregation logic to old IPA

---

ipa-core/src/ff/prime_field.rs
ipa-core/src/helpers/transport/stream/input.rs

Fixes a bug in `random_chunks` that showed up with `TestField = Fp31`, makes empty streams a candidate input, and fixes the greater-than-prime error in #931. The combination of `arb_size_in_bytes` and `arb_aligned_bytes` into `arb_expected_and_chunked_body` is not to fix a bug, it just seemed unnecessarily complicated. 
I got failures in Fp32BitPrime twice within 10-15 minutes, but I think I was lucky and O(hours) is a more realistic time frame. You can also change the TestField to Fp31 to get a failure immediately.
Fixes #931.

Generate valid field elements, and other fixes for RecordsStream proptest

---

ipa-core/src/helpers/buffers/ordering_sender.rs
ipa-core/src/helpers/gateway/send.rs
ipa-core/src/helpers/transport/in_memory/transport.rs

Prompted by https://github.com/private-attribution/ipa/pull/852/files#r1464197048.
I compromised the quality of the assertion in `State::write` a little. It may not be as effective in catching broken configurations, but it should still prevent reaching a deadlock.
There are two ways I can see revising this:
* Get rid of the notion of spare entirely, and just require that messages are uniformly sized (less work).
* Use an enum to track the mode (spare capacity vs. uniform message size), and the observed message size in the uniform case. This would restore the quality of the assertion, but would be a bit more work to implement.

Allow zero spare space in `OrderingSender`

---

.github/workflows/check.yml

We've started getting "no space left on device" [errors](https://github.com/private-attribution/ipa/actions/runs/7777348395/job/21205786323?pr=939) for these actions

Clean up GH runners for CodeCov and Sanitize actions

---

ipa-core/Cargo.toml

This should help with https://github.com/private-attribution/ipa/actions/runs/7806487945/job/21292951289?pr=898 but I am not sure until I see the CI results
Related issue: https://github.com/tkaitchuck/aHash/issues/200
before bump:
```bash
> cargo tree -i ahash
error: There are multiple `ahash` packages in your project, and the specification `ahash` is ambiguous.
Please re-run this command with one of the following specifications:
ahash@0.7.7
ahash@0.8.6
> cargo tree -i ahash@0.7.7
ahash v0.7.7
└── hashbrown v0.12.3
├── indexmap v1.9.3
│   └── metrics-util v0.15.1
│       ├── ipa-core v0.1.0 (/Users/koshelev/workspace/rmstuff/ipa/ipa-core)
│       └── metrics-tracing-context v0.14.0
│           └── ipa-core v0.1.0 (/Users/koshelev/workspace/rmstuff/ipa/ipa-core)
└── ordered-multimap …
```

[DRAFT] Bump config dependency

---

ipa-core/benches/ct/arithmetic_circuit.rs
ipa-core/benches/iai/arithmetic_circuit.rs
ipa-core/benches/oneshot/arithmetic_circuit.rs
ipa-core/src/error.rs
ipa-core/src/ff/boolean.rs
ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/curve_points.rs
ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/ff/field.rs
ipa-core/src/ff/galois_field.rs
ipa-core/src/ff/mod.rs
ipa-core/src/ff/prime_field.rs
ipa-core/src/helpers/buffers/ordering_sender.rs
ipa-core/src/helpers/gateway/send.rs
ipa-core/src/helpers/gateway/stall_detection.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/protocol/basics/mul/mod.rs
ipa-core/src/protocol/basics/mul/semi_honest.rs
ipa-core/src/protocol/basics/mul/sparse.rs
ipa-core/src/protocol/modulus_conversion/convert_shares.rs
ipa-core/src/secret_sharing/array.rs
ipa-core/src/secret_sharing/mod.rs
ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs
ipa-core/src/test_fixture/circuit.rs
ipa-core/src/test_fixture/mod.rs
ipa-core/src/test_fixture/sharing.rs

Semi-honest AdditiveShare can hold a vector of sharings instead of just one sharing. The semi-honest multiply can operate on these vectors.
There are some comments in `src/secret_sharing/mod.rs` that may help provide an overall picture.
* This includes the changes from #908; once that is merged the diff will be smaller (but still big).
* Earlier versions introduced a `Gf2Array` type, I have removed it in favor of using the BA types.
* I did not end up merging `SharedValueArray` with `ArrayAccess` / `CustomArray`, because there's actually a significant difference between the two: protocol code shouldn't need to access individual elements of a `SharedValueArray` since the computation for each record is exactly the same.
Results from `cargo bench --no-default-features -F …

Vectorization for prime fields

---

ipa-core/src/error.rs
ipa-core/src/ff/boolean.rs
ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/mod.rs
ipa-core/src/protocol/basics/mul/semi_honest.rs
ipa-core/src/protocol/basics/mul/sparse.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/secret_sharing/array.rs
ipa-core/src/secret_sharing/decomposed.rs
ipa-core/src/secret_sharing/mod.rs
ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs

Builds on #852.
Adds support for vectorization of bitwise protocols, and adds vectorized version of `compare_gt` (used by quicksort).
Unvectorized bitwise protocols operate on `AdditiveShare<BA>`, as before (bits of the BA are different bits of multi-bit values associated with a particular record). Vectorized bitwise protocols operate on `BitDecomposed<AdditiveShare<BA>>`, where the elements of the outer `BitDecomposed` are different bits of multi-bit values associated with a particular record, and bits of the inner BA are the values of a particular bit position for a stripe of records. Adds an `ArrayAccessRef` variant of the `ArrayAccess` trait that is implemented for both kinds of inputs, and an `ArrayBuilder` trait that is implemented for both kinds of outputs.
`compare_gt` benchmark. …

Vectorization of boolean arrays

---

.github/workflows/check.yml

checkout@v3 triggers a warning: https://github.com/private-attribution/ipa/actions/runs/7777716103

Use checkout@v4 action in CI consistently

---

ipa-core/Cargo.toml
ipa-core/src/test_fixture/logging.rs

Requires `logging::setup()`, but otherwise works smoothly by running [`tokio-console`](https://github.com/tokio-rs/console) client that consumes metrics emitted by IPA benchmarks and shows per-task and combined stats

Enable Tokio tasks profiler

---

ipa-core/src/ff/boolean.rs
ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/ff/field.rs
ipa-core/src/protocol/basics/check_zero.rs
ipa-core/src/protocol/basics/if_else.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/mul/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/protocol/prss/crypto.rs
ipa-core/src/secret_sharing/array.rs
ipa-core/src/secret_sharing/mod.rs
ipa-core/src/test_fixture/input/sharing.rs

* Remove `Field` trait impl from Boolean arrays.
* Remove u128 conversions from `Fp25519`.
* Add `select` variant of `if_else`. `select` is bus multiplexer with a single-bit control input. `if_else` is a vectorizable multiplexer, with condition input the same width as the data inputs.
* Remove `Field` (or replace with `SharedValue`) in various trait bounds.
* Implement `Vectorizable` and related traits for more boolean arrays.

Clean up `Field` trait

---

ipa-core/src/protocol/basics/check_zero.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/boolean/comparison.rs
ipa-core/src/protocol/boolean/solved_bits.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs

This change also removes the `B: RecordBinding` type parameter on the `Reveal` trait, which is no longer used after removal of IPAv2.
The complexity with vectorized reveal is converting the reveal output from `[T; 1]` to `T` in unvectorized protocols. For general handling of vectorized shares, there are two sets of methods (on the `AdditiveShare` type) -- the existing `new`, `left`, and `right` methods only work for unvectorized shares; the `new_arr`, `left_arr`, and `right_arr` methods return vector shares (even in the case where the vector dimension is one). We could do something similar with reveal, but it would be more complicated because it's traits instead of types. It doesn't seem worth it for the relatively small number of places that we call reveal.

Vectorized reveal

---

ipa-core/benches/ct/arithmetic_circuit.rs
ipa-core/benches/iai/arithmetic_circuit.rs
ipa-core/benches/oneshot/arithmetic_circuit.rs
ipa-core/src/test_fixture/circuit.rs
ipa-core/src/test_fixture/sharing.rs
pre-commit
scripts/coverage-ci

The previous version of the benchmark did not use seq_join. Using seq_join is necessary for parallel execution, and also provides a fairer baseline for unvectorized serial operation.
This change also generates test data outside the timed region (except under the iai framework, where that is not supported).

Rewritten arithmetic circuit benchmark

---

Cargo.toml
ipa-core/src/ff/curve_points.rs
ipa-core/src/ff/galois_field.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/step/mod.rs
ipa-core/src/test_fixture/circuit.rs
ipa-core/src/test_fixture/mod.rs
ipa-core/src/test_fixture/world.rs

Usually !debug_assertions => compact-gate, but that is not the case when profiling.

Turn off debug assertions in benchmark configs; enable strings as steps based on `cfg(test)`

---

scripts/collect_steps.py

adding a small update to the `collect_steps.py` script to have the option for multithreading.

add command line flag to collect_steps.py for multi-threading

---

ipa-core/src/ff/boolean_array.rs

The default one is too verbose.
Before:
```
(StdArray([BA32(BitArray<u8, bitvec::order::Lsb0> { addr: 0x12b842774, head: 000, bits: 32 } [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])]), StdArray([BA32(BitArray<u8, bitvec::order::Lsb0> { addr: 0x12b842778, head: 000, bits: 32 } [0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0])]))
```
after
```
(StdArray([BA32([1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])]), StdArray([BA32([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0])]))
```

Change boolean debug representation

---

scripts/collect_steps.py

PR #963 changed the root step name, now our script is failing.
Would be great to add it to CI, but I have high hopes that #961 is not too far ahead.
Tested by manually running this script

Fix collect_steps script

---

ipa-core/src/ff/prime_field.rs
ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs
ipa-core/src/protocol/ipa_prf/malicious_security/mod.rs
ipa-core/src/protocol/ipa_prf/mod.rs

cleaned up version of Lagrange

Precomputed Lagrange

---

ipa-core/Cargo.toml
ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs

Really minor change to remove one more iter_mut

removing one more iter_mut in the denominators

---

ipa-core/src/error.rs
ipa-core/src/helpers/buffers/unordered_receiver.rs
ipa-core/src/helpers/error.rs
ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/gateway/receive.rs
ipa-core/src/helpers/gateway/send.rs
ipa-core/src/helpers/gateway/stall_detection.rs
ipa-core/src/helpers/gateway/transport.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/prss_protocol.rs
ipa-core/src/helpers/transport/in_memory/mod.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/helpers/transport/receive.rs
ipa-core/src/helpers/transport/stream/collection.rs
ipa-core/src/lib.rs
ipa-core/src/net/transport.rs
ipa-core/src/sharding.rs
ipa-core/src/test_fixture/app.rs
ipa-core/src/test_fixture/world.rs

See #969 for overall approach.
This change introduces two fundamental concepts for horizontal scaling - `ShardIndex` and `Transportidentity`. 
The former will be used the same way as `HelperIdentity` is used nowadays - unique identifier of a peer we are communicating with. Having in mind 200B events, we may need more than 65k shards, thus 4 byte identifier usage. 
`TransportIdentity` is a generalization for peer identifiers used at transport layer.  Two fundamental structs implement it: `HelperIdentity` and `ShardIndex` to allow communication via MPC and shard channels.
`Role` is used at the Gateway/Context layer for communication purposes and `RoleResolvingTransport` is a convenient abstraction, so it also implements `TransportIdentity`.
`Transport` trait became generic over …

First building blocks for Sharding API: ShardIndex and TransportIdentity

---

ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/gateway/receive.rs
ipa-core/src/helpers/gateway/transport.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/in_memory/handlers.rs
ipa-core/src/helpers/transport/in_memory/mod.rs
ipa-core/src/helpers/transport/in_memory/routing.rs
ipa-core/src/helpers/transport/in_memory/sharding.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/query/processor.rs
ipa-core/src/sharding.rs
ipa-core/src/test_fixture/app.rs
ipa-core/src/test_fixture/sharing.rs
ipa-core/src/test_fixture/world.rs

This change introduces the ability to run very simple circuits on multiple shards in parallel. It is not possible to communicate between shards yet, but it is possible to use the same test infrastructure to create multiple shards and use PRSS inside them as well as provide the input for each shard and consume their output.
The next and hopefully final change will bring the ability to communicate across shards.

TestWorld for sharded environments

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/reshare.rs
ipa-core/src/protocol/modulus_conversion/convert_shares.rs

Similar to a recent change to `Reveal`. After removing old IPA we no longer need this implementation of `Reshare` for `Vec`s.

Remove RecordBinding type parameter from Reshare

---

ipa-core/src/protocol/ipa_prf/malicious_security/mod.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

First diff to verify zero knowledge proofs.

Verifying ZKPs part one

---

ipa-core/Cargo.toml
ipa-core/src/bin/ipa_bench/config.rs
ipa-core/src/bin/ipa_bench/models.rs
ipa-core/src/cli/ipa_output.rs
ipa-core/src/cli/mod.rs
ipa-core/src/cli/noise.rs
ipa-core/src/error.rs
ipa-core/src/ff/field.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/query/mod.rs
ipa-core/src/helpers/transport/query/oprf_shuffle.rs
ipa-core/src/lib.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/protocol/mod.rs
ipa-core/src/protocol/step/compact.rs
ipa-core/src/protocol/step/descriptive.rs

Removed the `enable-serde` flag and made Serde a non-optional dependency. Removed the `cfg` attributes that depended on the feature since now the library is included by default.
Both unit tests and `./pre-commit` pass.
closes private-attribution/ipa#588

Serde is now a non-optional dependency

---

ipa-core/src/test_fixture/world.rs

temporary fix for clippy, once we have implemented the malicious framework, we can fix it more permanently.

add #[allow(clippy::diverging_sub_expression)]

---

ipa-core/src/helpers/transport/stream/input.rs

`RecordsStream` is a convenient abstraction that takes care of polling the underlying raw byte stream, buffering enough data and deserializing them into a client-provided type `T`. It also handles padding and unaligned errors.
Before this change, stream element could only be a `Vec<T>` which means an extra allocation for clients that want to handle items one by one. This is the case for shard receiving streams.
Shard receiving streams are polled by MPC protocols that get records out of them one-by-one. The key difference between MPC receiving streams and shard receiving streams is that the former wants the ability to receive elements out of order. For shard streams, it is not required.
Shard streams can benefit from using `RecordsStream` abstraction quite a lot. I have it in my private …

Enable dual-mode for `RecordsStream`

---

ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/gateway/receive.rs
ipa-core/src/helpers/transport/in_memory/sharding.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/helpers/transport/receive.rs
ipa-core/src/helpers/transport/stream/box_body.rs
ipa-core/src/helpers/transport/stream/input.rs
ipa-core/src/helpers/transport/stream/mod.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/server/handlers/query/step.rs
ipa-core/src/net/transport.rs

This change is to unify stream handling between in-memory and real-world implementations. Before, in memory streams yielded `Vec<u8>` and HTTP streams operated on `Result<Bytes, _>`.
This discrepancy required us to build a compatibility layer, and it makes sense now to unify both implementations.
The main motivator for this change is to be able to use `RecordsStream` inside shard receivers - `UnorderedReceiver` use case fits MPC model well, but is clunky to use inside shard channels - we always receive items in a pure streaming fashion instead.

Use `BytesStream` inside `Transport` trait

---

ipa-core/benches/oneshot/ipa.rs
ipa-core/src/lib.rs

This does a few things towards the end goal in the description:
* Increase the log level for the random seed from trace to info.
* Adjust the initialization order so that logging is initialized in time to log the random seed.
* Add configuration of a 2nd log target to TestWorld (specifically, we want the benchmark crate `oneshot_ipa` in addition to `ipa_core`).

IPA bench: log random seed and runtime at info level

---

ipa-core/src/app.rs
ipa-core/src/bin/helper.rs
ipa-core/src/helpers/buffers/ordering_sender.rs
ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/gateway/receive.rs
ipa-core/src/helpers/gateway/send.rs
ipa-core/src/helpers/gateway/stall_detection.rs
ipa-core/src/helpers/gateway/transport.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/prss_protocol.rs
ipa-core/src/helpers/transport/in_memory/sharding.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/helpers/transport/receive.rs
ipa-core/src/helpers/transport/stream/input.rs
ipa-core/src/helpers/transport/stream/mod.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/ipa_prf/shuffle/base.rs
ipa-core/src/query/processor.rs
ipa-core/src/test_fixture/app.rs
ipa-core/src/test_fixture/mod.rs
ipa-core/src/test_fixture/world.rs

This change adds the necessary functionality to `Gateway` to be able to communicate between shards.
`get_shard_sender` and `get_shard_receiver` will allow circuits to send and request data from other shards, similarly to MPC send/recv.
There is a difference in how receives are handled for MPC and shards. The former channels use `UnorderedReceiver` that lets them receive records in any order. Shard receivers return a stream that has a FIFO order. This is a requirement that came from analysing shuffle and other protocols that require cross-shard communication. Each shard does not know in advance how many records it expects to receive from any shard.
This also adds a stub for HTTP shard transport, just to make the code compile. Actual HTTP implementation will come later.
In terms of next …

Implement shard communication channels for MPC circuits

---

ipa-core/benches/oneshot/ipa.rs
ipa-core/src/test_fixture/world.rs
scripts/collect_steps.py

Ignore random seed message in captured output.

Fix collect_steps

---

ipa-core/benches/oneshot/ipa.rs
ipa-core/src/bin/report_collector.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/test_fixture/event_gen.rs
ipa-core/src/test_fixture/ipa.rs

IPAv3 sorts the input records, so add sorting of input records to ipa_in_the_clear, and remove it from input drivers.
IPAv3 also shuffles the input records, so if there are duplicate timestamps among a single user's records, the output may be non-deterministic. To avoid end-to-end test failures, modify the test data generator to avoid generating duplicate timestamps. Add a directed test to exercise duplicate timestamps.
Possibly a fix for #967.

Duplicate timestamp and input-sorting changes

---

ipa-core/src/secret_sharing/decomposed.rs
ipa-core/src/secret_sharing/vector/transpose.rs

Add additional macros in transpose implementation, to reduce repetitive code

Transposes for vectorized aggregation

---

ipa-core/Cargo.toml
ipa-core/src/bin/helper.rs
ipa-core/src/cli/playbook/mod.rs
ipa-core/src/config.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs

This is part of the journey to update all of IPA's HTTP dependencies to the latest and greatest (tracked private-attribution/ipa#924). I have found that these versions (see `Cargo.toml`) together with a custom `axum-server` branch I created specifically for this change, allow us to bump until rustls0.22.3. This will be an intermediate step until all dependencies are updated.

Stabilizing versions around rustls0.22.3 and hyper 0.14.28

---

ipa-core/src/protocol/ipa_prf/malicious_security/hashing.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

The previous implementation was not 100% correct because with some probability it could generate an `r` value that must not be used by the prover. This change fixes that by introducing small bias when converting from 32 byte hash to a field value.

Biased field conversion for Fiat-Shamir

---

ipa-core/src/protocol/basics/mul/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs

`select` did not exist yet when I initially used a vector op in these routines. They are not truly vectorized, so the revised implementation better reflects what's going on.

Use BooleanArrayMul and `select` for saturated add/sub

---

ipa-core/src/helpers/buffers/ordering_sender.rs
ipa-core/src/helpers/buffers/unordered_receiver.rs
ipa-core/src/helpers/transport/stream/collection.rs

We used `will_wake` in correctness checks to make sure we don't hang the future/stream forever if a wrong waker is used, but the contract for this function is best-effort and it started generating more and more false positives.
The recent one, found by @aleiserson, is inside rust-lang (https://github.com/rust-lang/rust/pull/119863/), so it is very hard to get around.
We don't have a good replacement for this check unless we implement our own waker, but it is probably too much for now

Remove will_wake calls

---

ipa-core/Cargo.toml
ipa-core/src/net/client/mod.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/server/mod.rs

This is another step towards updating all of IPA's dependencies (tracked in private-attribution/ipa#924). This change bumps Rustls to the latest version. To make it work I had to fork `hyper-rustls` with some minimal changes so that all versions in the build remain compatible.

Using Rustls 0.23

---

ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs

It turns out that `evaluate_per_user_attribution_circuit` was returning a vector of rows, where all rows but one were zero. This seems silly. If we are confident that the logic ensures all rows contribute zero except for one, we can just collapse each user's contribution to a single row by adding all of a user's rows together. No need for any communication, since there can never be any carries.

minor simplification to logistic regression

---

ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/protocol/context/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_semi_honest.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs

There should be no reason to make them accessible via `Context` - only contexts that are created in the presence of multiple shards should provide the ability to open and close these channels.
This should improve the type safety for sharding functionality as it won't be possible to see those methods on non-sharded executions

Move shard send and recv channel methods to `ShardedContext` trait

---

ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/query/runner/oprf_ipa.rs
ipa-core/src/secret_sharing/decomposed.rs
ipa-core/src/secret_sharing/mod.rs
ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs
ipa-core/src/secret_sharing/vector/impls.rs
ipa-core/src/secret_sharing/vector/mod.rs
ipa-core/src/test_fixture/ipa.rs

More precisely, these methods still support unvectorized operation (a vectorization dimension of 1), but using them in that mode will now use 8x more memory than the previous version, because bits are not packed within bytes.
Network utilization should not be affected, because these protocols are doing bitwise arithmetic, which never had efficient network utilization in the unvectorized case.
In exchange for the performance loss under particular conditions, a bunch of code can be deleted and some of the remaining code can be simplified. However, in the (unvectorized) attribution code, things get slightly more complicated, to unpack bits into and repack bits from BitDecomposed.
I am offering this for discussion as something that simplifies some of the vectorized code.

Change some methods that were generic over vectorized/not to only support vectorization

---

ipa-core/src/error.rs
ipa-core/src/helpers/hashing.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/share_validation.rs
ipa-core/src/protocol/ipa_prf/malicious_security/mod.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

Include Sum To Zero Check Protocol since it is needed for DZKP verification.
It was originally a part of https://github.com/private-attribution/ipa/pull/930
It can also be used to check the consistency between shares, i.e. as a base protocol for https://github.com/private-attribution/ipa/pull/936
I moved Hashing to Prss, since it is similar (basic cryptographic operation). The only difference is that it is not keyed.

Sum To Zero Check Protocol

---

ipa-core/src/protocol/context/dzkp_field.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/telemetry/mod.rs

The PR removes the option from vec, and changes some of the more complex and expensive functionalities.
It changes the seq_join function on the validator (now validated_seq_join) and separates the chunk_size parameter in two separate parameters: chunk_size is the amount of futures processed in a single chunk (i.e. DZKP Batch) and multiplication_amount which determines how much memory is allocated within a Batch. 
chunk_size is now an input to validated_seq_join whereas multiplication_amount is specified at the time the validator is generated.
The PR does not make changes to the DZKP conversion which is a separate PR which I will also adjust as discussed: https://github.com/private-attribution/ipa/pull/1032
Upon request by Ben Savage and Alex Koshelev, the PR deletes the reallocation …

Improvment to the DZKP Batch Storage

---

ipa-core/Cargo.toml
ipa-core/src/helpers/transport/stream/axum_body.rs
ipa-core/src/helpers/transport/stream/box_body.rs
ipa-core/src/net/error.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/server/handlers/echo.rs
ipa-core/src/net/server/handlers/query/create.rs
ipa-core/src/net/server/handlers/query/input.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/server/handlers/query/prepare.rs
ipa-core/src/net/server/handlers/query/results.rs
ipa-core/src/net/server/handlers/query/status.rs
ipa-core/src/net/server/handlers/query/step.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/step/compact.rs

This is another step towards updating all of IPA's dependencies (tracked in private-attribution/ipa#924).
Note Axum 0.6 adds state to extractors, but we aren't using those for now (created private-attribution/ipa#1047 to track this). This version of Axum still uses hyper 0.14.
Also, as part of this update, Axum extractions separate Body operations from Body Parts (headers, query, etc). A nice improvement is that Body cannot be extracted twice thanks to the new API (BodyAlreadyExtracted exception is gone).
Instead of a having a custom Axum extractor per server handler, with this change we're using separate re-usable extractors for each of the HTTP parts reducing the amount of code in http_serde. Following is an example from the create handler. 
Here's how the code used to be:
```Rust
async …
```

Update to Axum  0.6

---

.github/workflows/check.yml

We are working towards reducing the total number of steps (#1056 is the step in that direction) and compact gate rearchitecture (#961) in parallel. The old compact gate gets broken because of that but there is no real reason to fix it.
To avoid red CI, this temporarily disables compact gate checks until #961 is merged

Temporarily disable compact-gate checks

---

ipa-core/src/protocol/boolean/and.rs
ipa-core/src/protocol/ipa_prf/aggregation/bucket.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs

Synced up with @benjaminsavage and fixed the documentation for this function - we use it on trigger values, not on breakdown keys.

Go down from 9 to 8 bits in bool_and operation

---

ipa-core/src/protocol/boolean/or.rs
ipa-core/src/protocol/context/upgrade.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/protocol/step/mod.rs

…based on how many are actually needed.
This is my second attempt. @martinthomson says the approach in #1065 will not work in terms of reducing the total number of compact gate steps that will be generated with the new approach. Hopefully this approach works better!

Specializing the BitStep for integer_add and integer_sub

---

ipa-core/src/protocol/basics/mul/step.rs
ipa-core/src/protocol/boolean/and.rs
ipa-core/src/protocol/boolean/mod.rs
ipa-core/src/protocol/boolean/step.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/step.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/step.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/step.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/protocol/step.rs
ipa-core/src/test_fixture/world.rs
ipa-step/src/gate.rs
scripts/coverage-ci

Addresses most of the comments from #961 PR.

Compact gate follow up

---

ipa-core/src/protocol/basics/share_known_value.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/context/upgrade.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/test_fixture/world.rs

... and make it an associated type instead.
My intuition for when the type parameter on the trait is needed is when the same trait needs to be implemented multiple times on a particular type, with some aspect of the implementation that varies based on the value of the type parameter. That is not the case for our concrete use case of this trait -- the MAC-based malicious protocol is associated with one particular field and can only work with values of that field.
If many of the places referencing the trait need to specify the value of the type, then it is more compact to specify a type parameter (`Trait<T>`) than an associated type bound (`Trait<Foo = SomeType>`). I applied this rationale for the `SharedValueArray` vectorization-related trait, but I don't think it's relevant here.
I …

Remove type parameter from `trait UpgradedContext`

---

ipa-core/src/cli/playbook/ipa.rs
ipa-core/src/helpers/stream/chunks.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/mod.rs

* Remove some unnecessary `IntoIterator` bounds on `Chunk` methods.
* Add a `Chunk::map` helper to transform chunk data without extracting it from the wrapper. Use this instead of the somewhat confusing `into_raw` method. A side effect of this change is we no longer aggregate extra zero rows in the last block, which improves performance on small inputs.
* To further speed up `protocol::ipa_prf::tests::semi_honest`, switch it to 5-bit breakdown keys and 8-bit histogram values.
* Add a check that the `BK` and `B` parameters are consistent.
* Move type aliases from `protocol` to `cli/playbook/ipa`. Fixes #1079.

Small aggregation changes and test speedup

---

ipa-core/src/ff/boolean.rs

small PR to implement ArrayAccess trait for Boolean.  Have run into needing when working on DP noise in MPC but probably not bad to have it generally added.   w/ @akoshelev

array access for boolean

---

ipa-step-derive/src/track.rs

`std::file!()` is `ipa-core/build.rs`, which is then interpreted relative to the package directory as the non-existent `ipa-core/ipa-core/build.rs`. This results in rerunning the build script and rebuilding the package on every build.
The default behavior, if the build script does not emit any `rerun-if-changed` directives, is to re-run it on every build. Emitting `rerun-if-changed=build.rs` can be used to suppress this behavior in the case where there are no other applicable rerun-if-changed directives. With or without `rerun-if-changed=build.rs`, cargo is smart enough to rebuild if the build script changes.
I considered whether to emit `rerun-if-changed=build.rs` when no step definition files are configured, but optimizing for that case doesn't seem worth the extra complexity.

Don't emit rerun-if-changed for the build script

---

ipa-core/src/helpers/gateway/mod.rs

My theory is that we are deadlocking around HTTP communication because data segments of 1,024 vectorized messages are too large relative to our buffering.
Considering only steps that involve communication, the following four protocol steps occur in sequence:
* PRF evaluation: Multiply r * y
* PRF evaluation: Reveal R
* PRF evaluation: Reveal z
* Quicksort: Bit 0 subtraction for first pass
Note: there is a rate mismatch between PRF evaluation and quicksort (PRF is vectorized by 64 and quicksort is vectorized by 256). However, unlike the stall cases we saw before, all of the PRF output is collected into a vector before beginning quicksort. Also, for input sizes of 50,000 records, a segment of 1,024 vectorized records spans the entire protocol, meaning there is only one segment of step data …

Reduce default active work 1024 -> 32

---

ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

This PR just makes changes to compute_proof changing the input types from iterators over fields to GenericArrays of fields. It also works now for owned values and references.

change compute_proof in prover.rs

---

ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

@danielmasny has pointed out that there is a lot of duplication of logic between `compute_proof` and `compute_final_proof`. We could potentially just use one. The caller just needs to be careful to "mask" the "u/v" vectors with randomly distributed points at index 0. By eliminating this method, we do not have any compile time guarantees that it will be used correctly (i.e. the inputs will be masked) but we can follow up with a solution for this later.

Eliminate compute_final_proof

---

ipa-step/src/gate.rs
ipa-step/src/hash.rs
ipa-step/src/hashing.rs
ipa-step/src/lib.rs

I was investigating why build with compact gate takes that long and everything pointed to large match statements inside `FromStr` and `AsRef` trait implementations for `CompactGate`. The major bottleneck was `AsRef` match statement and overall the size of match statement impacts build time exponentially. Once the number of steps crosses the 70k boundary, release builds do not finish. 
The fix was to replace the match arms with something else for both `FromStr` and `AsRef`. Latter can be done with a simple array indexed by compact gate index, so it is very straightforward. That alone got the compile time down from ~4mins to 50s for 20k steps.
Fixing `FromStr` is more involved because it requires a lookup table. I've experimented with PHF and an array of tuples `(hash(str), gate index)`, …

Improve build time for compact gate

---

ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

Follow up on #1094 to use `zip_chunks` in one more place

Use zip_chunks inside `sample_proof` test everywhere

---

ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

doing similar changes to verifier.rs as in https://github.com/private-attribution/ipa/pull/1090
- use GenericArray as inputs and in ProofVerifier vector
- use iterator with Borrow trait
- adjust tests to work with updated inputs

use gen array in verifier as well

---

ipa-core/src/helpers/buffers/ordering_sender.rs
ipa-core/src/helpers/buffers/unordered_receiver.rs
ipa-core/src/helpers/gateway/send.rs
ipa-core/src/net/server/handlers/query/step.rs

I've been using these for quite a while, but forgot to commit them to the main branch. This logs the following operations:
* When Hyper comes in to take the next chunk from ordering sender
* When unordered receiver gets more data from the underlying HTTP stream
* When helper receives a new step request

Add more tracing to the infrastructure

---

ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/server/config.rs
ipa-core/src/net/server/mod.rs

It was diagnosed as root cause for #1085. Here are the reasons why we think it is safe to turn it off:
* We have flow control built in at the application layer. `OrderingSender` provides backpressure per stream/step and MPC protocol logic breaks the whole execution into chunks where we open large but limited number of streams.
* We have flow control at TCP layer
* Connection level flow control for HTTP2 connections works well for web-servers that don't control clients that can connect to it. In our case, we have a very limited set of clients for each MPC-to-MPC connection.
I had a chat with @aleiserson, and we think ultimately it will be beneficial if we only used one mechanism to provide and given the nature of IPA, it would be better to have full control there. This means that …

Disable connection-level flow control for HTTP2 streams

---

ipa-core/src/protocol/context/dzkp_field.rs

Moving away from use of GenericArray in favor of just normal vanilla arrays.

Remove more GenericArray usage

---

ipa-core/build.rs
ipa-core/src/protocol/ipa_prf/dp/mod.rs
ipa-core/src/protocol/ipa_prf/dp/step.rs
ipa-core/src/protocol/step.rs

Small PR for an `apply_dp_noise` function which adds noise to a vector of values.  This will be used when both applying the noise in the case of aggregation and `feature_label_dot_product` but I'll split those into separate PRs.

apply_dp_noise function

---

ipa-core/Cargo.toml
ipa-core/src/bin/helper.rs
ipa-core/src/bin/report_collector.rs
ipa-core/src/config.rs
ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/transport/stream/axum_body.rs
ipa-core/src/helpers/transport/stream/box_body.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/error.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/net/server/handlers/echo.rs
ipa-core/src/net/server/handlers/query/create.rs
ipa-core/src/net/server/handlers/query/input.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/server/handlers/query/prepare.rs
ipa-core/src/net/server/handlers/query/results.rs
ipa-core/src/net/server/handlers/query/status.rs
ipa-core/src/net/server/handlers/query/step.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/context/dzkp_field.rs

Using newest version of Axum (0.7.5) and Hyper which is beyond 1.0 bringing more stability. Since Hyper doesn’t include a client, we are using the one suggested in Hyper-Utils, which is a drop-in replacement from the client that was present in Hyper 0.14.
Hyper now relies on Http-Body 1 which cascaded into a bunch of changes to HTTP bodies used throughout the code. Hyper also gives the option to pick any execution framework, but we’re sticking to Tokio.
During my testing I observed that the tests like `https_semi_honest_ipa` would get stuck. After a lot of debugging, I was able to identify `SETTINGS_MAX_CONCURRENT_STREAMS` option for HTTP2 connections as the culprit. By default, Hyper-Utils sets it to 200 which is insufficient for that test. 1000 was the “smallest” number I was able to …

Upgraded to Axum 0.7

---

ipa-core/src/helpers/stream/chunks.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs
ipa-core/src/secret_sharing/vector/array.rs
ipa-core/src/secret_sharing/vector/transpose.rs

Share conversion uses boolean shares, while PRF evaluation uses Fp25519 and RP25519 shares. The latter are much larger than the former, so adjust the implementation to support differing vectorization factors. This introduces a vector-to-vector conversion problem like the one in aggregation, although vectorization is still across records on both sides so the solution here at least doesn't involve a transpose.
The separation of share conversion and PRF evaluation into two seq_joins may also be useful when adding malicious securitiy.
This also cleans up a few things that were left over from when there were multiple versions of the share conversion test for vectorization factors of 1, 16, 64, and 256.

Decouple vectorization for share conversion and PRF evaluation

---

ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs

It should help to better understand the bottlenecks, so more tracing was added to each routine to see the latency breakdown
I also had to fix some clippy issues after refactoring, so new type alias is there for this exact reason
```bash
2024-06-04T00:51:33.032403Z  INFO ipa_core::cli::verbosity: Logging setup at level info
2024-06-04T00:51:33.424129Z  INFO ipa_core::net::server: server listening on http://0.0.0.0:3002
2024-06-04T00:53:05.842863Z  INFO stall_detector{role=H3}: ipa_core::helpers::gateway::stall_detection::gateway: new
2024-06-04T00:53:05.846146Z  INFO oprf_ipa_query{sz=50000}: ipa_core::query::runner::oprf_ipa: new
2024-06-04T00:53:05.846201Z  INFO oprf_ipa_query{sz=50000}: ipa_core::query::runner::oprf_ipa: New query: IpaQueryConfig { per_user_credit_cap: 8, …
```

Carve out the attribution circuit from aggregation routine

---

ipa-core/src/protocol/ipa_prf/dp/mod.rs

Small PR to implement Thm 1 of this paper https://arxiv.org/pdf/1805.10559 which allows us to go from an epsilon, delta and other parameters to the minimum number of bernoulli samples we need to achieve that level of DP.
See this doc for more discussion. https://docs.google.com/document/d/116qQIgVoz3uV8axbmVWfif6dTjBVww5THecPqC0kERw/edit
Much of this PR is a translation into Rust of this earlier python script https://github.com/private-attribution/ipa/compare/main...bmcase:raw-ipa:binomial_variable_p

num_bernoulli from epsilon, delta

---

ipa-core/src/protocol/basics/share_validation.rs
ipa-core/src/protocol/context/dzkp_field.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

This is a split from https://github.com/private-attribution/ipa/pull/1083
PR adds recursion function for the prover as well as an UVValues struct that keeps track of the length.

proof recursion in prover.rs

---

ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/galois_field.rs
ipa-core/src/ff/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/dp/mod.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/query/runner/oprf_ipa.rs
ipa-core/src/secret_sharing/decomposed.rs
ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs
ipa-core/src/secret_sharing/replicated/semi_honest/mod.rs
ipa-core/src/secret_sharing/vector/transpose.rs
ipa-core/src/test_fixture/input/sharing.rs

* Add a BooleanArray trait as shorthand for `SharedValue + CustomArray<Element = Boolean>` (and a few other traits that are always implemented for boolean arrays).
* Delete ArrayAccessRef (not needed after #1049 and perhaps `impl DerefMut for BitDecomposed`).
* Remove ArrayAccess for Galois fields (perhaps not needed after fix for #1079).
* Remove some generics from some AdditiveShare-related things that are only used with Boolean arrays.

Simplify some things related to boolean arrays

---

ipa-core/src/protocol/dp/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs

I don't think we should be hard-coding "UpgradedSemiHonestContext" into our protocols. That's a strange dummy type that's there so that a Semi Honest Context can get "upgraded" but it won't actually do anything.
We probably want to make our protocols not really care if it's operating in a semi-honest or a malicious context. This PR is about starting to make that change.

Step one of removing UpgradedSemiHonestContext

---

ipa-core/src/query/executor.rs

This is an attempt to mitigate #1120 by hinting Tokio executor that query task maybe blocking the worker thread for longer than expected and it should hand off everything from that worker thread.
Here is how this issue is reproducible in our environment
Tokio executor is a work-stealing scheduler that optimizes for low latency and
resource utilization. It optimizes for low scheduling overhead and uses the same worker
threads for polling tasks and to service IO and timer operations, if they are enabled.
This leads to very low overhead, but also to an unfortunate possibility of tasks that are
long-running to block the entire runtime, even if it is multithreaded.
Here is an example in IPA code that led to this discovery:
- IPA query kicks in and first step it performs a very large …

Hand off Tokio bookkeeping tasks before starting a new IPA query

---

ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

We can further simplify the verifier code by just breaking down the `verify_proof` function into the two separate components.
I'm sorry the diff view is so unhelpful... I removed the ProofVerifier struct as it's no longer needed, and cargo fmt moved everything back one indentation... which is displayed so badly in the diff view.

Further simplifying the verifier code

---

ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/mul/semi_honest.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs

The old BasicProtocols was no longer used anywhere. This replaces it with a version that includes only the basic protocols that have been vectorized. It also makes some progress towards not exposing semi-honest protocols on arbitrary contexts (which is unsafe).
Split from #1112.

Revise BasicProtocols

---

ipa-core/src/helpers/buffers/circular.rs
ipa-core/src/helpers/buffers/mod.rs

I've been running IPA at scale and one thing #1085 revealed is that network stack (hyper and kernel) does not really like the large buffers we've been sending after vectorization was enabled. @andyleiserson showed that keeping active work at 1024 results in 1.6Mb chunks sent down from the send buffers. Reducing active work to 32 eliminated the stall, but, according to my perf tests, it made our network utilization worse.
Fixing the size of `take`, allowed to increase active work parameter to extreme values (100k) and below are the results of those experiments (1M rows, real hardware, no match key encryption, HTTPS). 
Active work (items) | Max send chunk size (bytes) | Runtime (seconds) | Delta (from baseline) | Notes |
|-- | -- | -- | -- | -- |
1024 | 4096 | 438 | 0 | Baseline
32 | 1024 | …

Add circular buffer implementation to be later used inside `OrderingSender`

---

ipa-core/src/protocol/ipa_prf/malicious_security/mod.rs
ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

verifier.rs computes p and q now recursively without allocation in a vector by using streams and the chunks method on streams
Unfortunately Rust treats streams as different types even when they use the same Item type. I used Pin<Box<Dyn<>> to be able to store different types an accomplish evaluating streams recursively. 
I have tried using the chunks method by itertools. Unfortunately, I ran into issues since stream::chunk returns chunks that are vectors, itertools:chunks seems to return a reference to some custom chunk type.
@andyleiserson I think there is probably something that can be improved.
@andyleiserson I did not manage to make your borrow trick work such that I can use streams of owned values or references. The issue is that the  Pin<Box<Dyn<Stream<Item = B>>>> became complex, …

recursive computation of p and q final without allocation

---

ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

I left a few small naming suggestions on #1134. It's easier to just merge that PR and put up a new one with those changes given timezones =).
The tests were also bothering me. I have tried to unify what we are testing with the actual approach we intend to use. Namely:
1. To use a consistent compression factor for every step, including the final step. Not vary the compression factor for the final recursive step.
2. For the final proof, to first move element at index 0 to the end of the array, then overwrite index 0 with the mask.
Now that these are unified, we can just test it two ways, manually calling `recurse_u_or_v` many times, as well as to call `recursively_compute_final_check`. Now we can just assert these give the same answer.
How did I get the expected numbers? I updated the …

Cleaning up test code

---

ipa-core/src/protocol/basics/mul/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/secret_sharing/vector/impls.rs

remove generic support for other Fields from dzkp_validate since we plan to only support Fp61BitPrime for now.

remove generic support for other Fields from dzkp_validate

---

ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

Computes zero shares for all proofs at once.
Also removes async from recurse_u_or_v as @benjaminsavage has pointed out since it was not needed.
renamed iterators that were streams to streams

Compute zero shares for all proofs at once

---

ipa-core/src/ff/boolean_array.rs

These tests use specific fields, so we shouldn't waste compiler's time generating them for all field implementations

Move field-specific tests from `boolean_array_impl_small`

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/mod.rs

upgrades the conversion that uses Boolean integer addition to malicious security by using upgraded contexts.
It still needs to be generalized to use traits, such that it works for DZKP semi honest as well as DZKP malicious. The most important structure is already in the PR.

Upgrade OPRF Conversion to Malicious using DZKPs

---

ipa-core/src/protocol/basics/mul/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/secret_sharing/vector/impls.rs

cleans up validate such that it doesn't use a counter as input anymore

split validate into validate and validate_chunks

---

ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/sigmoid.rs

For 8-bit signed values that are assumed to represent x = -8 to x = 8 (that is, each consecutive 8-bit value is 1/16th larger than the previous one), one can very closely approximate the sigmoid function $1/(1 + exp(-x))$ with just a piecewise linear function. Simply split up the range into 16 segments of width 16 (e.g. [0, 16), [16, 32), ...) and approximate each with a line segment.
Best of all, this function only requires 31 bits of communication (per helper) to compute this, less than a single multiplication in our Fp32BitField. The round-depth is only 3 since mostly it's all parallelised. It's also vectorised, so we can pack many parallel computations together. 
Here's a graph showing the true sigmoid function in blue, and this approximation in red. As you can see, they are quite …

8-bit sigmoid function through piecewise linear approximation

---

ipa-core/src/utils/arraychunks.rs
ipa-core/src/utils/mod.rs

adding chunk methods that returns iterator over arrays
this allows us to use iterators instead of streams when chunks is needed during the DZKP validation.
It resolves issues with Mutex and await points in https://github.com/private-attribution/ipa/pull/1164

chunk_array

---

ipa-core/src/bin/test_mpc.rs
ipa-core/src/cli/playbook/add.rs
ipa-core/src/cli/playbook/generator.rs
ipa-core/src/cli/playbook/input.rs
ipa-core/src/cli/playbook/mod.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/query/mod.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/protocol/step.rs
ipa-core/src/query/executor.rs
ipa-core/src/query/runner/add_in_prime_field.rs
ipa-core/src/query/runner/mod.rs
ipa-core/src/query/runner/test_add.rs
ipa-core/tests/common/mod.rs
ipa-core/tests/helper_networks.rs

This change adds a new simple test circuit and integration tests for it. This circuit does not do anything sophisticated and the need for it is dictated by #1141 where I need to test that inputs of size > 2Gb can be handled by our MPC helpers. 
I tried to use `test-multiply` but it just takes too long to process inputs of this size. I estimated ~300M field value pairs need to be submitted to exceed $2^{31}-1$ input size and that makes that circuit to run for 8+ mins. 
This circuit is much faster for two reasons. First, it does not require communication. Second, it generates input and shares it using iterators. That makes a big difference - my experiments showed that it takes roughly 9 mins to get `test-multiply` inputs delivered and ~50 seconds for `test-add`. It can be further optimized …

Create test addition circuit

---

ipa-core/src/app.rs
ipa-core/src/bin/helper.rs
ipa-core/src/config.rs
ipa-core/src/hpke/mod.rs
ipa-core/src/hpke/registry.rs
ipa-core/src/net/test.rs
ipa-core/src/query/executor.rs
ipa-core/src/query/processor.rs
ipa-core/src/query/runner/oprf_ipa.rs
ipa-core/src/report.rs

This adds a new struct `PublicKeyOnly`, similar to the existing `PrivateKeyOnly`, allowing us to only provide a private key for the current helper. A helpers own public key should not need to be known when running.

add new PrivateKeyOnly struct to handle KeyRegistry with only a private key

---

ipa-core/Cargo.toml
ipa-core/benches/ct/prss.rs

This was used to evaluate the performance of #1185 and I'd like to keep it around for some time.

Add PRSS criterion benchmark

---

ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/transport/query/mod.rs

For inputs smaller than 32k, this changes nothing. For inputs larger than 32k, this improves the latency of IPA as shown in #1118

Increase active work size to 32k

---

.github/workflows/check.yml
ipa-core/src/bin/test_mpc.rs
ipa-core/src/helpers/transport/stream/axum_body.rs
ipa-core/src/helpers/transport/stream/box_body.rs
ipa-core/src/helpers/transport/stream/mod.rs
ipa-core/src/net/transport.rs
ipa-core/tests/common/mod.rs
ipa-core/tests/helper_networks.rs
pre-commit

This fixes #1141 and adds a test that verifies that clients can submit inputs larger than 2GB ($2^{31}$ - 1). The test is quite slow (40 seconds), so I gated it behind an environment variable and only run it on Github. The probability of breaking it is quite low, so it is fine if it fails on CI only. 
IPA uses two different stream types for in-memory and real-world infrastructure to submit bodies - one is Axum type and another one is just boxed byte stream. The fix must be applied to both because **report_collector** uses in-memory streams and **helper** binary and **integration tests** use Axum stream.
In order to have only one place that splits the incoming byte, both streams had to be hidden behind an umbrella type `BodyStream` that works for both.

Split large request bodies into chunks of size not exceeding 1 MB 

---

ipa-core/src/helpers/buffers/unordered_receiver.rs

The waker at `start` is actually for `self.next + wakers.len()`, not `self.next`. The `max_polled_idx` case (line 284) can also put `self.next` in the list. Having two zeros in the list (when `self.next` is zero) results in an underflow computing `num - 1` in `to_ranges`.
I am not sure how best to test this (either a regression test for the fix, or to make sure the change doesn't break anything else). But opening a PR anyways so it's less likely the issue just gets lost.

Fix a corner case in stall detection

---

ipa-core/src/protocol/prss/crypto.rs
ipa-core/src/protocol/prss/mod.rs

This is the first step to allow PRSS to generate only one part of randomness, shared with one helper. The motivating issue is #1029. To support that, we need to enforce uniqueness checks at the lower layer because each generator now can be called at different times.
This change moves the `used` variable to `Generator` struct. This required some rethinking of `generate` method parameter types - instead of raw `u128`, it now takes `PrssIndexu128`. Mainly for debugging purposes, to be able to print "index:offset" when a duplicate index is used.

Enforce index uniqueness inside the Generator struct

---

ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/prss.rs
ipa-core/src/protocol/prss/crypto.rs
ipa-core/src/protocol/prss/mod.rs

Builds on top of #1185
This closes https://github.com/private-attribution/ipa/issues/1029 by adding a method to PRSS implementation that allows callers to specify which randomness they want to obtain: shared with the helper on the right or on the left. This saves 50% of computation in cases where only one side of PRSS is required. https://github.com/private-attribution/ipa/issues/1029 lists the cases where it is useful.
Happy to bikeshed on naming, it gets harder and harder to find good names

Allow PRSS to generate randomness shared with only one helper

---

ipa-core/src/protocol/context/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs

Without chunking, for now.
The tests for share conversion created the validator in the test code, with a record count tailored for the test. Quicksort creates the validator internally, with a reasonable chunk size for production. However, this resulted in paying the cost to verify a production-sized chunk, even for test cases with minimal input size. There are some changes here to remedy this.

Add malicious validate to quicksort

---

ipa-core/src/protocol/basics/check_zero.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs
ipa-core/src/secret_sharing/replicated/malicious/additive_share.rs
ipa-core/src/test_fixture/sharing.rs
ipa-core/src/test_fixture/world.rs

Another piece of #1112. This modifies the reveal implementations so that reveal is implemented only for upgraded contexts, and not for any `C: Context`. The danger of `impl Reveal<C: Context> for /* semi honest */ AdditiveShare<F>` is that it could accidentally be invoked by a protocol intending to have DZKP malicious security.
This changes the `check_zero` protocol used for MAC-based malicious security to use a malicious reveal, however, there is still a problem with the zero check, see https://github.com/private-attribution/ipa/issues/1204#issuecomment-2261313344.
The reveals in PRF evaluation are changed to call `malicious_reveal` directly because the PRF doesn't yet take a context of an appropriate type. I've added a TODO, which can be cleaned up with the changes for malicious …

Implement reveal for upgraded contexts only

---

ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/protocol/basics/mul/malicious.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/secret_sharing/replicated/malicious/additive_share.rs
ipa-core/src/secret_sharing/replicated/malicious/mod.rs
ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs
ipa-core/src/secret_sharing/vector/array.rs
ipa-core/src/secret_sharing/vector/traits.rs

This change gets us closer to running maliciously secure PRF evaluation. As semi-honest protocols are vectorized at this point, malicious functionality needs to be upgraded to match it. This change does that and a few more things
* Vectorize MAC computations
* Vectorize malicious multiply
* Add a few helper methods (induce, expand, transform) to secret sharings

Vectorize malicious shares

---

ipa-core/src/protocol/dp/mod.rs
ipa-core/src/protocol/ipa_prf/mod.rs

change parameters in `semi_honest_with_dp` to make faster. 
Move `gen_binomial_noise_16_breakdowns` to be a slow test.

Speed up dp tests

---

ipa-core/src/protocol/basics/reshare.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/context/upgrade.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/test_fixture/world.rs

When working on vectorizing malicious shares,
we noticed that the existing upgrade API does not work for vectorized shares. It either required contexts to be vectorization-aware which we tried to avoid up to this point, or a different mechanism to specify how upgrades occur for vectorized shares.
For example: `Replicated<F, N>` when upgraded, gets transformed to `MaliciousReplicated<F, N>` and different `N` values, require different bounds on functions.
That was a blocker for PRF evaluation upgrade and the solution we came up with was to introduce `Upgradable` trait.
The functionality of this trait is very similar to `UpgradeToMalicious` and `Upgrade` but upgrade now is bound explicitly to `RecordId`. This optimizes for protocols readability. Malicious upgrades in tests had to find a way …

Use Upgradable trait in MAC module

---

ipa-core/src/protocol/basics/mul/malicious.rs
ipa-core/src/protocol/basics/reshare.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/basics/share_known_value.rs
ipa-core/src/protocol/boolean/or.rs
ipa-core/src/protocol/context/batcher.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/test_fixture/world.rs

This API serves multiple purposes:
Previously, the validation process was separate, detached from actual protocol and validated everything at once. We saw multiple occurrences where reveal was called before sharings were validated.
Vectorization makes data processed in chunks. Going between different chunk sizes (one for data, one for validation) has proven to be challenging. The code written for that was hard to read.
The core of this proposal is to put `validate_record` API on the `UpgradedContext` that takes a `record_id` and blocks the execution until this record (and others in the same batch) has been validated. FWIW this is exactly how ZKP validator works now.
This API allows to bring closer together MAC and ZKP validation.
In addition to bringing this API, this change also updates …

Add `validate_record` API to upgraded contexts

---

ipa-core/src/protocol/dp/mod.rs

very small PR to help understand if cross cloud testing is stuck in `apply_dp_noise` or at some point after it.

add tracing to the apply_dp_noise fn

---

in-market-test/v2/hpke/encrypt_report.py
ipa-core/Cargo.toml
ipa-core/src/cli/crypto.rs
ipa-core/src/cli/mod.rs
ipa-core/src/query/mod.rs
ipa-core/src/query/runner/mod.rs

right now this is mostly just for reference (I also intend to add a test to make sure this stays in line with the IPA codebase), but if we start using more any more python, we should add a linter/format check to our github checks.

Python formatting

---

in-market-test/v2/hpke/encrypt_report.py

This updates the python script so that it can encrypt with 3 different helper public keys.
I updated this so that I could test decryption, but it's not working unfortuantely.
```
./target/debug/crypto_util encrypt --input-file tmp/raw_reports.txt --output-dir tmp --network tmp/keys/network.toml
```
```
./target/debug/crypto_util decrypt --input-file1 tmp/helper1.enc --input-file2 tmp/helper2.enc --input-file3 tmp/helper3.enc --mk-private-key1 tmp/keys/h1_mk.key --mk-private-key2 tmp/keys/h2_mk.key --mk-private-key3 tmp/keys/h3_mk.key  --output-file tmp/out.dec
```
produces no diff between `tmp/raw_reports.txt` and `tmp/out.dec`.
```
./in-market-test/v2/hpke/.venv/bin/python in-market-test/v2/hpke/encrypt_report.py --pub_key 92a6fb666c37c008defd74abf3204ebea685742eab8347b08e2f7c759893947a …
```

add 3 public keys when encrypting to files

---

pre-commit

`echo " ${@@Q}"` causes a `Bad Substitution error` in zsh (now the default on macOS), which very unfortunately gives a 0 exit code.  `echo " ${*}"` still prints the command that it failed on, and it should work with bash and zsh.

fix precommit bug when using zsh

---

in-market-test/v2/ansible/provision.yaml

this uses the `package` module in ansible, rather than `yum` specifically. we started with that, because Amazon Linux is Redhat based, but this will work more generically. it also points directly to `rustup` and `cargo`, which aren't on the path in debian.

make package installs more generic across OSs

---

ipa-core/src/protocol/dp/README.md

Fix bug in DP README.md

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/helpers/transport/query/mod.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/net/server/handlers/query/create.rs
ipa-core/src/query/executor.rs
ipa-core/src/query/processor.rs

simpler way to have a feature flag for relaxed padding DP parameters.  should fix draft crashing.

 update feature flags for relaxed DP

---

ipa-core/Cargo.toml
ipa-core/src/bin/report_collector.rs
ipa-core/src/cli/crypto.rs
ipa-core/src/cli/mod.rs
ipa-core/src/cli/playbook/ipa.rs
ipa-core/src/cli/playbook/mod.rs
ipa-core/src/report.rs
ipa-core/tests/common/mod.rs
ipa-core/tests/compact_gate.rs
ipa-core/tests/encrypted_input.rs
ipa-core/tests/helper_networks.rs

Here's an initial draft for how we can allow for encrypted inputs in 3 distinct files.
It moves the old way of running it into a new command "oprf-ipa-test". One open question here is if we should remove the idea of plaintext vs encrypted match keys, since we now expect the full event to be encrypted for the encrypted code path.
This still needs tests, and a little clean up, but wanted to open this to get feedback on the overall approach.

Encrypted Input Buffer

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/cli/crypto.rs

missed this when renaming in the last PR. inconsequential but good to have names aligned.

align variable and struct naming

---

ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/boolean/and.rs
ipa-core/src/protocol/boolean/or.rs
ipa-core/src/protocol/boolean/step.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/step.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/step.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-step-derive/src/lib.rs
ipa-step-derive/src/variant.rs
ipa-step-test/src/lib.rs

This does a few things:
* Adds (panicking) `From<int>` impls for tuple struct steps, converts a few single-variant-enum steps to tuple struct steps, and adds (also panicking) `Step::variant(int)` constructors for enum variant indexed steps.
* Adds a check for out-of-range index in the low-level `base_index` function in the generated compact gate code. The error message suggests using the bounds-checked constructors of the previous bullet. The tuple struct member is private, so can't be constructed directly, but in the enum variant case, we can't prevent constructing it directly with an out-of-range index.
* Adds tests for the preceding two items, and a test for the panic message when invoking attribution with more than 64 records per user.

Detect out-of-bounds step indices

---

ipa-core/src/test_fixture/hybrid.rs
ipa-core/src/test_fixture/mod.rs

To write tests for the "Hybrid" protocol, we need to compare the results generated to some kind of "ground truth" correct answer. This provides that.

New in the clear implementation for Hybrid

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/test_fixture/ipa.rs

Kill some dead code

---

ipa-core/src/bin/test_mpc.rs
ipa-core/src/helpers/transport/query/hybrid.rs
ipa-core/src/helpers/transport/query/mod.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/query/executor.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/query/runner/mod.rs

This is the first step in getting our query infrastructure ready to handle hybrid protocol requests. It adds `Hybrid` query type that is not implemented.
At the same time, we are about to start testing our sharding infrastructure and we need a query type for that as well. @cberkhoff asked for this change so it is easier to put them together

Hybrid and sharded suffle query types

---

.github/workflows/check.yml
ipa-core/build.rs
ipa-core/src/lib.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/boolean/or.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/step.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/step.rs
ipa-core/src/secret_sharing/into_shares.rs
ipa-core/src/secret_sharing/vector/transpose.rs
ipa-core/src/test_fixture/circuit.rs
ipa-core/src/test_fixture/mod.rs
ipa-core/src/test_fixture/step.rs
ipa-core/src/test_fixture/test_gate.rs
ipa-step/src/gate.rs
ipa-step/src/hash.rs
scripts/coverage-ci

This fixes #1285. It was a silly error where the code used 32 bit step, but the compact gate declaration pointed to 16 bit. I spent the majority of the time actually reproducing this error in a unit test and making compact gate work with in-memory infra to allow people to write more of them.
So this PR essentially brings a test to reproduce the issue, runs more things with compact gate enabled and adds yet another approval step to the CI. It also fixes compile errors that we had for long time with compact gate and in memory infrastructure. Those errors stayed in the code because we never ran it with compact gate

Fix the saturated addition panic inside IPA

---

.github/workflows/check.yml
ipa-core/src/cli/crypto.rs
ipa-core/src/cli/playbook/input.rs
ipa-core/src/hpke/registry.rs
pre-commit

Our observation it takes 10+ minutes for all tests to pass and it is blocking people from working on other things. This change intends to keep only basic checks where we see the majority of failures: formatting, clippy and basic tests.
It is still possible to run all checks by setting  `EXEC_SLOW_TESTS` environment variable to 1

Improve pre-commit runtime by running fewer checks

---

pre-commit

This fix makes pre-commit not to run checks behind environment variable flag if it is not set

Fix pre-commit script

---

ipa-core/src/helpers/transport/stream/mod.rs
ipa-core/src/lib.rs
ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs

We are having some flakiness with this test: https://github.com/private-attribution/ipa/actions/runs/11018449181/job/30598750956?pr=1307 and I attribute it to having too many iterations (by default it is set to 32). Even running it locally takes a long time and it is not possible to have reliable detection for large routines.
This attempts to fix #1312

Reduce number of iterations for breakdown reveal test

---

ipa-core/src/app.rs
ipa-core/src/helpers/transport/handler.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/routing.rs
ipa-core/src/helpers/transport/stream/collection.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/net/server/handlers/query/kill.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/transport.rs
ipa-core/src/query/mod.rs
ipa-core/src/query/processor.rs

In our testing with external parties, it became quite evident that bouncing helpers if query fails is far from having good experience for people who run the test. We need to have an ability to kill queries that failed on one or more helper and restart the runs.
This change does exactly that - adding a `/query_id/kill` handler that will respond with immediately aborting the task that runs an IPA query.
if helper address is `helper.com`, one can terminate a query by sending a POST request to 
```
http(s)://helper.com/query/0/kill
```
For local testing it can be done easily with `curl`
```
curl -X POST http://localhost:3002/query/0/kill
```
if query is killed successfully, the following response is provided by the helper
```json
{"query_id":"0","status":"killed"}
```

Add a handler to kill a query

---

ipa-core/src/helpers/gateway/send.rs

It was proven useful in several investigations, so we should just enable it

Print send config in tracing

---

ipa-core/src/protocol/context/step.rs
ipa-core/src/protocol/ipa_prf/aggregation/step.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/step.rs

Running Draft on 50M records revealed that we don't have sufficient number of steps for zero-knowledge proof runs.
I tried to keep the step limit under 20k, so I did some cleanup as well, but I think I failed and I had to bump it.

Increase number of steps for DZKP proof to 600 from 192

---

.clippy.toml
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/ipa_prf/shuffle/base.rs

This code was written to address a failure observed in `protocol::ipa_prf::aggregation::breakdown_reveal::tests::semi_honest_happy_path` tests. After some investigating I realized the issue only manifested when using the Shuttle crate (not the `multithreading` feature). Shuttle sets a [limit on the stack of 32kb](https://github.com/awslabs/shuttle/blob/main/src/lib.rs#L248) instead of the usual 2MBs.
Instead of just increasing that threshold, I used a few tools (Like the crate [TopTypeSizes](https://docs.rs/top-type-sizes/latest/top_type_sizes/) and [size_of_val](https://doc.rust-lang.org/std/mem/fn.size_of_val.html)) to analize what types could be causing the stack to grow too large, focusing on Futures which tend to be the culprits in these cases. The root stems from `shuffle_protocol` …

Pinning shuffle futures that are too large for Shuttle

---

ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/oprf_padding/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs

Use the relaxed parameters for most tests, and disable padding for the end-to-end malicious test when running under shuttle.
I believe this will resolve the newer failure symptom in #1312.

Plumb padding parameters to breakdown_reveal_aggregation

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/mul/dzkp_malicious.rs
ipa-core/src/protocol/basics/mul/mod.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/context/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/test_fixture/world.rs

The next step to be able to run sharded protocols is to change the validators API and support both sharded and non-sharded contexts.
This is a fairly straightforward change that just propagates `ShardBinding` trait bound through MAC and ZKP contexts and validators

Support sharding in MAC and ZKP validations

---

ipa-core/src/protocol/basics/mul/malicious.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/test_fixture/world.rs

This is the final PR in the series (#1333, #1315) that enables writing sharded malicious protocols.
The support is added for `Runner::malicious` function, and it can be used to execute malicious circuits. Other methods like `upgraded_semi_honest` and `upgraded_malicious` haven't been touched yet - I am not convinced that these are necessary and we can update them as we go.
The core goal here is to unblock efforts to implement Hybrid protocol

Support sharded malicious protocols inside the test infrastructure

---

ipa-core/benches/oneshot/ipa.rs
ipa-core/src/app.rs
ipa-core/src/bin/helper.rs
ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/gateway/send.rs
ipa-core/src/helpers/gateway/stall_detection.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/prss_protocol.rs
ipa-core/src/lib.rs
ipa-core/src/protocol/basics/mul/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/query/processor.rs
ipa-core/src/test_fixture/circuit.rs
ipa-core/src/test_fixture/world.rs
ipa-core/src/utils/mod.rs
ipa-core/src/utils/power_of_two.rs

This is the second attempt to mitigate send buffer misalignment. Previous one (https://github.com/private-attribution/ipa/pull/1307) didn't handle all the edge cases and was abandoned in favour of this PR.
What I believe makes this change work is the new requirement for active work to be a power of two. With this constraint, it is much easier to align the read size with it. Given that `total_capacity = active * record_size`, we can represent `read_size` as a multiple of `record_size` too:
`read_size = X * record_size`. If X is a power of two and active_work is a power of two, then they will always be aligned with each other.
For example, if active work is 16, read size is 10 bytes and record size is 3 bytes, then:
```
total_capacity = 16*3
read_size = X*3 (close to 10)
X = 2 (power of two …
```

Fix send buffer misalignment [No 2]

---

.github/workflows/check.yml

We are getting errors in our CI like these, so everything is blocked now: https://github.com/private-attribution/ipa/actions/runs/11243388038/job/31259140713
Thanks to @andyleiserson who pointed that out that we could actually exclude packages that are failing because we only use unsafe features in ipa-core. He also figured that this failure may be related to this https://github.com/lu-zero/cargo-c/issues/398#issuecomment-2349191336 which means that the fix may be coming soon
I checked the fix in my repo and it appears to be working: https://github.com/akoshelev/raw-ipa/actions/runs/11246313348/job/31267934735

Exclude all packages from sanitizers except ipa_core

---

ipa-core/src/app.rs
ipa-core/src/lib.rs
ipa-core/src/query/executor.rs
ipa-core/src/query/processor.rs
ipa-core/src/query/state.rs

The time has come to have a need to have a precise control over which runtime is used to run queries. The reason for that is that we had another occurrence of HTTP keep-alive timeout that aligns with OPRF computation.
https://draft-mpc.vercel.app/query/view/nervy-fret2024-10-05T0245
```
2024-10-05T03:57:35.203964 - 2024-10-05T03:57:35.203922Z  INFO oprf_ipa_query{sz=50000000}:compute_prf_for_inputs: ipa_core::protocol::context::batcher: batch 30 is ready for validation
2024-10-05T03:57:35.206943 - 2024-10-05T03:57:35.206901Z  INFO oprf_ipa_query{sz=50000000}:compute_prf_for_inputs: ipa_core::protocol::context::batcher: batch 31 is ready for validation
2024-10-05T03:57:35.209813 - 2024-10-05T03:57:35.209777Z  INFO oprf_ipa_query{sz=50000000}:compute_prf_for_inputs: …
```

Introduce IpaRuntime and plumb it all the way down to executor

---

ipa-core/src/cli/metric_collector.rs
ipa-core/src/cli/verbosity.rs

It turns out we've been running with metrics overhead the whole time. I tested a run locally with `disable-metrics` feature and to my surprise I still saw the telemetry emitted from helper binary.
Upon investigating, I came across our `Verbosity` struct that was installing the collector unconditionally. I changed that and tested that metrics are no longer emitted

Make disable-metrics feature turn off global recorder

---

ipa-core/src/bin/helper.rs
ipa-core/src/cli/playbook/mod.rs
ipa-core/src/lib.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/error.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs

This attempts to mitigate panics we're seeing in PRF where computing proofs + PRF values stalls all available CPUs for long time and that prevents HTTP heartbeats and causes receive timeouts on all helpers. We create two dedicated runtimes to avoid scheduling conflicts.
This shouldn't impact our existing backpressure mechanisms as application receivers are still responsible for not polling the H2 streams if they are full

Set up separate runtimes for HTTP and MPC queries

---

ipa-core/src/query/runner/oprf_ipa.rs
ipa-core/tests/compact_gate.rs

@akoshelev here is a few basic tests to show the that IPA doesn't work for per user credit cap of 1, 2, 3, or 4.

add test to show that IPA fails for cap 1, 2, 3, and 4

---

ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs

* Don't start all aggregation batches from record 0.
* Fix a bug in insert_segment_large when segments are added out-of-order.
* Remove unused `last_record` and tweak `is_empty`.
* Add a few tests.

Fixes for aggregation batching

---

ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs

The benefit of using it is it does not require trait bounds math as `Serializable` trait and it can be used in const context

Add compile time function to compute the size of AdditiveShare

---

ipa-core/src/bin/helper.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs
ipa-core/src/sharding.rs

This is the first of a series of pull requests (PR) to enable sharding on IPA.
This change doesn't meaningfully change any tests or the operation of IPA. This is just adding abstractions that are going to be useful later.
The key introduction of this PR is the `TransportRestriction` trait. Please take a read at the included docs for more details. To make more sense of the intended usage of this new trait, I'm modifying `MpcHelperClient` to make use of it, but without altering it's API, yet. I understand the scope of this example is limited, hence I can answer questions about its future use if needed.
Renamed `ClientIdentity::Helper` to `ClientIdentity::Header` since I'm planning to use the same mechanism for Shard to Shard identity resolution.

[Sharding 1] TransportRestriction and Client

---

ipa-core/src/protocol/context/mod.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/query/runner/mod.rs
ipa-core/src/query/runner/reshard_tag.rs

In https://github.com/private-attribution/ipa/pull/1358 it was mentioned that waiting until all AAD tags and match keys have been collected before starting resharding process adds latency that is unnecessary. We can start resharding process right when we received the first tag and do everything in parallel.
This change does that by leveraging newly added `reshard_try_stream` and a few helper structs and functions to make it ergonomic to use

Streaming tag resharding and match key collection in Hybrid 

---

Cargo.toml
ipa-metrics/Cargo.toml
ipa-metrics/src/collector.rs
ipa-metrics/src/context.rs
ipa-metrics/src/controller.rs
ipa-metrics/src/key.rs
ipa-metrics/src/kind.rs
ipa-metrics/src/label.rs
ipa-metrics/src/lib.rs
ipa-metrics/src/partitioned.rs
ipa-metrics/src/producer.rs
ipa-metrics/src/store.rs
scripts/coverage-ci

Follows the design described here
https://docs.google.com/document/d/1cRnE024bi7KJYeqMT8yMYluIplA8992bNIaeKBmrXp4/edit#heading=h.d8g3vju6yaqd
I have a working solution where this crate is integrated with IPA. There will be 3 separate PRs to make the transition
* [This PR] ipa-metrics crate with core functionality
* ipa-metrics-tracing that adds support for metric partitioning in tests
* Migrate IPA to new metrics engine

Add ipa-metrics crate

---

ipa-core/src/bin/helper.rs
ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/server/handlers/mod.rs
ipa-core/src/net/server/handlers/query/create.rs
ipa-core/src/net/server/handlers/query/input.rs
ipa-core/src/net/server/handlers/query/kill.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/server/handlers/query/prepare.rs
ipa-core/src/net/server/handlers/query/results.rs
ipa-core/src/net/server/handlers/query/status.rs
ipa-core/src/net/server/handlers/query/step.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs

This is the third of a series of pull requests (PR) to enable sharding on IPA. See #1360 
This change doesn't meaningfully change any tests or the operation of IPA. This is just adding abstractions that are going to be useful later.
Biggest changes are concentrated in `net/transport.rs`. 
`HttpTransport` has now 2 "sub-classes"; Mpc and Shard, each implemented as a composition. E.g.
```
#[derive(Clone)]
pub struct MpcHttpTransport {
inner_transport: Arc<HttpTransport<Helper>>,
}
```
Having `MpcHttpTransport` own the inner Arc simplified the interactions with these HttpTransports since they know how to clone themselves. Shard and MPC HTTP Transports are very similar, hence most of the functionality has been factored inside `HttpTransport`.
`bin/helper.rs` and `net/test.rs` have a few …

[Sharding 3] ConnectionFlavor-aware HttpTransport

---

ipa-core/src/query/runner/hybrid.rs
ipa-core/src/report/hybrid.rs

This adds a new struct, `IndistinguishableHybridReport`, implements `From` for the various `HybridReport` structs, and adds the conversion to the decryption pipeline.

Indistinguishable reports

---

ipa-step-derive/src/lib.rs
ipa-step-test/src/lib.rs

This method essentially returns the unique index associated with the current gate. The plan is to use that number for metrics uniqueness check: they greatly benefit from knowing that the dimension for compact gate is `u64`

Extend the compact gate implementation to provide `index` method

---

ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs
ipa-core/src/query/runner/hybrid.rs

This creates a new function that will take in the indistinguishable reports and compute the hybrid protocol. This PR is just plumming.
It includes a bunch of trait bounds that we also have for the OPRF protocol. Given that we will be using most of the same sub-protocols, I think we'll need them all, but certainly open to feedback here if we think we should add them at a different point.

add hybrid_protocol function, unimplemented

---

ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs

This PR originally removed the chunk override for attribution, but that was observed to impact performance, so now is just revising the comment to accurately describe the situation.

Revise comment about chunk override for attribution

---

DEVELOPMENT.md
ipa-core/src/helpers/buffers/ordering_sender.rs
ipa-core/src/lib.rs
ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/test_fixture/world.rs

Changes to tests and test infrastructure to be able to reproduce test runs from a seed.
This just updates one example of each kind of test I could think of to demonstrate how to achieve reproducibility. There are still many other tests that would need to be updated to match.
Fixes #1321

Seed management to improve reproducibility

---

ipa-core/Cargo.toml
ipa-core/src/bin/helper.rs
ipa-core/src/cli/metric_collector.rs
ipa-core/src/cli/mod.rs
ipa-core/src/cli/verbosity.rs
ipa-core/src/helpers/gateway/send.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/prss.rs
ipa-core/src/protocol/mod.rs
ipa-core/src/sharding.rs
ipa-core/src/telemetry/mod.rs
ipa-core/src/telemetry/stats.rs
ipa-core/src/telemetry/step_stats.rs
ipa-core/src/test_fixture/logging.rs
ipa-core/src/test_fixture/metrics.rs
ipa-step/Cargo.toml
ipa-step/src/descriptive.rs

This is the final PR to upgrade IPA to use new metric engine. This change removes the old metric dependency and updates the code to use new metrics.
This approach was tested in #1278 and the only difference here is that we don't consume metrics yet. #1353 will take care of it

Migrate IPA code to new metrics engine

---

ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/base.rs
ipa-core/src/protocol/ipa_prf/shuffle/malicious.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/sharded.rs
ipa-core/src/query/runner/oprf_ipa.rs
ipa-core/src/secret_sharing/mod.rs

First step towards malicious sharded shuffle. This saves the intermediates from the sharded shuffle, like #1249 did for the unsharded shuffle.

Save intermediates during sharded shuffle

---

ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/step.rs
ipa-core/src/protocol/ipa_prf/oprf_padding/mod.rs
ipa-core/src/report/hybrid.rs
ipa-core/src/secret_sharing/replicated/mod.rs
ipa-core/src/test_fixture/hybrid.rs

This implements the `Paddable` trait for `IndistinguishableHybridReport` so that it can work with `apply_dp_padding`. It also implements `TestIndistinguishableHybridReport` and `Reconstruct` to support the tests.
Note that this is fairly repetitive to the OPRF implementation. If we wanted to keep that around, we'd want to make this more generic, but given our intention is to delete that, it's copied and modified to work directly with  `IndistinguishableHybridReport`.

Hybrid padding

---

ipa-core/src/bin/helper.rs
ipa-core/src/bin/report_collector.rs
ipa-core/src/bin/test_mpc.rs
ipa-core/src/cli/playbook/add.rs
ipa-core/src/cli/playbook/ipa.rs
ipa-core/src/cli/playbook/mod.rs
ipa-core/src/cli/playbook/multiply.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs

Two things happened in here:
1. Removed the default `Helper` for `ConnectionFlavor` in the Http Client. Now you have to be explicit.
2. Renamed `MpcHelperClient` to `IpaHttpClient` since it can handle both Mpc and Shard  communication.

Renaming MpcHelperClient to IpaHttpClient<Helper>

---

ipa-core/src/net/mod.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs

Two things happened in here:
(Server)
1. Removed the default `Helper` for `ConnectionFlavor` in the Http Server. Now you have to be explicit.
2. Renamed `MpcHelperServer` to `IpaHttpServer` since it can handle both Mpc and Shard communication.

Renaming MpcHelperServer to IpaHttpServer<Helper>

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/dp/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/multiplication.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/sigmoid.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs
ipa-core/src/test_fixture/world.rs

This changes a bunch of tests that were upgrading Boolean contexts to MAC-semi-honest to instead use DZKP-semi-honest. An upgrade of some kind became necessary after removing support for MPC primitives from the base context. When that first happened, DZKP upgrades were not ready. Now that DZKP upgrades work, it makes more sense to use them here -- it's unlikely we would want to use MAC security with a Boolean field, because it is significantly more expensive than the DZKPs.
Making this change avoids the need to maintain MAC support for `Boolean`, which was never properly implemented. (When we actually used it, it was with `Gf2`, which is distinct from `Boolean`, for better or worse.)

Remove use of MAC-upgraded contexts with Boolean

---

ipa-core/src/helpers/transport/in_memory/config.rs
ipa-core/src/helpers/transport/in_memory/mod.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/sharding.rs
ipa-core/src/test_fixture/world.rs

This will be used by the tests for malicious sharded shuffle.

Support interception of mpc messages in sharded environment

---

ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs

Now we can start a sharded infrastructure for tests. I'm using the following changes to test the upcoming Query Workflow. I'm front-loading the tests that I will later use to make sure everything keeps working on every PR.
Created the `TestApp` struct which is used to create `HelperApp` by HTTP tests. HTTP Transport tests uses this new struct to spin up the hosts.  
One of the certificates I had uploaded before was wrong so I'm updating it now.
I plan to breakdown `tests.rs` in a later PR, once the changes I have in the backlog are merged.

Adding testing infrastructure to support sharded tests

---

ipa-core/src/net/server/handlers/mod.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/server/handlers/query/prepare.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/transport.rs

Adding the HTTP endpoint for the prepare query API. Modified it so that the same code can be used for either shard/helper communication (both just forward the input to their respective transports).

Prepare HTTP Endoint

---

ipa-core/src/protocol/context/mod.rs
ipa-core/src/telemetry/stats.rs

`std::io::stdout()` is not captured in test runs -- see https://github.com/rust-lang/rust/issues/90785.
The `Display` implementation for `comfy_table::Table` assembles everything into a string anyways (actually worse -- it assembles into a `Vec<String>` and then calls `join`). So, even if we were to have other places where we want the `std::io::Write` interface, there is unlikely to be a performance benefit of the previous implementation.

Suppress metrics table in passing test runs

---

ipa-core/src/ff/curve_points.rs

I noticed that we do quite a bit of compress/decompress operations inside IPA to compute PRF values. For each row we do
Compress:
* 2 operations to convert from `Fp25519` (secret share)
* 2 operations to reveal (reveal requires two additions, each addition is one compress)
* 1 multiplication (on revealed value)
Decompress:
* 4 operations to reveal (two additions, each requires decompressing both RHS and LHS)
* 1 operation to multiply
In total we have 10 and each of those requires an inverse operation which shows up in the profiler as quite expensive. I ran some DRAFT queries on preliminary implementation and it showed ~14% latency drop for storing uncompressed Ristretto points for **semi-honest** implementation. I want to check malicious as well, although there is a bigger issue there, so …

Optimize Ristretto points handling in IPA

---

ipa-core/src/ff/prime_field.rs

Zero-knowledge proofs use multiplication on this field extensively. For every bit of multiplication output, we perform [~10 multiplications](https://github.com/private-attribution/ipa/blob/cf25c69f7c641ed70de62c6536c0293e1e6b2db5/ipa-core/src/protocol/context/dzkp_field.rs#L122) in `Fp61BitPrime`. That's around $86 \times 10^9$ modulo reduction operations per 35 million MPC multiplications.
My preliminary testing shows ~30% improvement in local runs, will do some Draft runs to confirm

Optimized modulo operator for `Fp61BitPrime`

---

ipa-core/src/app.rs
ipa-core/src/bin/helper.rs
ipa-core/src/config.rs
ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/gateway/transport.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/handler.rs
ipa-core/src/helpers/transport/in_memory/config.rs
ipa-core/src/helpers/transport/in_memory/mod.rs
ipa-core/src/helpers/transport/in_memory/sharding.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/error.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/ipa_prf/shuffle/malicious.rs
ipa-core/src/query/processor.rs
ipa-core/src/sharding.rs
ipa-core/src/test_fixture/app.rs
ipa-core/src/test_fixture/world.rs

A few changes required to make Prepare Query API work for the sharded scenario:
1. HandlerRef was generalized to support both `<ShardIndex>` and `<HelperIdentity>`
2. `app::Setup` returns also a `HandlerRef<ShardIndex>` to give to the ShardHttpTransport.
3. Added `ShardTransports` trait. This one provides an additional function to retrieve my shard configuration (`Sharded`). I need shard transports to know how many shards are in total. I will use this functionality in the Prepare Query API (query processor) so that the leader shard can send messages to all other shards. Note there's no Context at this stage, these are the preliminary steps of the query.
4. Created a simple `net::errors::ShardError`. This one only wraps the general net Error with shard information. This is needed by the …

Prepare Query API Plumbing

---

ipa-core/src/error.rs
ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/galois_field.rs
ipa-core/src/protocol/ipa_prf/shuffle/base.rs
ipa-core/src/protocol/ipa_prf/shuffle/malicious.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/sharded.rs

This uses the `Shuffleable` trait (originally added for the semi-honest sharded shuffle) in the base shuffle and malicious shuffle code. Doing so simplifies the trait bounds on many of the shuffle routines.
The bounds on `ShuffleShare` here are similar to but different from `BooleanArray`. I avoid assuming `Copy`, which probably doesn't matter much for the things we shuffle currently, but makes the implementation more extensible to shuffling larger things.
There are also a few other changes. Most notably, I adopt the one-side PRSS generation that was added #1187. I also eliminate some `clone`s and make some other small adjustments / simplifications.

Use Shuffleable traits for all shuffle routines

---

ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/oprf.rs

As requested [here](https://github.com/private-attribution/ipa/pull/1408#issuecomment-2462937702), this is the first of 2 PRs, splitting up #1408, adding the OPRF step to the hybrid protocol.
This only copies over the [IPA OPRF code ](https://github.com/private-attribution/ipa/blob/main/ipa-core/src/protocol/ipa_prf/mod.rs), without modifying it yet. Originally, it was in the `protocol/ipa_prf/mod.rs` file, which contained other stuff as well, so this isn't a complete copy of that file.
cc @cberkhoff

copy ipa oprf code over for use with hybrid

---

ipa-core/src/protocol/prss/crypto.rs

I noticed that rejects_the_same_index fails when running `cargo test -r`. The reason is that it tests UsedSet, which is only enabled when using cfg(debug_assertions). So I added that requirement to the test

[Bugfix] Add debug_assertions requirement to rejects_the_same_index

---

ipa-core/src/helpers/buffers/circular.rs

Multiple tests for CircularBuf rely on matching a panic initiated by `debug_assert!`. However, these tests will fail when we're not in debug mode (such as when running `cargo test -r`), so I added specifiers to the tests that rely on `debug_assert!`.
Alternatively, we could replace the `debug_assert!`s with `assert!`s. I don't have a preference, but we should do one of the two

[Bugfix] Add cfg(debug_assertions) to dependent CircularBuf tests

---

ipa-core/src/helpers/transport/stream/mod.rs

The rejects_large_chunks relies on a panic being initiated by a `debug_assert`, so we should either make it a regular `assert` or limit the test to debug mode

[Bugfix] Add cfg(debug_assertions) to rejects_large_chunks test

---

ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/oprf.rs
ipa-core/src/protocol/hybrid/step.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/report/hybrid.rs

This is stacked on top of #1412, so to look at the just the diff, make sure to ignore the `d1199d1` commit in the diff viewer.
This updates the OPRF function to work with hybrid reports, as well as negotiating a key exchange across shards. Note that that will be replaced by the functionality in #1410 once merged.
It also adds a direct test for this function, which was lacking before.

Hybrid oprf pt2

---

ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/oprf.rs
ipa-core/src/protocol/hybrid/step.rs
ipa-core/src/sharding.rs

This is currently a draft, as it's stacked on top of #1413. For review, you'll want to make sure to just look at the commits after `4db9c544`.
This implements `Serializable` for `PRFIndistinguishableHybridReport<BA8, BA3>`. Offline @akoshelev and I discussed this, and instead of dealing with the complicated trait bounds to implement `Serializable` generically for and `BK, V`, we'd only implement it for the types we actually use. If at some point we decide to use this for a large set of replicated types for breakdown keys and values, we can look into other approaches to implement this more efficiently, like a macro.

Reshard by oprf

---

ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs
ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

rustc didn't optimize the `eval` function and ended up doing
131072*32*992 loop iteration per Lagrange compute.
For some unknown reason to me, optimizer works only if we operate
on integers, not on fields. Maybe modulo reduction is to blame

Lagrange evaluation performance improvements

---

ipa-core/src/app.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/handler.rs
ipa-core/src/helpers/transport/in_memory/sharding.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/query/processor.rs

Added `processor::prepare_helper` and `processor::prepare_shard` to Processor and corresponding tests to validate the correct behavior. Had to add functionality in `InMemoryShardNetwork` to be able to set custom Handlers. Since the amount of testing code in `processor` was getting out of hand I created a few structs to help streamlining them.
Following is a description of the overall approach we want to take for Sharded APIs. 
Query APIs (Create Query, Query Status, etc), the Report Collector (RC) will reach out to the Leader Shards **only**. The diagram above shows how Shard 1-0 receives a Create Query from RC (`processor::new_query`). He validates its own state and then forwards the calls to the other leaders; Shard 2-0 and Shard 3-0, using the `processor::prepare_helper` (blue arrows …

Sharded Prepare Query API

---

ipa-core/src/helpers/buffers/unordered_receiver.rs
ipa-core/src/helpers/cross_shard_prss.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/protocol/prss/crypto.rs
ipa-core/src/protocol/prss/mod.rs
ipa-core/src/protocol/prss/seed.rs
ipa-core/src/sharding.rs
ipa-core/src/test_fixture/world.rs

This protocol will generate random seeds using PRSS and then distribute those seeds to all shards. Every shard will initialize cross-shard PRSS from those seeds. Follows up on #1410.

Implement protocol to create cross-shard coordinated randomness

---

ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/step.rs
ipa-core/src/report/hybrid.rs

much simpler than the last go around, thanks for all the improvements here @andyleiserson!
note that the share type here is less than optimal, but I ran into issues when attempting to build smaller BooleanArrays. I think I have a lead on getting that to work, but it's better addressed in a different PR.

implement Shuffleable for IndistinguishableHybridReport

---

ipa-core/src/protocol/ipa_prf/shuffle/malicious.rs
ipa-core/src/protocol/ipa_prf/shuffle/sharded.rs

The only reason it was there was to be able to use `AdditiveShare` inside malicious shuffle, but it felt too constraining to me. AdditiveShare has a lot of stuff built in and a lot of these are not required for Shuffle and a simple wrapper could to the same trick.
While working on this, I noticed that it gets a bit clunky to use in tests that call `verify_shuffle`. I tried to fix that but it is a much bigger refactoring. The idea was to add more traits supporting maliciuos shuffle. Initially we could consume `MaliciousShuffleable` that could later be upgraded to `MaliciousWithTags` type and bound to the original through `ShuffleWithTag`. That type could expose shares with tags attached. More importantly, it should provide a means to go back to original `MaliciousShuffleable`.
I got half …

Remove SharedValue trait bound from MaliciousShuffleable

---

ipa-core/src/protocol/hybrid/agg.rs
ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/step.rs
ipa-core/src/protocol/ipa_prf/oprf_padding/mod.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/report/hybrid.rs
ipa-core/src/test_fixture/hybrid.rs

This is a draft of implementing `aggregate_reports`, which adds the expected two shares from each match key (dropping any matchkeys without exactly 2 reports.)
The test is incomplete, and it stalls. Presumably this has to do with the malicious validation. Any feedback or pointers to other code that does something similar would be helpful. I was looking at [this implementation](https://github.com/private-attribution/ipa/blob/main/ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs#L501-L548), and admittedly some of the comments there suggest there may be a better way to do this.
Additionally, this doesn't yet utilize vectorization. (cc @andyleiserson). Any feedback or pointers in that direction would also be greatly appreciated.

compiling version of aggregate_reports

---

ipa-core/src/protocol/hybrid/breakdown_reveal.rs
ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/ipa_prf/oprf_padding/mod.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/report/hybrid.rs
ipa-core/src/test_fixture/hybrid.rs
ipa-core/src/test_fixture/sharing.rs

This implements `breakdown_reveal` for hybrid, which covers padding reports, shuffling them, revealing the breakdown key, and then adding the secret shares of the values into histograms.
Note that this is stacked on top of #1444, but in the meantime, you can look just at commit `5dbaa63` to highlight the changes.

Breakdown key reveal

---

.github/workflows/check.yml
ipa-core/src/ff/accumulator.rs
ipa-core/src/ff/boolean.rs
ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/ff/field.rs
ipa-core/src/ff/galois_field.rs
ipa-core/src/ff/mod.rs
ipa-core/src/ff/prime_field.rs
ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs

Create an abstraction for multiply-accumulate and provide an optimized implementation for `Fp61BitPrime`. Currently it is still used only in `lagrange::dot_product`, but it will soon be used in `compute_proof` as well.
This change by itself is not meant to affect performance (up or down), it is meant to encapsulate the optimized implementation so that we don't need similar code working with field internals in both `dot_product` and `compute_proof` (and anywhere else we might use it in the future).
Without the `#[inline]` directives, this seemed to hurt performance in my local testing. After adding the `#[inline]` directives, I do not see a significant performance impact either locally or in draft ([before](https://draft-mpc.vercel.app/query/view/void-job2024-11-19T0059) / …

Create an abstraction for multiply-accumulate

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/hybrid/oprf.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/query/runner/reshard_tag.rs
ipa-core/src/test_fixture/world.rs

This upgrades our tests to use malicious context, and implements a couple necessary traits.
~Unfortunately, two tests are stalling (at least when run locally) after this change. I'm not sure what about this change would cause a stall, especially since it's not all the tests. @akoshelev could you take a look?~
~Stalling tests:~

upgrade hybrid tests to use malicious context

---

ipa-core/src/helpers/cross_shard_prss.rs
ipa-core/src/helpers/gateway/mod.rs
ipa-core/src/helpers/gateway/stall_detection.rs
ipa-core/src/helpers/gateway/transport.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/in_memory/transport.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/prss/mod.rs
ipa-core/src/protocol/step.rs
ipa-core/src/query/executor.rs
ipa-core/src/query/runner/mod.rs
ipa-core/src/query/runner/sharded_shuffle.rs

This does not get it to the end, but it implements the necessary parts to plumb sharded contexts and streams into the sharded shuffle toy protocol.
We still need to test it end-to-end and do some blackbox testing inside transport module, but this work is currently blocked behind changes being made inside the processor

Support sharded shuffle in executor

---

ipa-core/benches/dzkp_convert_prover.rs
ipa-core/src/protocol/context/dzkp_field.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs
ipa-core/src/protocol/ipa_prf/malicious_security/mod.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/validation_protocol/proof_generation.rs
ipa-core/src/protocol/ipa_prf/validation_protocol/validation.rs
ipa-core/src/secret_sharing/vector/transpose.rs

As coded, this change only works when the first recursion has λ = 4. I also have a hacked up version with λ = 8, but it's not as optimized as it could be. For a comparison of the different choices for λ with or without this optimization, see https://github.com/private-attribution/ipa/pull/1440#issuecomment-2480801696.
Unfortunately this change has grown quite large. I may be able to split it up if needed, but I'll also offer the following breakdown of the changes to possibly simplify reviewing:
* In `dzkp_field.rs`:
* Change the verifier routines to use table indices like the prover routines.
* Change the table index generation to write to an output iterator instead of producing a vector that may need to be repacked.
* Some cleanup and renaming.
* In `prover.rs` and `verifier.rs`:
* Add …

Use lookup tables for first proof Lagrange output

---

ipa-core/src/helpers/transport/stream/mod.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/server/handlers/query/step.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/step.rs
ipa-core/src/query/runner/sharded_shuffle.rs

This is not an integration test, but it works all the way through HTTP stack similar to how test multiply works. This proves that Rust server and client code work to handle all interactions between shards and helpers.

Implement e2e sharded shuffle test

---

ipa-core/src/test_fixture/hybrid_event_gen.rs
ipa-core/tests/hybrid.rs

With the hybrid protocol, we only expect at most 1 conversion per impression. We're likely to still have cases where there are unmatched impression or conversions, but (aside from a malicious client), we'll never encounter multiple conversions per impression. The protocol filters out any match key with more than 2 reports associated (assuming it has 1 of each, though that's not confirmable), so event gen should match that case.

update hybrid generator to provide max 1 conversion per impression

---

ipa-core/src/ff/boolean_array.rs
ipa-core/src/protocol/context/dzkp_validator.rs

This makes it usable e.g. for `BA4096`, but I'm not actually adding any large BA types in this PR.

Make the boolean_array_impl_large macro more flexible

---

ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/step.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/test_fixture/hybrid.rs

this adds DP noise to the histogram (only on the leader shard.) it also allows for a proper unit test of hybrid end-to-end.
note there are a few changes to be made after landing #1446.

add dp_for_histogram to hybrid, complete unit test

---

ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs

There's one part of the PRF code that can likely be sped up by using batch inversion of Fp25519. This PR adds a function to call the Scalar batch_invert in curve25519-dalek which can be used here.
The function I wrote is not memory efficient at all because I couldn't figure out how to effectively work with <V as Vectorizable<N>>::Array>. I'd appreciate some suggestions here :)
Using Vecs appears to be necessary as it's part of the dalek batch_invert code. To re-implement that code using arrays, we would need to fork dalek to expose UnpackedScalar and the pack/unpack methods.
Even so, this version appears to be faster:
2M records in 6:12 https://draft-mpc.vercel.app/query/view/sore-deal2024-11-21T1848
4M records in 12:12 https://draft-mpc.vercel.app/query/view/roast-loft2024-11-21T2017 …

add scalar batch invert

---

ipa-core/src/protocol/dp/mod.rs

I was in this file, and realized that we were using both `Replicated` and `AdditiveShare` interchangeably within the same file. This opts for `Replicated` everywhere (though if we prefer `AdditiveShare` everywhere that's a simple change.)

use Replicated for AdditiveShare consistently

---

ipa-core/src/net/client/mod.rs
ipa-core/src/net/error.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/net/server/handlers/mod.rs
ipa-core/src/net/server/handlers/query/mod.rs
ipa-core/src/net/server/handlers/query/status_match.rs
ipa-core/src/net/server/handlers/query/step.rs
ipa-core/src/net/server/mod.rs
ipa-core/src/net/test.rs
ipa-core/src/net/transport.rs
ipa-core/src/query/state.rs

Quite a bit of changes here, mostly because of a need to have test server for shard endpoint.
This endpoint is required for shards to be able to communicate query status updates to each other.

New HTTP handler for query status status requests

---

ipa-core/benches/oneshot/ipa.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/dp/mod.rs
ipa-core/src/protocol/hybrid/breakdown_reveal.rs
ipa-core/src/protocol/hybrid/oprf.rs
ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/test_fixture/world.rs

There is a risk that this will introduce flakiness, if there are tests where the tail of the runtime distribution exceeds the timeout. On the other hand, we know that stalls are a predominant failure mode of our protocols, and a clear failure message is a lot nicer than a test job that hangs until somebody notices and kills it.

Add a timeout to TestWorld

---

ipa-core/Cargo.toml

The signature of `tokio::time::timeout` changed in v1.39 (https://github.com/tokio-rs/tokio/commit/6e845b794d53443c81b33e7dbe2e7bcf58863793), but updating to the latest.
Started a draft run: https://draft-mpc.vercel.app/query/view/feral-flux2024-12-04T0049

Update tokio version

---

ipa-core/src/app.rs
ipa-core/src/bin/helper.rs
ipa-core/src/cli/clientconf.rs
ipa-core/src/cli/config_parse.rs
ipa-core/src/cli/test_setup.rs
ipa-core/src/config.rs
ipa-core/src/net/test.rs
ipa-core/src/protocol/hybrid/agg.rs
ipa-core/src/query/processor.rs
ipa-core/src/sharding.rs
ipa-core/tests/common/mod.rs
ipa-core/tests/helper_networks.rs

This builds on top #1473 and only adds [this commit](https://github.com/private-attribution/ipa/commit/afa5c7273bcebc0591d841539a6cd377bd8ed764)
This takes the simplest approach of overwriting the key files after
creating them. Unfortunately there is no easy way to test this without
writing a new protocol, so we'll wait until Hybrid comes into play.
In the meantime I tested it manually to make sure files get overwritten
```bash
running 1 test
generating configuration for 3 shards in /var/folders/n2/wgkrrbd57173j9dvy8bdjcvw0000gn/T/.tmpCMhgQb
...
❯ cmp /var/folders/n2/wgkrrbd57173j9dvy8bdjcvw0000gn/T/.tmpCMhgQb/shard0/h1_mk.key /var/folders/n2/wgkrrbd57173j9dvy8bdjcvw0000gn/T/.tmpCMhgQb/shard1/h1_mk.key
❯ cmp /var/folders/n2/wgkrrbd57173j9dvy8bdjcvw0000gn/T/.tmpCMhgQb/shard0/h1_mk.key …
```

Use one set of encryption keys on all shards for match key encryption

---

.github/workflows/check.yml
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/hybrid/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/test_fixture/mod.rs
ipa-core/src/test_fixture/world.rs

And some general proptest cleanup and improvements. Run longer versions of the MPC proptests when EXEC_SLOW_TESTS is set.
Prompted by #1463.

Add proptest for breakdown-reveal aggregation

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/bin/test_mpc.rs
ipa-core/src/cli/playbook/hybrid.rs
ipa-core/src/cli/playbook/mod.rs

turns out a bunch of these functions aren't actually OprfIpa specific. I did one small "hack" to convert `HybridQueryParams` into `IpaQueryConfig` (it's just a super set and the extra fields are unused at this point) to avoid copying and pasting the entire `run_query_and_validate` function.
This is mostly complete, but we'll need to swap in `HTTPS` clients instead of `HTTP`, so we're blocked on that, cc @akoshelev

add CLI command to run hybrid query

---

ipa-core/src/bin/crypto_util.rs
ipa-core/src/cli/crypto/hybrid_decrypt.rs
ipa-core/src/cli/crypto/hybrid_encrypt.rs
ipa-core/src/cli/crypto/mod.rs

I'm going to tidy this up in a bit, but the functionality is there I believe. Let me know if I missed something important

Add Hybrid Encryption/Decryption to CLI

---

ipa-core/src/cli/playbook/mod.rs
ipa-core/src/cli/playbook/streaming.rs

This change does not integrate streaming into report collector yet as we're not quite ready for it. But it provides a means to split a `BufRead` interface into `M` streams that read from it one at a time. This should not require reading the entire file in memory in order to submit it.
There are a few things that I decided not to bring in the first version:
* Reading from a file can be done in async runtime using `AsyncRead` interface. The benefit of it is not clear to me atm.
* reading more than one line at a time. We could support reading lets say 8kb chunks from file and then let HTTP streams to stream it out.

Support streaming inputs in CLI tooling

---

ipa-core/Cargo.toml
ipa-core/src/bin/crypto_util.rs
ipa-core/src/bin/report_collector.rs
ipa-core/src/cli/crypto/encrypt.rs
ipa-core/src/cli/crypto/hybrid_encrypt.rs
ipa-core/src/config.rs
ipa-core/src/hpke/registry.rs
ipa-core/src/report/hybrid.rs

There were quite a few bottlenecks here:
* Writes were done serially, writing one file at a time.
* Shares were encrypted on a single CPU core
I almost used `rayon` to parallelize encryption, but the problem is that we need to get the output sorted to maintain total order across files. Rayon can do that, but requires collecting `ParallelIterator` which would be bad for generating 100M+ reports.
Our goal is to be able to share and encrypt 1B, so streaming and manual fiddling with thread pools is justified imo.
The way this CLI works right now: it keeps a compute pool for encryption (thread-per-core) and a separate pool of 3 threads to write data for each helper in parallel
I also made a few tweaks to improve code re-usability in this module.
Time it takes to encrypt 1M reports done locally …

Improve performance of hybrid encrypt CLI

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/query/runner/hybrid.rs
ipa-core/src/secret_sharing/vector/transpose.rs

As we scale up to 1B rows, the saturated_add results in all histogram values saturating at `2^16 - 1` (e.g. `65_535`) with `BA16`. Increasing this to `BA32` will move the saturation point up to `4_294_967_295`. 
Our current data generator has a 20% match rate. With a max_value of 7 (and thus expected value of 3.5), we'd expect histograms to have values around `(1B * 0.2 * 3.5) / 256 = 2_734_375`, safely under the saturation point.

use BA32 instead of BA16 for hybrid histogram values

---

ipa-core/src/bin/in_the_clear.rs
ipa-core/src/test_fixture/hybrid.rs

This operation was OOMing on 500M inputs
```
memory allocation of 73551314960 bytes failed
Aborted
```
The reason for that was that we were keeping all the information from original reports, including AAD and match key. 
The improved algorithm only keeps breakdown keys and values to perform attribution.
My back of the envelope calculation says that this improvement is enough to get us to 1 billion reports. Each entry would take ~8 bytes and for 1B entries we are looking at 8Gb memory consumption which should be doable
I ran it on 500M and it finished successfully.

Improve memory usage for computing hybrid results in the clear

---

ipa-core/src/query/processor.rs

We may be observing issues trying to run Hybrid at scale that are not visible to us due to the nature how query status handles those. If error is not a mismatch, it is just silently ignored. This could lead to a variety of problems - most importantly it will mask the failures and made other shards think that everything is OK, and they can proceed with finalizing results.
This PR changes this and makes this API return an error if there is at least one error that is not a status mismatch. If all of them are, the behaviour is the same as before

Don't ignore errors on query status API

---

ipa-core/src/query/runner/hybrid.rs

Adds a `seq_join` and `async_move` to the shard code operating on encrypted report streams to make decryption parallelizable. 
To make sure it is in fact running in multiple cores, I added a print line to the lambda that calls the decrypt function and tested with the multi-threading feature
`cargo test --package ipa-core --test hybrid --no-default-features --features "cli compact-gate web-app real-world-infra test-fixture relaxed-dp multi-threading" -- test_hybrid --exact`
Example output: 
```
thread id: Thread { id: ThreadId(12), name: Some("query-executor"), .. }
thread id: Thread { id: ThreadId(8), name: Some("query-executor"), .. }
thread id: Thread { id: ThreadId(8), name: Some("query-executor"), .. }
thread id: Thread { id: ThreadId(9), name: Some("query-executor"), .. }
thread id: …
```

Multithreaded Encryption

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/cli/playbook/hybrid.rs

To test this, I added `.args(["--set-fixed-polling-ms", "100"])` before line 93 in the file containing `test_hybrid()`. I also verified that it fails with bad arguments
Test ran with `cargo test --package ipa-core --test hybrid --no-default-features --features "cli compact-gate web-app real-world-infra test-fixture relaxed-dp multi-threading" -- test_hybrid --exact`
I should say this usually passes... I ran it once (with the argument specified) and got
```
Unable to create query!: FailedHttpRequest { dest: "localhost:64473", status: 500, reason: "500 Internal Server Error: One or more peers rejected the request: [(ShardIndex(3), ShardError { shard_index: ShardIndex(0), source: ConnectError { dest: \"localhost:64493\", inner: hyper_util::client::legacy::Error(Connect, Custom { kind: Other, …
```

Add Fixed-Rate Polling Specifier To ReportCollector

---

ipa-core/Cargo.toml

Abort on panics

---

ipa-core/src/cli/verbosity.rs
ipa-core/tests/common/mod.rs
ipa-core/tests/helper_networks.rs

We need it because stderr is often dropped by the external services (like Kubernetes)
This also adds some verification for our e2e tests to make sure we write something into them

Add an option to put helper logs into a file

---

ipa-core/src/query/runner/hybrid.rs

We previously used unwrap before the protocol was complete (and caught the panic in the test). Now that we don't expect this to panic, we should use `?`.

swap unwrap with ?

---

Cargo.toml
ipa-core/Cargo.toml

This must be specified in workplace Cargo as it was pointed in the warning

Fix Cargo.toml for panic=abort

---

ipa-core/src/protocol/hybrid/oprf.rs

In this case the adjustment reduces active_work from 32,768 to 256. Using the larger value results in many proofs being active concurrently.
Draft run: https://draft-mpc.vercel.app/query/view/pied-salon2024-12-14T1951

Use validator-adjusted active work for seq_join

---

ipa-core/src/helpers/transport/stream/buffered.rs
ipa-core/src/helpers/transport/stream/mod.rs

The need for it is driven by the behavior we're observing from Report Collector sending bytes down to individual shards. It writes data as it becomes available and Hyper does not accumulate it before sending. On the receiver side we are seeing chunks of size 1 received and that creates thrashing on sender/receiver side.
This change paves the path to use buffering on RC side.

Create a buffered wrapper around BytesStream

---

ipa-core/Cargo.toml
ipa-core/benches/oneshot/ipa.rs
ipa-core/build.rs
ipa-core/src/bin/helper.rs

jemalloc is used by default on linux. The feature enables it on non-linux platforms.
The `stats` feature is enabled by default on version 0.5 of the `tikv-jemalloc-ctl` crate. It needs to be specified on version 0.6 of the crate. I figured might as well upgrade the jemalloc bits now, when I'm aware of the breaking change, than have to remember (or somebody else rediscover) it later.
The jemalloc profiling enables are a bit confusing. This PR does not have all of the config that I set to do memory profiling. My intent was to have it compiled-in-but disabled, but I'm not sure that's actually what this PR does. I will do a draft run to check whether there is a performance impact.

Upgrade jemalloc to 0.6; add jemalloc feature

---

ipa-core/Cargo.toml
ipa-core/src/app.rs
ipa-core/src/bin/test_mpc.rs
ipa-core/src/cli/playbook/add.rs
ipa-core/src/cli/playbook/hybrid.rs
ipa-core/src/cli/playbook/ipa.rs
ipa-core/src/cli/playbook/multiply.rs
ipa-core/src/cli/playbook/sharded_shuffle.rs
ipa-core/src/helpers/transport/query/mod.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/http_serde.rs
ipa-core/src/net/mod.rs
ipa-core/src/net/query_input.rs
ipa-core/src/net/server/handlers/query/input.rs
ipa-core/src/net/transport.rs
ipa-core/src/query/processor.rs
ipa-core/src/query/state.rs
ipa-core/src/test_fixture/app.rs

Support for helper to pull query input from a URL, rather than receiving it directly from the client in an HTTP request body.
Also adds a simple HTTP server in test_mpc to serve local files, for testing purposes.

Query input from URL

---

ipa-core/src/cli/crypto/hybrid_decrypt.rs
ipa-core/src/cli/crypto/hybrid_encrypt.rs
ipa-core/src/cli/crypto/mod.rs

In order to support the new ability for helpers to load data from a file/url, we need the ability to produce length delimited encrypted data for testing. This adds a flag to the `crypto_util` called `--length-delimited` which will produce length delimited binary instead of newline delimited hex.
The next step is to use this with the integration test. The flow will be
1. generate raw input data files (one for each shard)
2. use `crypto_util` to encrypt each of these for each shard (and each helper)
3. pass these files into the report collector (is this implemented yet @akoshelev ?)
4. cat all input data files together and run `in-the-clear`
5. compare results

add flag to encrypt_util for length delimited binary format

---

ipa-core/src/net/error.rs
ipa-core/src/net/query_input.rs
ipa-core/src/net/server/handlers/query/input.rs

Enforcement of `https_only` in `hyper-rustls` had been broken 🫠 and was fixed in the past ~24 hours.
I don't really think it's a good idea to allow http here, but for expediency, I did intend to use it when I made the change. I guess my better self wrote `https_only` despite my intentions. I will file an issue about disallowing http (which is mostly a pain because it will require generating certificates for the test).

Fix input_from_url test

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/cli/playbook/hybrid.rs
ipa-core/tests/hybrid.rs

This builds on top #1509 and #1508 and supports polling for inputs mode on the report collector side and adds an integration test to verify correctness of this setup end-to-end.
Test passes, so it seems we are quite close

Support Query input from URL on report collector side + integration test

---

ipa-core/benches/oneshot/ipa.rs
ipa-core/src/bin/helper.rs
ipa-core/src/lib.rs
ipa-core/src/seq_join/local.rs
ipa-core/src/seq_join/multi_thread.rs
ipa-core/src/telemetry/memory.rs
ipa-core/src/telemetry/mod.rs

The reporting is wired into seq_join. The reporting interval increases as the record count increases, which results in a tolerable amount of log messages for loops with many iterations, while still providing some reporting for shorter loops. It's still fairly chatty, so I put it at debug level. [Here's a sample](https://github.com/user-attachments/files/18159269/memory-reporting-sample.txt) -- 1141 lines reporting memory usage vs. 583 other log lines -- but I reduced the frequency after generating this, so it's ~half of that now.
Note that the reporting depends on jemalloc. That is the default on linux. It can be activated on other platforms with a feature.

Periodically report memory usage

---

ipa-core/src/protocol/hybrid/breakdown_reveal.rs
ipa-core/src/protocol/hybrid/mod.rs
ipa-core/src/protocol/hybrid/oprf.rs
ipa-core/src/protocol/hybrid/step.rs
ipa-core/src/protocol/ipa_prf/shuffle/malicious.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/step.rs
ipa-core/src/query/runner/hybrid.rs

It turns out, we've never used sharded shuffle in Hybrid, running local shuffles (per shard) instead. This change fixes that.
Also, drop `Shuffle` implementation for sharded contexts to prevent this from happening again.
Using sharded shuffle costs about 20% in terms of latency, according to the latest benchmarks. 
with sharded shuffle - **64 min** for 1B rows
without sharded shuffle - **53 min** for 1B rows
This change also contains a small fix for PRF - to use a resharding step that we forgot to use as well.

Use sharded shuffle in Hybrid 

---

ipa-core/src/protocol/dp/mod.rs
ipa-core/src/protocol/hybrid/breakdown_reveal.rs

These tests timed out in https://github.com/private-attribution/ipa/actions/runs/12439153477/job/34732429420.

Increase a couple test timeouts

---

ipa-core/src/bin/report_collector.rs
ipa-core/src/cli/playbook/mod.rs
ipa-core/src/cli/playbook/streaming.rs
ipa-core/src/helpers/mod.rs
ipa-core/src/helpers/transport/mod.rs
ipa-core/src/helpers/transport/stream/buffered.rs
ipa-core/src/helpers/transport/stream/mod.rs

Continuation of #1501, we want to avoid submitting reports one by one from RC to each individual shard. That likely leads to fragmentation and we've been observing slow execution on the client side.
This sets up the buffer size to be divisible by TCP MSS, but I don't have any real evidence that this is going to work well. We would need to experiment with it

Use stream buffering in report collector

---

.github/workflows/audit.yml
.github/workflows/check.yml
ipa-core/src/protocol/hybrid/breakdown_reveal.rs

Also add rust toolchain version to cache key.

Update workflows for ubuntu 24.04 runners

---

.github/workflows/audit.yml
ipa-core/Cargo.toml
ipa-core/src/cli/keygen.rs

* Grant additional permissions to the job
* Update rcgen to 0.13
* Waive several vulnerabilities that are not critical and cannot immediately be fixed. Tracked by #1527.

Fixes for security audit

---

.github/workflows/audit.yml

https://rustsec.org/advisories/RUSTSEC-2025-0014
> This advisory has been withdrawn and should be ignored. It is kept only for reference.
https://github.com/tailhook/humantime/issues/31

Remove RUSTSEC-2025-0014 audit lint suppression

---

ipa-core/Cargo.toml

Failures started to pop up recently:
https://github.com/private-attribution/ipa/actions/runs/13868880764/job/38812864191?pr=1529
I couldn't figure out what caused this. I suspect one of our dependencies stopped using `util` feature from Tower and didn't mark that change as breaking. I checked Axum change log, but couldn't find anything.
Either way, this fixes it and I also bumped up tower dependency version to the latest

Fix build failures
