private-attribution/ipa

.github/workflows/check.yml

This runs a build, tests, formatting, and clippy checks.
I'm using clippy::pedantic, which is pretty aggressive about some
things, but it is pretty helpful at picking up common programming
errors.

Add a GitHub Action to check code

---

raw-ipa-lib/src/helpers/aggregation.rs
raw-ipa-lib/src/helpers/event.rs
raw-ipa-lib/src/user.rs

Stack overflow delivers yet again

Pretty print JSON

---

raw-ipa-cli/src/lib.rs
raw-ipa-cli/src/stringn.rs
raw-ipa-lib/src/user.rs
raw-ipa-ua/src/main.rs

Also, add the hashing of the provider name into the matchkey ingest.

Allow the matchkey to be any string

---

raw-ipa-lib/src/helpers/event.rs
raw-ipa-lib/src/lib.rs
raw-ipa-lib/src/report.rs
raw-ipa-lib/src/user.rs

Created two structs - meant to encapsulate event reports, with a new function on the User struct to generate a report, and a function on the Helper struct to partially decrypt a report. For now reports only consist of a set of encrypted match keys. We will add the secret shares later.

Adding a function to encrypt multiple matchkeys

---

.github/workflows/check.yml
Cargo.toml
src/error.rs
src/helpers/mod.rs
src/helpers/privacy_budget.rs

It expects a vector of encrypted blobs alongwith budget to be consumed.
After increasing the budget consumed by all the blobs, it returns blobs which are below TOTAL_PRIVACY_BUDGET

This module implements privacy budget using a redis cache

---

src/helpers/privacy_budget.rs

Currently these are failing on local machine due to missing redis server installation. Will be creating a separate diff to handle that

Ignoring tests from privacy budget for now

---

src/replicated_secret_sharing.rs

In this rev, only supports addition, subtraction and multiplication by a constant

Adding a ReplicatedSecretSharing implementation

---

src/field.rs

These implementations are generic enough to be defined for any field, but they require some additional bounds on `Self::Integer` to be able to subtract, right shift and determine the size in bits of the underlying type

Field: move `pow` and `invert` to the trait def.

---

.gitattributes
research-prototype/.gitignore
research-prototype/Programs/Source/ipae2e.mpc
research-prototype/README.md
research-prototype/ipainput.py

Currently only merging this in as a branch so we can work on it. cc @martinthomson @benjaminsavage @bmcase

add mp-spdz prototype, data generator, and readme

---

.github/workflows/check.yml
pre-commit
pyproject.toml

adding in python formatting tools, supporting #54

add pre-commit and github action for python formatting. includes .mpc files

---

.github/workflows/check.yml
scripts/start-helpers.py

for some reason, the main branch has a failing github workflow around python linting. this resolves that issue, as well as breaks up the workflow for rust/python CI

Python linting fix

---

research-prototype/README.md

* Format code blocks as bash scripts
* Add instructions how to run MPC on multiple hosts

research-prototype: update readme

---

.github/workflows/check.yml
Cargo.toml
pyproject.toml
src/error.rs

* Remove Redis dependency
* Reorder some Github actions to get feedback faster

Sanitize Github actions config

---

src/protocol/sort/apply.rs
src/protocol/sort/bit_permutations.rs
src/protocol/sort/reshare.rs
src/protocol/sort/reveal.rs
src/protocol/sort/shuffle.rs

There are a few issues in the uploaded doc images not being rendered. This PR takes care of that. However, I am able to run cargo doc and see the comments in a very incosistent manner. Sometimes it shows up and sometimes it doesn't.

Fix errors while running cargo doc

---

Cargo.toml

Yep, [it turns out we needed it](https://github.com/martinthomson/raw-ipa/pull/107#issuecomment-1272649289).

rand_core is back!

---

src/protocol/modulus_conversion/convert_shares.rs
src/protocol/reveal_additive_binary.rs

Thank you @thurstonsand for your suggestions! These suggestions make the code much cleaner looking.

Code improvements

---

CONTRIBUTING.md
README.md

This is all very drafty and I'm definitely not a lawyer, but hopefully this is enough to start with.

Update the README and add CONTRIBUTING

---

src/protocol/context.rs
src/protocol/mod.rs
src/protocol/prss.rs
src/protocol/securemul.rs
src/protocol/sort/shuffle.rs
src/test_fixture/mod.rs
src/test_fixture/world.rs

I think that these names are better.  Outside of the module, there isn't much that changes.

PRSS cleanup

---

src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/prss.rs
src/protocol/securemul.rs
src/protocol/sort/reshare.rs

Because we really don't care and this makes writing the code easier.

Accept anything that converts into u128 as an index

---

src/protocol/check_zero.rs
src/protocol/context.rs
src/protocol/mod.rs
src/protocol/prss.rs
src/protocol/reveal.rs

This is needed later on to upgrade to malicious security

Implementing the Check Zero protocol

---

src/protocol/securemul.rs
src/protocol/sort/shuffle.rs

Some trivial stuff based on Thurston's feedback.

Cleanup some of the step management stuff

---

.github/workflows/check.yml

Reverts private-attribution/ipa#155
We can't get it working for now

Revert "Update the CI checks"

---

src/error.rs
src/protocol/malicious.rs
src/protocol/mod.rs
src/secret_sharing/mod.rs
src/secret_sharing/replicated.rs

This class must be informed about all the inputs to an arithmetic circuit, informed about each multiplication (or reshare) that happens, and asked to `validate()` at the end of the circuit.

Implementing the malicious security validator

---

src/protocol/modulus_conversion/specialized_mul.rs
src/protocol/reveal.rs
src/protocol/securemul.rs
src/protocol/sort/reshare.rs

#159 made all of this dead code - but somehow it was not detected as such. This PR just removes it all.

Removing dead code

---

src/protocol/modulus_conversion/convert_shares.rs

@richajaindce - this might be helpful to you in #186

adding method to convert just one bit

---

src/error.rs
src/protocol/reveal.rs
src/protocol/reveal_additive_binary.rs

...and tests for both successful and unsuccessful cases

Adding a Malicious Reveal protocol

---

src/protocol/sort/apply.rs

This just seems slightly better to me.

Tiny change

---

src/protocol/modulus_conversion/convert_shares.rs
src/protocol/modulus_conversion/double_random.rs

Daniel Masny pointed out that the share conversion protocol we had been using was optimized for pushing work into the "offline" phase. In this case, we don't gain any benefit from an "offline" phase, since we are trying to just minimize the total computation cost and latency is not as critical. If we just push it all to the "online" phase, there is actually less communication this way.

Simplifying share conversion

---

src/protocol/boolean/bitwise_lt.rs

Addressing comments from #206.
* Added new tests cases to test `BitwiseLessThan` protocol with `Fp32BitPrime`
* Refactor test helper functions to be generic over `F`, and simplify types/signatures

New test cases to test BitwiseLessThan with Fp32BitPrime

---

src/protocol/mul/semi_honest.rs

make this test a bit better

---

benches/oneshot/sort.rs
src/protocol/context.rs
src/protocol/context_traits.rs
src/protocol/malicious.rs
src/protocol/mod.rs
src/protocol/mul/malicious.rs
src/protocol/reveal/mod.rs
src/protocol/sort/bit_permutation.rs
src/protocol/sort/generate_sort_permutation.rs
src/secret_sharing/mod.rs
src/test_fixture/mod.rs
src/test_fixture/sharing.rs

Gen bit perm for Semi honest and malicious setting

---

src/protocol/mul/malicious.rs
src/protocol/sort/bit_permutation.rs

very small fix

---

src/helpers/buffers/fsv.rs
src/helpers/buffers/send.rs
src/helpers/messaging.rs

Simpler FSV

---

src/protocol/mul/semi_honest.rs
src/test_fixture/mod.rs
src/test_fixture/sharing.rs
src/test_fixture/world.rs

This builds on #253.  View the last commit only.

Simplify test

---

Cargo.toml
src/bin/ipa_bench/gen_events.rs
src/protocol/prss.rs

Fewer dependencies is better, right?

Remove byteorder crate

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/mod.rs
src/protocol/mod.rs

* Make `AccumulateCredit` struct signatures align with other protocols.
* Remove `IterStep`
* Rename values/structs

Refactor AccumulateCredit

---

src/protocol/attribution/accumulate_credit.rs

I hope this makes the test case a bit easier to read.
This unit test still doesn't use `world.semi_honest()` since that requires a bit more complex `IntoShares` logic. I'll try to work on it when I finish other high-pri tasks.

Small improvement to the attribution test case readability

---

src/protocol/attribution/accumulate_credit.rs

* Renamed `Fp31AttributionInputRow` to `AttributionTestInput`, and made it generic over `F`
* Move to the new framework!

Move AccumulateCredit tests to the new test framework

---

src/protocol/boolean/bitwise_less_than_prime.rs

Splitting out the changes to just one file from #309

Making BitwiseLessThanPrime maliciously secure

---

src/protocol/boolean/solved_bits.rs

one more tiny step

---

src/protocol/attribution/mod.rs

If Else use generics

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs
src/protocol/mod.rs

This was starting to get a little tiresome.

Add a macro for repeating strings 64 times

---

src/protocol/context/mod.rs
src/protocol/sort/apply_sort/shuffle.rs

Impl Researable for Vec<Replicated<F>>

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs

Small refactoring

---

src/protocol/attribution/aggregate_credit.rs

Fix step names

---

src/helpers/http/mod.rs

Two PRs (#288 and #339) collided resulting in broken main

Fix IntoShares import

---

src/protocol/basics/mod.rs
src/protocol/basics/sum_of_product/malicious.rs
src/protocol/basics/sum_of_product/mod.rs
src/protocol/basics/sum_of_product/semi_honest.rs

This will be needed for GenMultiBitPerm: https://docs.google.com/document/d/1DbMVkBf2n4LkdHKg4Q5pHFxbvCSA8oR63sx16qRPfp0/edit?usp=sharing

Sum of products implementation

---

src/helpers/buffers/mod.rs
src/helpers/buffers/receive.rs
src/net/client/mod.rs
src/net/server/handlers/query.rs
src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/basics/check_zero.rs
src/protocol/basics/reshare.rs
src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/bitwise_less_than_prime.rs
src/protocol/ipa/mod.rs
src/protocol/malicious.rs
src/protocol/sort/apply.rs
src/test_fixture/network.rs
src/test_fixture/sharing.rs

Clippy recently updated, and revealed [a few new things](https://github.com/private-attribution/ipa/actions/runs/3706797462/jobs/6282448753#step:7:16) it wanted us to change in the code. With this PR, our CI will pass again

Make latest version of clippy happy

---

src/bits/bit_array.rs
src/bits/mod.rs
src/ff/field.rs
src/ff/mod.rs
src/ff/prime_field.rs

Move arithmetic-ops bounds into its own trait, and have all fields implement it.

Fields implement `ArithmeticOps`

---

src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/boolean/bit_decomposition.rs
src/protocol/boolean/mod.rs
src/protocol/boolean/random_bits_generator.rs
src/protocol/boolean/solved_bits.rs
src/secret_sharing/malicious_replicated.rs
src/secret_sharing/mod.rs
src/test_fixture/sharing.rs

This won't get to the real problem we're dealing with here, but it should avoid most of the overhead in tests.

Simplify the random bits generator

---

src/chunkscan.rs
src/helpers/network.rs
src/helpers/transport/mod.rs
src/protocol/basics/sum_of_product/malicious.rs
src/protocol/basics/sum_of_product/mod.rs
src/protocol/basics/sum_of_product/semi_honest.rs

- Also includes minor changes to handle cargo doc errors

Refactoring sum of product to take a pair instead of vector of a's and b's

---

src/protocol/sort/multi_bit_permutation.rs

I had accidentally done the opposite
Thanks Alex for the improvement AND also helping uncover this issue!

[Multi Gen Bit Perm] Minor improvement and flipping the order of inputs to start from lsb to msb

---

src/protocol/sort/apply_sort/mod.rs
src/protocol/sort/secureapplyinv.rs

This is a building block to support multi bit permutation to work on multi bit slices at a time

Secure apply inv now works on multi bits

---

src/protocol/basics/sum_of_product/malicious.rs
src/protocol/basics/sum_of_product/mod.rs
src/protocol/basics/sum_of_product/semi_honest.rs
src/protocol/sort/multi_bit_permutation.rs

This is an attempt to address issue #403. I don't like it. There's a lot of duplicate code here.

Attempt to remove needless iterators

---

Cargo.toml
src/bits/mod.rs
src/crypto/hpke/aad.rs
src/crypto/hpke/mod.rs
src/crypto/hpke/registry.rs
src/crypto/mod.rs
src/ff/field.rs
src/ff/prime_field.rs
src/helpers/buffers/ordering_mpsc.rs
src/helpers/http/prss_exchange_protocol.rs
src/helpers/messaging.rs
src/lib.rs
src/secret_sharing/mod.rs
src/secret_sharing/xor.rs

This commit provides basic HPKE functionality to decrypt match keys encrypted on UA side according with https://github.com/patcg-individual-drafts/ipa/pull/31.

HPKE for match key encryption

---

src/protocol/ipa/mod.rs

This test ensures our communication cost as number of records sent does not go up accidentally.

IPA communication baseline test

---

src/protocol/boolean/bitwise_gt_constant.rs

* Removed one vector allocation by combining the neighboring bits subtraction with the prefix-or step
* Removed one `reverse()` operation by using `rev()` iteration

Reduce the memory footprint in `bitwise_gt_constant`

---

src/protocol/ipa/mod.rs

Now that we have a (work in progress) malicious IPA implementation, let's establish a benchmark for communication there as well.

Establishing a baseline for communication in malicious IPA

---

src/protocol/attribution/accumulate_credit.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/credit_capping.rs
src/protocol/attribution/mod.rs

merging in latest changes from main

Merge main (once again)

---

src/hpke/info.rs
src/hpke/mod.rs

It addresses the updates in the proposal https://github.com/patcg-individual-drafts/ipa/pull/31/ and IPA issue #492

Update HPKE encryption of match keys

---

src/protocol/attribution/mod.rs
src/protocol/ipa/mod.rs

Stop bits are used in the next iteration. No sense generating more than will be used in the next iteration.

Stop computing unused stop bits

---

src/protocol/attribution/aggregate_credit.rs
src/protocol/ipa/mod.rs

Same approach as #504 - but extended to the `malicious_aggregate` variant as well.

Malicious aggregate optimized

---

benches/oneshot/ipa.rs
src/protocol/ipa/mod.rs
src/test_fixture/ipa.rs
src/test_fixture/mod.rs

This test runs for query size = NUM_USERS * MAX_RECORDS_PER_USER as compared to earlier one which ran for a BATCHSIZE.

[IPA oneshot test] Previous test did not validate the results were same as expected.

---

in-market-test/helper-nodes/setup_instructions.md

Adding some instructions which will be useful for helper nodes to start preparing for the upcoming test

helper-node-instructions

---

src/bits/fp2_array.rs
src/bits/mod.rs

See the super long comment =).
Eventually, this will be used as an "Extension Field" to be able to operate on arithmetic circuits in F2, with any security parameter we choose, as outlined in https://eprint.iacr.org/2019/386.pdf

Adding an implementation of multiply for Bit Array

---

benches/oneshot/sort.rs
src/bits/fp2_array.rs
src/bits/mod.rs
src/cli/playbook/input.rs
src/cli/playbook/ipa.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/attribution/input.rs
src/protocol/attribution/malicious.rs
src/protocol/attribution/semi_honest.rs
src/protocol/basics/share_known_value.rs
src/protocol/boolean/generate_random_bits/mod.rs
src/protocol/ipa/mod.rs
src/protocol/modulus_conversion/convert_shares.rs
src/protocol/sort/apply_sort/mod.rs
src/protocol/sort/apply_sort/shuffle.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/generate_permutation_opt.rs
src/query/executor.rs
src/query/processor.rs
src/secret_sharing/into_shares.rs
src/secret_sharing/replicated/semi_honest/xor_share.rs
src/secret_sharing/scheme.rs
src/test_fixture/input/mod.rs
src/test_fixture/input/sharing.rs
src/test_fixture/ipa.rs
src/test_fixture/sharing.rs

Fp2Array isn't really that anymore. Now that we have added an implementation of "multiply" that actually defines a field, it's better to call it what it is, a GaloisField.

Galois field 2

---

benches/oneshot/arithmetic_circuit.rs
src/ff/field.rs
src/ff/galois_field.rs
src/ff/mod.rs
src/ff/prime_field.rs
src/protocol/attribution/aggregate_credit.rs
src/protocol/sort/generate_permutation.rs
src/protocol/sort/generate_permutation_opt.rs
src/secret_sharing/mod.rs

Commandeering @andyleiserson 's #545 plus a bit more refactoring/renaming/cleanup. Thanks Andy!

make GaloisField a subtype of Field

---

src/protocol/attribution/credit_capping.rs

Noticed that this method needlessly processes input rows one-by-one while working on new Infra. It is not possible to set up buffering correctly for it, so I decided to make it process inputs in parallel.

Parallel processing inside credit capping `compute_final_credits`

---

src/protocol/context/malicious.rs

There is no reason not to run these computations in parallel. This might help our flamegraph show less time in malicious upgrade.

Parallelize Better

---

benches/oneshot/ipa.rs
src/test_fixture/ipa.rs

Makes it easier to choose semi-honest vs malicious IPA

Add security mode parameter to IPA benchmark

---

src/helpers/transport/mod.rs
src/protocol/basics/mul/semi_honest.rs

See #587 for motivation on the `send` contract change

Code cleanup

---

src/protocol/attribution/mod.rs
src/protocol/basics/if_else.rs
src/protocol/basics/mod.rs

This is a pretty generic function and it belongs here.

Move if_else to basics

---

benches/oneshot/ipa.rs
src/protocol/ipa/mod.rs
src/test_fixture/ipa.rs

This will be used inside `test_mpc` binary to validate the results returned from MPC helpers.

Add a function that executes IPA in the clear

---

Cargo.toml
src/bin/helper.rs
tests/helper_networks.rs

Fixes #648
Merge may need to be coordinated with #647.

Use available ports for integration tests

---

src/query/runner/ipa.rs

and fix the compilation errors to make it runnable again

Make IPA runner tests runnable by cargo test again

---

src/hpke/info.rs
src/hpke/mod.rs
src/lib.rs
src/protocol/modulus_conversion/convert_shares.rs
src/query/runner/ipa.rs
src/report.rs

Some related notes and discussion here: https://docs.google.com/document/d/1SXt0OEH7GMd8xvYdpzbcUJrvUaBLkYezKdRUPN7CkGo/edit

Types for input reports

---

src/bin/test_mpc.rs

Output: 
test_mpc: IpaQueryConfig { per_user_credit_cap: 5, max_breakdown_key: 20, attribution_window_seconds: Some(10), num_multi_bits: 3, plaintext_match_keys: false } IPA for 5000 records took 73.187223057s

Print the query config, query size and time taken when report collector runs a query

---

Cargo.toml
src/bin/helper.rs
src/net/client/mod.rs
src/net/server/mod.rs
src/net/test.rs

Remove hyper-tls and replace it with hyper-rustls

---

.github/workflows/docker.yml

See https://github.com/private-attribution/ipa/issues/691#issuecomment-1601641673

Use a context for building the docker image

---

src/helpers/transport/query.rs
src/query/runner/ipa.rs

This addresses https://github.com/private-attribution/ipa/issues/726

Add query config and query size in the tracing logs

---

Cargo.toml
README.md

updating the README and Cargo.toml as I'm getting started. 
A few of these benchmarks aren't working for me, and I added notes in the readme. I can delete those and open issues, if that's preferred, but I just wanted to make sure we documented it somewhere.

Readme update

---

src/protocol/aggregation/input.rs
src/protocol/aggregation/mod.rs
src/protocol/mod.rs
src/protocol/step/compact.rs
src/query/executor.rs
src/query/runner/aggregate.rs

This PR hooks up the aggregate query request to the internal protocol to be called to perform a simple aggregation of binary shares. The protocol itself is not implemented yet. Coming next.

Secure aggregation protocol interface

---

src/protocol/aggregation/input.rs
src/protocol/aggregation/mod.rs
src/protocol/mod.rs
src/query/executor.rs
src/query/runner/aggregate.rs
src/secret_sharing/decomposed.rs

Actual implementation of the simple aggregation protocol.

Implement aggregate protocol 

---

src/bin/report_collector.rs
src/cli/clientconf.rs
src/helpers/gateway/mod.rs
src/helpers/transport/in_memory/transport.rs
src/helpers/transport/query.rs
src/helpers/transport/stream/collection.rs
src/helpers/transport/stream/input.rs
src/net/client/mod.rs
src/net/http_serde.rs
src/net/server/handlers/query/create.rs
src/net/server/mod.rs
src/net/test.rs
src/protocol/aggregation/input.rs
src/protocol/aggregation/mod.rs
src/protocol/modulus_conversion/convert_shares.rs
src/query/executor.rs
src/query/runner/aggregate.rs
src/query/runner/mod.rs
src/seq_join.rs
src/test_fixture/input/sharing.rs

Just renamed a thing and made clippy happy

Rename "aggregation" to "sparse aggregation" and fix clippy

---

src/protocol/aggregation/mod.rs

We got two PRs clashing with each other.

Fix the build

---

src/ff/galois_field.rs
src/ff/mod.rs
src/protocol/boolean/comparison.rs
src/protocol/boolean/saturating_sum.rs
src/protocol/prf_sharding/mod.rs
src/secret_sharing/decomposed.rs

Adding attribution window to the OPRF attribution protocol.

OPRF attribution windowing

---

src/test_fixture/ipa.rs

Updating IPA in the clear logic to be capable of supporting either type of capping, either you cap the OLDEST stuff first, or you cap the MOST RECENT stuff first.

Supporting the opposite capping logic

---

.github/workflows/check.yml

See https://github.com/private-attribution/ipa/issues/837 for details

Temporarily disable sanitizers in GH workflow

---

src/error.rs
src/ff/galois_field.rs
src/protocol/attribution/credit_capping.rs
src/protocol/basics/apply_permutation.rs
src/protocol/basics/mul/sparse.rs
src/protocol/ipa_prf/prf_sharding/bucket.rs
src/protocol/prss/mod.rs
src/protocol/sort/apply_sort/shuffle.rs

Upgrade to Rust 1.74

---

src/helpers/buffers/ordering_sender.rs

This change makes `OrderingSender` yield chunks of equal size, by blocking writes when `written` crosses `write_size` threshold.
After stream is polled, sender becomes open for writes again.
This is required to fix #843. Tested on AWS with it and parallel execution and confirmed that this change fixes the stall.

Make `OrderingSender` yield chunks of the same size

---

ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs

Figured it out. Capping wasn't working correctly. 
Once a user reaches the cap, it should stay "saturated" forever. 
So the logic should be "this row is saturated if EITHER this row just overflowed, OR if the previous row was already saturated".
I accidentally removed this important functionality when I migrated the code to use Boolean Array.
I utilized the clever trick that @andyleiserson proposed here: https://github.com/private-attribution/ipa/pull/785#discussion_r1333647004 which allows me to compute this "OR" without any additional communication.

Adding test case for wrapping bug

---

ipa-core/src/ff/galois_field.rs
ipa-core/src/ff/mod.rs
ipa-core/src/protocol/ipa/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/feature_label_dot_product.rs
ipa-core/src/protocol/modulus_conversion/convert_shares.rs

Using the nice, new boolean array construct, which has the added bonus of making these multiplications vectorized!

Migrating the feature label dot product to use BooleanArray

---

ipa-core/src/protocol/ipa_prf/quicksort.rs

Using bitvec and other minor changes

updates suggested by Alex on quicksort

---

ipa-core/src/ff/boolean_array.rs

I don't know if this is much better than repeating "0, " 255 times, but it was an interesting exercise.

metaprogramming for boolean array values of 1

---

ipa-core/src/ff/boolean_array.rs

This might make @richajaindce less put off by the 112-bit stuff.

A nicer interface to bitarr_one

---

ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs

No tests.  @akoshelev, did you manage to find a way to make this reproducible?  One that doesn't involve writing a new scheduler?

Alex discovered this, I thought that I would land it

---

ipa-core/src/cli/playbook/ipa.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/test_fixture/ipa.rs

This plumbs in shuffle and sort
For sort, for now I have implemented a "sort key" which sorts based on timestamp, is_trigger and counter
Counter runs from 0 to num of rows per user which addresses #888

OPRF flow with all protocols plumbed in

---

ipa-core/src/protocol/ipa_prf/quicksort.rs

Making some changes suggested by @martinthomson on #892. 
Currently tests do not pass... still debugging...

Quicksort improvements

---

ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs
pre-commit

We have two unit tests failing and OPRF IPA not functioning properly that is blocking other PRs. While folks are on vacation, temporarily disabling those to allow progress on other areas. #899 is created to follow up on it

Unblock build

---

docker/helper.Dockerfile
ipa-core/src/cli/keygen.rs
ipa-core/src/cli/test_setup.rs
ipa-core/tests/helper_networks.rs

See commit messages for motivation

Fix dockerfile and allow custom expiration time for TLS certs

---

ipa-core/src/protocol/context/mod.rs

Kill the Arc inside Context::Inner

---

scripts/collect_steps.py

Fix collect_steps DEPTH_DYNAMIC_STEPS string

---

ipa-core/src/seq_join/multi_thread.rs

Replace tokio yield with sleep(1ms)

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/prf_eval.rs

Slightly simplifies trait bounds.

Add BooleanProtocols rollup trait

---

.github/workflows/check.yml

Attempting to resolve the upload failures. See https://github.com/codecov/codecov-action/issues/1359.

Update codecov action version

---

ipa-core/src/protocol/context/dzkp_field.rs
ipa-core/src/protocol/context/dzkp_validator.rs

fixes issue https://github.com/private-attribution/ipa/issues/1024

reduce test time using non-consecutive integers

---

ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/context/upgrade.rs

This is irrelevant without sparse multiplies.

Remove sparse upgrades

---

scripts/coverage-ci

Temporarily remove compact gate test coverage

---

ipa-core/src/test_fixture/sharing.rs

Additional ReconstructArr impl

---

ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

split from https://github.com/private-attribution/ipa/pull/1083.
follow up from https://github.com/private-attribution/ipa/pull/1090

changes to compute final proof, proof generator and challenge and recurse

---

ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

add constants & add small parameter set

Add constants for proof parameter sets

---

ipa-core/src/protocol/context/dzkp_field.rs

I broke main... sorry... fixing it!

Making clippy happy

---

ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

We will definitely need these two helper functions at the next stage. I've added a few tests for them that illustrate how they will be used and ensure the expected behavior.

Adding a few useful helper functions

---

ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs

In his review of #1109, @andyleiserson suggested either using a struct with a "left" and "right" or immediately destructuring. I've opted for the latter approach since the two items in the tuple returned by `gen_proof_shares_from_prss` mean different things in practice, and just destructuring and giving them descriptive names (like we do within `gen_artefacts_from_recursive_step`) is probably the way to go.

Use fewer .0 and .1

---

ipa-core/src/protocol/ipa_prf/validation_protocol/mod.rs
ipa-core/src/protocol/ipa_prf/validation_protocol/proof_generation.rs
ipa-core/src/protocol/ipa_prf/validation_protocol/validation.rs

compute challenge + test + move BatchToVerify

Challenge for DZKP Verification

---

ipa-core/src/ff/galois_field.rs

Miri checks fail due to errors in main

fix miri errors

---

ipa-core/src/ff/galois_field.rs
ipa-core/src/protocol/ipa_prf/validation_protocol/validation.rs

Just some refactoring to remove code duplication and mutable objects.

cleaning up the challenge generation code

---

ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

split u_or_v recursion and verify_proof in verifier.rs

split u_or_v recursion and verify_proof

---

ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/mul/semi_honest.rs
ipa-core/src/protocol/basics/reveal.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/addition_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs

Split from #1112; builds on #1128.

Use upgraded context for tests of some boolean protocols

---

ipa-core/src/protocol/basics/mul/mod.rs

Remove `impl BooleanArrayMul<SemiHonestContext<...>>`

---

ipa-core/src/protocol/basics/mul/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/secret_sharing/vector/impls.rs

add a counter for chunks in validate such that chunk specific contexts for the validation can be generated.

enumerate chunks for chunk specific contexts

---

ipa-core/src/protocol/context/dzkp_field.rs
ipa-core/src/protocol/context/dzkp_validator.rs

Deprecates SingleUVBlock and replaces streams over arrays of field elements to streams over field elements.

Deprecate SingleUVBlock

---

ipa-core/src/protocol/ipa_prf/validation_protocol/validation.rs

Adding Ben's suggestion from https://github.com/private-attribution/ipa/pull/1159

use try_join for send and receive in validation.rs

---

ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs
ipa-core/src/protocol/ipa_prf/validation_protocol/validation.rs
ipa-core/src/utils/arraychunks.rs

replaces streams with iterators by using chunk_array instead of chunks

Replace uv stream in verifier and validation

---

ipa-core/src/protocol/ipa_prf/validation_protocol/validation.rs

needed since Mutex cannot be used across await points, see issue: https://github.com/private-attribution/ipa/pull/1164

split verify into fn and async fn

---

ipa-core/src/utils/arraychunks.rs

remove flags and add Martin's suggestion to array chunk. Andy is implementing default for more primefield types. Afterwards we can replace Primefield with Default.

add Martin's suggestion to improve array chunk iterator implementation

---

ipa-core/src/protocol/context/dzkp_field.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/context/mod.rs

now that DZKPs are done, I removed some dead code flags

remove dead code flags from malicious security and validation

---

ipa-core/src/helpers/hashing.rs
ipa-core/src/protocol/ipa_prf/malicious_security/mod.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs

Feedback from @martinthomson was that we should not use lambda as it's hard to type.

Matching IETF draft. Using L not lambda

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/reveal.rs

I can't remember why I added this, but it doesn't seem to be necessary.

Remove `N` const parameter from `Reveal`.

---

ipa-core/src/protocol/dp/mod.rs
ipa-core/src/protocol/ipa_prf/mod.rs

make dp test for measuring network not print out lots of things to the terminal all the time.

Make DP test quite

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/breakdown_reveal.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/quicksort.rs

Add DZKP malicious security support to attribution.
This does not add a test. I do have a branch with a test for this, but to make the test work I also ended up adding malicious security to aggregation. I'll make a separate PR for that.

upgrading attribution

---

in-market-test/v2/README.md
in-market-test/v2/ansible/parse_logs.py

added some clarifications to the in-market-test README and updated `parse_logs.py` to provide either table or tsv output.

In market test updates

---

in-market-test/v2/ansible/provision.yaml

adding stall detection to the ansible build script

add stall detection to ansible build script

---

in-market-test/v2/hpke/encrypt_report.py

Added parsing comma delimited format:
File format: <timestamp>,<match_key>,<event_type>,<breakdown_key>,<trigger_value>
Output 3 reports, 1 for each helper.

Python HPKE sample code add csv file format and output 3 reports

---

README.md

Add documentation to README.md for how to pass a custom epsilon command line or disable the default DP for outputs.

update README with how to pass DP params on command line

---

ipa-core/src/error.rs
ipa-core/src/ff/boolean_array.rs
ipa-core/src/ff/galois_field.rs

conversion between BA types and Vec<Gf32Bit>. Also adds pub function that allows to get Gf32Bit as raw slice.

Conversion between Boolean Array and Gf32Bit

---

ipa-core/src/protocol/ipa_prf/shuffle/base.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs

change shuffle signature, store intermediate messages and tests

changes to shuffle function

---

ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/context/batcher.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/context/validator.rs
ipa-core/src/protocol/dp/mod.rs
ipa-core/src/protocol/dp/step.rs
ipa-core/src/protocol/ipa_prf/aggregation/mod.rs
ipa-core/src/protocol/ipa_prf/aggregation/step.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/mod.rs
ipa-core/src/protocol/ipa_prf/prf_sharding/step.rs
ipa-core/src/protocol/step.rs

Adds test coverage for malicious attribution and aggregation

Malicious aggregation and DP noising

---

ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/base.rs
ipa-core/src/protocol/ipa_prf/shuffle/malicious.rs
ipa-core/src/protocol/ipa_prf/shuffle/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/step.rs
ipa-core/src/query/runner/oprf_ipa.rs

creating shuffle trait with different shuffle implementations for malicious and semi honest + plumbing it in the executor

Malicious Shuffle Plumbing

---

ipa-core/Cargo.toml
ipa-core/src/protocol/context/dzkp_validator.rs

Also boxed a future that was triggering clippy

Tonic update to deal with https://rustsec.org/advisories/RUSTSEC-2024-0376

---

ipa-core/src/protocol/context/dzkp_validator.rs

The extra panic is noisy and potentially confusing.

Skip the unverified multiplies check if we're already unwinding

---

ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/ipa_prf/shuffle/sharded.rs

Internally, reshard used streams already, so it is only a matter of changing the API and connecting things together

Make reshard work with streams too

---

ipa-core/src/protocol/ipa_prf/shuffle/sharded.rs

fix typo in shuffle/sharded.rs

---

ipa-core/src/hpke/info.rs
ipa-core/src/hpke/mod.rs
ipa-core/src/report/hybrid.rs
ipa-core/src/report/hybrid_info.rs
ipa-core/src/report/ipa.rs
ipa-core/src/report/mod.rs

Some initial code to serialize and encrypt Hybrid Impression Reports. If this all looks good, I'll follow up with Conversion Reports.

Hybrid Impression Report Encryption

---

ipa-core/Cargo.toml
ipa-core/build.rs
ipa-core/src/protocol/ipa_prf/mod.rs
ipa-core/src/report/hybrid.rs
scripts/coverage-ci

This fixes #1301 and cleans up assertions

Fix compact gate build errors

---

ipa-core/src/lib.rs
pre-commit

Fix for #1301 broke our `pre-commit` script

Fix pre-commit script

---

ipa-metrics/src/collector.rs
ipa-metrics/src/context.rs
ipa-metrics/src/controller.rs
ipa-metrics/src/key.rs
ipa-metrics/src/label.rs
ipa-metrics/src/lib.rs
ipa-metrics/src/store.rs

These changes are required to make the metric engine work in IPA. See commit messages for details

Metrics ergonomic and unit test improvements

---

ipa-core/src/ff/boolean_array.rs
ipa-core/src/protocol/ipa_prf/malicious_security/lagrange.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
ipa-core/src/secret_sharing/vector/array.rs

See commits for details. I noticed those while working on RP25519 perf

Fix a few issues in serialization logic + some code cleanup

---

ipa-core/src/report/hybrid.rs

Remove OPRF code from hybrid.rs

---

ipa-core/src/protocol/context/mod.rs

#1029 has been fixed already, time to take advantage of it

Generate half of randomness required to pick a shard in Shuffle

---

ipa-core/Cargo.toml
ipa-core/src/ff/ec_prime_field.rs
ipa-core/src/ff/galois_field.rs
ipa-core/src/ff/prime_field.rs
ipa-core/src/helpers/hashing.rs
ipa-core/src/protocol/basics/check_zero.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/mul/mod.rs
ipa-core/src/protocol/basics/share_validation.rs
ipa-core/src/protocol/ipa_prf/shuffle/malicious.rs
ipa-core/src/protocol/ipa_prf/validation_protocol/validation.rs
ipa-core/src/secret_sharing/replicated/malicious/additive_share.rs

I suspect it would be quite difficult to construct a meaningful attack on one of these, but it still seems wise to use constant-time comparisons where best practice would dictate doing so.

Use constant-time comparisons

---

ipa-core/src/protocol/hybrid/breakdown_reveal.rs

nothing really to review here, just a copy of the breakdown_reveal.rs file to make #1445  easier to review.

copy IPA breakdown_key reveal verbatim

---

.github/workflows/docker.yml
README.md
docker/helper.Dockerfile
docker/report_collector.Dockerfile

Also adding some utilities to the docker. I can remove them after we're done setting up the sharded environment.

Adding Report Collector docker creation

---

ipa-core/src/cli/keygen.rs
ipa-core/src/ff/boolean_array.rs
ipa-core/src/helpers/buffers/ordering_sender.rs
ipa-core/src/helpers/hashing.rs
ipa-core/src/helpers/stream/chunks.rs
ipa-core/src/protocol/basics/mod.rs
ipa-core/src/protocol/basics/mul/malicious.rs
ipa-core/src/protocol/context/dzkp_malicious.rs
ipa-core/src/protocol/context/dzkp_semi_honest.rs
ipa-core/src/protocol/context/dzkp_validator.rs
ipa-core/src/protocol/context/malicious.rs
ipa-core/src/protocol/context/mod.rs
ipa-core/src/protocol/context/prss.rs
ipa-core/src/protocol/context/semi_honest.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/comparison_and_subtraction_sequential.rs
ipa-core/src/protocol/ipa_prf/boolean_ops/share_conversion_aby.rs
ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
ipa-core/src/protocol/ipa_prf/malicious_security/verifier.rs
ipa-core/src/protocol/ipa_prf/oprf_padding/distributions.rs
ipa-core/src/protocol/ipa_prf/oprf_padding/mod.rs
ipa-core/src/protocol/prss/mod.rs
ipa-core/src/query/completion.rs
ipa-core/src/query/processor.rs
ipa-core/src/secret_sharing/replicated/malicious/additive_share.rs
ipa-core/src/secret_sharing/replicated/semi_honest/additive_share.rs
ipa-core/src/secret_sharing/vector/array.rs
ipa-core/src/telemetry/stats.rs
ipa-core/src/test_fixture/app.rs
ipa-core/src/test_fixture/ipa.rs
ipa-step-derive/src/track.rs

Massive change due to new clippy lints

Upgrade to Rust 1.83

---

ipa-core/src/bin/test_mpc.rs
ipa-core/src/cli/config_parse.rs
ipa-core/src/cli/keygen.rs
ipa-core/src/cli/playbook/mod.rs
ipa-core/src/cli/playbook/sharded_shuffle.rs
ipa-core/src/cli/test_setup.rs
ipa-core/src/helpers/transport/routing.rs
ipa-core/src/net/client/mod.rs
ipa-core/src/net/error.rs
ipa-core/src/net/transport.rs
ipa-core/src/protocol/ipa_prf/shuffle/sharded.rs
ipa-core/src/protocol/ipa_prf/shuffle/step.rs
ipa-core/src/query/processor.rs
ipa-core/tests/common/mod.rs
ipa-core/tests/helper_networks.rs

This builds on top of #1461 and adds an HTTP end-to-end test for sharded shuffle

Sharded shuffle http e2e test

---

scripts/create-sharded-conf.py

Updated the script to generate the hostnames in the way K8s likes them to be.

Using k8s supported DNS format

---

ipa-core/tests/hybrid.rs

This is stacked on #1472, and won't actually work until we can encrypt the input with the work that @tyurek is doing.

Hybrid integration test

---

scripts/presigned-s3-urls.sh

update presigned url script expires-in flag to 7 days - max allowed by aws

s3 presigned urls hot fix

---

.github/workflows/check.yml

Restore sanitizers to ubuntu-latest
